### ISSUE TITLE
Use system clipboard by default

### ISSUE THREAD

**Issue by gcoelho05** [martanne/vis#1003]
I have been using neovim for some years now, but vis seems like a much saner way to do things and I would love to make it my daily driver.

I'm not sure this is the right place to ask for help and if it's not, please forgive me and point me to the right direction.

---

I wanted to have vis use the system clipboard for everything. In neovim, this is how I would do that:
```
set clipboard+=unnamedplus
```
How can I replicate this behaviour in my lua config?

Also, I would be grateful if someone pointed me to some documentation on how to configure vis with lua.

**Comment by erf** [comment]
The is a documentation section in the Readme.md that links to the Lua Api. Also check out the Wiki on plugins.

**Comment by mcepl** [comment]
1. https://github.com/martanne/vis/wiki is a pretty good starting point for documentation of vis
2. /usr/bin/vis-clipboard (that’s the location on my system, yours may vary) is a shell script

**Comment by jpaulogg** [comment]
Applying @deepcube's diff seems like the best way to me. You can also do something like this `:map! normal d <vis-register>+<vis-operator-delete>`.

In your viscr.lua: 
```lua
vis:map(vis.modes.NORMAL, "d", "<vis-register>+<vis-operator-delete>")
```

From config.h:
```c
{ "d",                  ALIAS("<vis-register>+<vis-operator-delete>") },
```

Abraços de Minas Gerais!

**Comment by leorosa** [comment]
In addition to @jpaulogg answer, you may also find useful to copy the system clipboard content into the main register, by including the following line somewhere in your visrc.lua:
```
vis.registers['"'] = { io.popen("vis-clipboard --paste"):read("*all") }
```

**Comment by gabriel-coelho** [comment]
Thanks everyone for the answers.
I have found @deepcube's solution to be my favourite, but everyone helped me with their good insight

**Comment by bscuron** [comment]
> 

Did these changes work for you on a Mac? I am currently trying to use the system clipboard by default, but I receive this message when I compile with these changes: "Command failed System clipboard not supported". I also tried just setting the primary register = clipboard register. This works inside of vis, but when I paste outside of the editor it does paste the contents of the yanked text.

Please let me know if you have any additional ideas that may help. Thank you.

**Comment by mcepl** [comment]
@bscuron It would be probably better to write this as a separate ticket rather than continue this never ending story.

**Comment by gcoelho05** [comment]
Sorry to reopen this.
@deepcube's solution was helpful, and I am now able to copy something from my e.g. browser to vis with `p`, yet, something I yank in vis with `y` cannot be copied into my browser. How can I get this to work?

**Comment by rnpnr** [comment]
You should be able to. The text is copied to `PRIMARY` not `CLIPBOARD`. You probably need to use middle mouse click to paste into your browser.

**Comment by mcepl** [comment]
@rnpnr Isn’t this ticket long overdue for closing?

**Comment by rnpnr** [comment]
Yes I was waiting for confirmation about using middle mouse button but
I am certain it is correct.
