### ISSUE TITLE
How to place cursor at the left part of multiple selection?

### ISSUE THREAD

**Issue by lbvf50mobile** [martanne/vis#1004]
Greetings.

Second day I try to repeat actions from https://asciinema.org/a/41361 that I found in this [pdf](https://www.brain-dump.org/gsoc17/vis-cosin.pdf).

Time code is: 00:24.

After selection `:x/^static .* cmd_[a-z]+\(.*;` cursor moves inside the selection from the right part to the left.

I carefully read the help, even try to use `:y/^static bool` to remove left par of the selection, but in the demo there are some keys. What are they?

May be it is `vis-selection-flip                    Flip selection, move cursor to other end ` or something else? Then how to bind this action to a hot-key?

[Here](https://martanne.github.io/vis/man/vis.1.html) I found that `_`  **flip selection direction, swap cursor and anchor**, but when look in the `:help` this symbol used for trimming from white spaces. 

Thank you.

**Comment by thinlines** [comment]
I believe what you're looking for is <kbd>o</kbd>. From the help:

```
  o                     Flip selection, move cursor to other end
```

This is what it says in the man page on my computer, too, but maybe the formatting is messed up in the link you posted.

**Comment by lbvf50mobile** [comment]
[thinlines](https://github.com/thinlines), thank you a lot. It is that feature.
