### ISSUE TITLE
Markdown header style hard coded in markdown.lua

### ISSUE THREAD

**Issue by realwhz** [martanne/vis#1005]
Hello.  Markdown uses a hard coded style for headers.  The style cannot be controlled by theme.  Is it expected?
https://github.com/martanne/vis/blob/master/lua/lexers/markdown.lua#L85-L92

It is not a big deal.  Just a bit inconsistent.

Thanks.

**Comment by mcepl** [comment]
Lexers are not maintained as part of vis any more, please, push this ticket to https://github.com/orbitalquark/scintillua/issues. Thank you.
