### ISSUE TITLE
Meta feature request: Discussion section for QA, newbie questions, idiomatic usage, etc.

### ISSUE THREAD

**Issue by hholst80** [martanne/vis#1006]
GitHub has this reasonable new feature called "Discussions" which is basically a integrated forum. 

Do you think it would make sense to have that here? Us users of vis are quite few, and I consider myself a newbie still and I think a forum for non-issues would be quite nice to have.

**Comment by ninewise** [comment]
You're welcome to ask questions, start discussions or just say hi on both the mailing list https://lists.sr.ht/~martanne/devel (slightly more serieus) and the IRC channel (#vis-editor on libera.chat, open for casual talk). I don't mind general questions as tickets on source hut or here either. I'd rather not add another medium.
