### ISSUE TITLE
Bash lexer crashes when end tag of here document is off-screen

### ISSUE THREAD

**Issue by dragonmaus** [martanne/vis#1008]
If a bash script contains a here document that is only partially on-screen (that is, the start [the bit with `<<` or `<<-`] is visible but the end is not), the lexer will crash with the following error:
```
/path/to/vis/lexers/bash.lua:<linenumber>: attempt to concatenate a nil value (local 'delimiter')
```

This crash is persistent, and will reoccur every time vis tries to render the partially off-screen here document.

(The inverse is not true; that is, the lexer will not crash if the end tag is visible but the start is not.)

----

Vis version: `vis v0.7 +curses +lua +acl`

**Comment by ninewise** [comment]
IIRC this was a bug in the bash lexer and I believe I've seen a fix for this pass by at scintillua.

OK found it: https://github.com/orbitalquark/scintillua/pull/43

**Comment by jvvv** [comment]
Rather than reverting the commit for f55312ba, I have tested [b27670f](https://github.com/jvvv/vis/commit/b27670f20525542f0b5f65620f11c2c4bfe12ce6). My intent with this change is that I think it maintains the
point of the original commit while also trying to address this issue.
