### ISSUE TITLE
Planned release? v0.8?

### ISSUE THREAD

**Issue by jgarte** [martanne/vis#1012]
The title says it all.

**Comment by mcepl** [comment]
I think there are many pull requests in the queue which could be squeezed in first.

**Comment by euclaise** [comment]
Maybe a release to-do list would be helpful?

**Comment by mcepl** [comment]
> Maybe a release to-do list would be helpful?

I have produced something in https://github.com/martanne/vis/issues/1001#issuecomment-1140220807 but it is incomplete. Basically the list of open pull requests is the best what we have.
