### ISSUE TITLE
Use object-verb order like Kakoune, in other words reverse order

### ISSUE THREAD

**Issue by GReagle** [martanne/vis#1014]
I really like Kakoune's idea of puting the object first and it being automatically highlighted, then typing in the action command like 'd' for delete.  Much more interactive and clear.  Would you consider this change for vis?  This is the way that x already works so it would be more consistent too.

from https://github.com/mawww/kakoune/wiki/Migrating-from-Vim
delete a word:
    vim: dw
    kak: wd

**Comment by mcepl** [comment]
https://github.com/martanne/vis/wiki/Differences-from-Kakoune

I think the author is fully aware of differences and he doesn’t seem to be interested in change.

**Comment by erf** [comment]
You could perhaps make your own kak keybindings in the config.h or using the Lua API.

**Comment by GReagle** [comment]
> You could perhaps make your own kak keybindings in the config.h or using the Lua API.

I assume that changing the verb-object order is not possible just by changing keybindings.  However, that does give me the idea of making the change into a new mode.

**Comment by GReagle** [comment]
Very useful deepcube, thank you!
