### ISSUE TITLE
Not sure how multiple cursors work

### ISSUE THREAD

**Issue by ConceitedZebra** [martanne/vis#1016]
I'm trying to learn what operations are available when using multiple cursors. I'm coming from Kakoune, where you can edit "normally" with multiple cursors active. The example below splits the buffer on newlines and then I delete text surrounding the region I'm interested in.

https://user-images.githubusercontent.com/71189698/175874593-73f2b4d5-23c8-466b-9903-169acf06336b.mp4

I tried to do the same in Vis by selecting the buffer with `:,` and then splitting on newlines with `:x`, but at this point it doesn't seem like I can make normal edits that are reflected in each selection simultaneously. 

Do you operate on multiple regions exclusively with "c/text/" commands in Vis? How could I go about recreating the edits in the video above (deleting up to the first semicolon and after the number on each line)?

**Comment by erf** [comment]
After making a selection with `:x` you can press escape to go to normal mode and make edits per cursor.

Also see `man vis` or the [the online docs](http://martanne.github.io/vis/man/vis.1.html#Multiple_Selections) or the [Differences from Kakoune](https://github.com/martanne/vis/wiki/Differences-from-Kakoune) in the Wiki.

**Comment by ConceitedZebra** [comment]
Ahh I had a colorscheme issue that made it look like there was only a single active cursor in that situation. Thank you for answering!
