### ISSUE TITLE
vis:message functionality changed in commit 22d4709e8a30c8feb9b4da7d78e0ea6a57af83e8

### ISSUE THREAD

**Issue by erf** [martanne/vis#1034]
After commit 22d4709e8a30c8feb9b4da7d78e0ea6a57af83e8 I'm not able to concat messages to a single new window, instead a new window is created for each message. I found this when using https://github.com/erf/vis-plug plugin with the `vis-list` or `vis-outdated` command. Would it be possible to revert to the old behaviour?

**Comment by deepcube** [comment]
On Thu Aug 11, 2022 at 4:15 AM MDT, Erlend wrote:
> After commit 22d4709e8a30c8feb9b4da7d78e0ea6a57af83e8 I'm not
> able to concat messages to a single new window, instead a new
> window is created for each message. I found this when using
> https://github.com/erf/vis-plug plugin with the `vis-list` or
> `vis-outdated` command. Would it be possible to revert to the old
> behaviour?

Sorry about that.  I'll revert it for now and dig into it later to
find a way to implement this without causing that issue.

Can you give me a minimal example that worked before but does not
work now?  Then I can use it to test against.

**Comment by erf** [comment]
Hi @deepcube i've made a small example visrc.lua file which looks like this:

```Lua
require('vis')

vis.events.subscribe(vis.events.INIT, function()
        vis:message('hello 1')
        vis:message('hello 2')
end)

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
        vis:message('hello 3')
        vis:message('hello 4')
end)
```

In the latest (d3cb76e) where the fix is reverted it prints the following on opening the editor:

<img width="877" alt="Screenshot 2022-09-03 at 12 45 27" src="https://user-images.githubusercontent.com/1562523/188267230-0312e258-f2a6-4d96-8399-da908ef8cab4.png">


In commit f3828ef it just seem to hang now when i open the editor:

<img width="877" alt="Screenshot 2022-09-03 at 12 54 34" src="https://user-images.githubusercontent.com/1562523/188267276-02cdda65-e396-49aa-8d75-060ae6c4950a.png">

If i comment out the `vis:message` in the `WIN_OPEN` event so it looks like this:

```Lua
require('vis')

vis.events.subscribe(vis.events.INIT, function()
        vis:message('hello 1')
        vis:message('hello 2')
end)

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
        --vis:message('hello 3')
        --vis:message('hello 4')
end)
```

I get the following:

<img width="877" alt="Screenshot 2022-09-03 at 12 55 29" src="https://user-images.githubusercontent.com/1562523/188267309-81600e9a-c88a-4ac7-bcb7-d7eca3e52a51.png">

BTW:

It would be nice if i could choose where the new window would appear.
