### ISSUE TITLE
Is it possible to feedkeys without recording them?

### ISSUE THREAD

**Issue by royapardaz** [martanne/vis#1035]
Is it possible to feedkeys without recording them? For example suppose I'm in insert mode and I want to remap the Enter key:

```lua
    vis:map(vis.modes.INSERT, "<Enter>", function(keys)
        vis:info('<Enter> key pressed')
        vis:feedkeys('<vis-insert-newline>')
    end)
```

The mapping is correct, but it records something like this: `<Enter><vis-insert-newline>` which obviously is incorrect and it inserts two Enter when using the dot command. I know there are workarounds, but sometime I don't find anything besides the function `feedkeys`.

**Comment by ninewise** [comment]
There's (afaik) no such function. I do agree a 'rewind' of consumed keys while recording would make sense though. For now I'm afraid you'll have to stick to one of the workarounds.
