### ISSUE TITLE
Transparent background and setting options by default

### ISSUE THREAD

**Issue by swindlesmccoop** [martanne/vis#1040]
I know in other ncurses programs that it's possible to implement this by adding
```
use_default_colors();
assume_default_colors(-1,-1);
```
to whatever file/function is responsible for handling drawing, however by adding the latter line under the former in `ui-terminal-curses.c`,  however it did not do anything. I have alpha set on my terminal already, and I would prefer that vis respects that and does not try and draw its own background. I'd prefer to be able to set this option myself in the source code.

Speaking of setting options in source code, is it possible? Say that I always want to show numbers, no matter what file I'm opening - is it possible to do that in source? I want to be able to fully configure it only in source without the need of any Lua.

**Comment by clarkep** [comment]
You don't have to change the code, just use 'back:default' in your style definition. I don't know why there aren't any of the example styles that do this, but it is possible and documented in the Wiki.

**Comment by clarkep** [comment]
Not sure why you want to avoid Lua but you can use 'back:default' in your style definition to avoid drawing a background.

**Comment by SadielEd** [comment]
Hello I am using vis version 0.9 +curses +lua +acl in foot terminal and it respects my theme and transparency by default.
So maybe this issue can be closed.

![vis-screenshot](https://github.com/user-attachments/assets/dfdac7e8-391f-414e-97af-264d3da4cd75)

**Comment by rnpnr** [comment]
Thanks for the info! I thought it should but didn't really set anything up for testing.
