### ISSUE TITLE
Why every time I want to exit Command I had to hit Esc 2 times and wait for several seconds?

### ISSUE THREAD

**Issue by faustzero1** [martanne/vis#1041]
I had to hit Esc 2 times and between that **1st** key press and **2nd** key press I need to wait for several seconds to make it really exit to normal mode.

Otherwise, I got this message:
`<M-Escape>`

**Comment by raphael-proust** [comment]
Sounds like this topic covered in the FAQ https://github.com/martanne/vis/wiki/FAQ#m-key-is-inserted-whenever-i-press-escape-and-key-in-short-succession
