### ISSUE TITLE
terminal native colorschemes?

### ISSUE THREAD

**Issue by wael444** [martanne/vis#1044]
currently is it possible to use the terminal's colors (eg. ANSI (`\e[1;31m`)) instead of internal vis colorschemes?

**Comment by ninewise** [comment]
Check this thread: https://github.com/martanne/vis/issues/1027

**Comment by mcepl** [comment]
@ninewise, isn’t this just a duplicate of #1027? Shouldn’t it be closed as such?

**Comment by wael444** [comment]
it still has,,,not been revealed to me how to make a terminal native colorschrme

**Comment by wael444** [comment]
> as it's not accessible in the editor

Well, that just means this issue stays open.
Isn't `ESC[X;XXm` possible with colors?

**Comment by ninewise** [comment]
Well it is still a duplicate, and the other issue has more info.

**Comment by apprehensions** [comment]
https://github.com/martanne/vis/blob/1a958f221404b09cb8b0612fb34301e6b9783cf9/ui-terminal-vt100.c#L56-L64

this simply needs to be extended to the other 8 colors; like `32` and `42`, both being normal and high green color.
