### ISSUE TITLE
`%` in filename results in `Command failed`

### ISSUE THREAD

**Issue by Eolien55** [martanne/vis#1046]
When the filename contains a '%', `vis` warns `Command failed` .

**Comment by ninewise** [comment]
Could you be more specific? `vis %.txt` works fine, here. What command are you executing?

**Comment by mcepl** [comment]
I think he wants `%` as a variable with the current document’s filename (as it is [done in vim](https://vimhelp.org/cmdline.txt.html#cmdline-special)). `vis` doesn’t support this, you must use `vis_filename` environmental variable.

If you would like compatibility with `vim` in this, then this is a duplicate of #1013.

**Comment by Eolien55** [comment]
> I think he wants % as a variable with the current document’s filename
I was talking about `vis` outputting `Command failed`.

The issue is with one of the plugins, not `vis` itself (more specifically the `vis-title` one, which uses `printf` and interprets `%` as a special character). Sorry about that
