### ISSUE TITLE
suggestion: scroll the view like the helix editor

### ISSUE THREAD

**Issue by erf** [martanne/vis#1048]
In the helix editor you can scroll the view using the mouse pad, the cursor will follow if close to the edge of the screen. This is different than scrolling the cursor in vis and feels more intuitive.

**Comment by ninewise** [comment]
This is how I scroll in vis, if I use the mouse. My terminal emulator send Ctrl-y and Ctrl-e signals when the mouse scrolls up and down. vis (and several other terminal interfaces) interpret these correctly.
