### ISSUE TITLE
trivial: one single warning during compilation

### ISSUE THREAD

**Issue by hholst80** [martanne/vis#1058]
during compilation I got this single warning (gcc v11)

```
text-io.c:245:17: warning: ignoring return value of ‘fchdir’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  245 |                 fchdir(cwd);
      |                 ^~~~~~~~~~~
```

It would be nice to get a 100% warning free compile ;-)

**Comment by mcepl** [comment]
Proposed patch is https://lists.sr.ht/~martanne/devel/patches/37376

**Comment by ninewise** [comment]
That patch was merged, so I'm closing this issue here.
