### ISSUE TITLE
vis-plugins - a collection of vis plugins and themes

### ISSUE THREAD

**Issue by erf** [martanne/vis#1059]
I made a repo at [https://github.com/erf/vis-plugins](https://github.com/erf/vis-plugins) with a list of all the vis [plugins](https://github.com/martanne/vis/wiki/Plugins) and [themes](https://github.com/martanne/vis/wiki/Themes) in the wiki.

It includes a [web page](https://erf.github.io/vis-plugins/), hosted by github, to show these plugins with names, descriptions, url to repo, file path and images for themes. You can toggle between showing plugins / themes and also search for plugins.

I wanted a nicer way to see all the available themes and to easily copy the configuration to [vis-plug](https://github.com/erf/vis-plug).

Plugins and themes are kept in two separate js files. Feel free to send a PR to update these or to improve the web page.

Not a direct vis issue (so feel free to close), but i thought it might be interesting to get some opinions or suggestions.

**Comment by mcepl** [comment]
You can mention it on https://github.com/martanne/vis/wiki/Plugins (hint: it’s a wiki), but otherwise yes, this should be closed.
