### ISSUE TITLE
File Navigation

### ISSUE THREAD

**Issue by bscuron** [martanne/vis#1063]
This is not an issue with vis. I was wondering what is the best way to navigate between multiple files easily using vis. Currently, I am using tmux, creating a new tmux window, and using fzf, rg, and fd to navigate. If anyone has better recommendations, please let me know.

**Comment by ninewise** [comment]
I use [skim (similar to fzf)](https://github.com/ninewise/dotfiles/blob/master/config/vis/visrc.lua#L37-L58) and [rg](https://github.com/ninewise/dotfiles/blob/master/config/vis/visrc.lua#L73-L93) as well, but from within vis.

**Comment by mcepl** [comment]
There is `open` command, but mostly vis is very old fashioned in the style of “Unix is IDE” https://blog.sanctum.geek.nz/series/unix-as-ide/ .

**Comment by bscuron** [comment]
> I use [skim (similar to fzf)](https://github.com/ninewise/dotfiles/blob/master/config/vis/visrc.lua#L37-L58) and [rg](https://github.com/ninewise/dotfiles/blob/master/config/vis/visrc.lua#L73-L93) as well, but from within vis.

Thank you for sharing your config. I appreciate the help.

**Comment by bscuron** [comment]
> There is `open` command, but mostly vis is very old fashioned in the style of “Unix is IDE” https://blog.sanctum.geek.nz/series/unix-as-ide/ .

Thank you for telling me about open, I like how you can use glob patterns.

**Comment by bscuron** [comment]
Using the replies from @ninewise and @mcepl, I was able to a good way to navigate 
```
-- Find files
vis:command_register("fd", function(argv, force, cur_win, selection, range)
    local search_dir = io.popen("IFS='\n' | read INPUT | echo $INPUT | vis-menu"):read()
    local out = io.popen("fd . " .. search_dir .. " --type f | fzf --color=bw"):read()
    if out then
        local parent_dir = io.popen("dirname " .. out):read()
        vis:command("cd " .. parent_dir)
        vis:command(string.format(argv[1]..' "%s"', out))
        vis:feedkeys("<vis-redraw>")
    end
end, 'fuzzy out search')

vis:map(vis.modes.NORMAL, " f", function()
    vis:command('fd e')
end)

-- Grep files
vis:command_register("rg", function(argv, force, cur_win, selection, range)
    local search_dir = io.popen("IFS='\n' | read INPUT | echo $INPUT | vis-menu"):read()
	local out = io.popen('rg --color=never --line-number --no-heading --smart-case "${*:-}" ' .. search_dir .. ' | fzf --color=bw'):read()
	if out then
		local filename = string.find(out, ':')
		local linenumber = string.find(out, ':', filename + 1)
		vis:command(string.format(argv[1]..' "%s"', string.sub(out, 0, filename - 1)))
		vis.win.selection:to(tonumber(string.sub(out, filename + 1, linenumber - 1)), 0)
		vis:feedkeys("<vis-redraw>")
	end
end, 'fuzzy grep open')

vis:map(vis.modes.NORMAL, " g", function()
	vis:command('rg e')
end)
```

**Comment by mcepl** [comment]
> Thank you for telling me about open, I like how you can use glob patterns.

You know there is the `vis(1)` manpage, right?
