### ISSUE TITLE
Yank to system clipboard

### ISSUE THREAD

**Issue by erf** [martanne/vis#107]
Option to yank to system clipboard.

**Comment by martanne** [comment]
I assume you are talking about the `"*` and `"+` registers? Not a big fan of using system specific APIs (especially for Mac OS X, as I have *no* clue about them), the way this should be supported is via external tools such as [xsel](http://www.vergenet.net/~conrad/software/xsel/).

**Comment by erf** [comment]
I understand, but i found this if it helps: http://www.alecjacobson.com/weblog/?p=2376

**Comment by martanne** [comment]
So `pbcopy` and `pbpaste` are the [Mac OS X equivalents](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/pbpaste.1.html), are these standard i.e. pre installed on all systems?

Then there is the question of how to support Wayland ...

**Comment by erf** [comment]
It seems so - i have it preinstalled on my macbook OSX 10.11.1.

Maybe you need to make a system/platform folder ..

**Comment by erf** [comment]
Maybe implement libuv, and make support for plugins?

**Comment by greduan** [comment]
pbcopy and pbpaste are installed with every OS X system, at least since Snow Leopard I think. It's probably in all OS X versions. In any case it's been pre-installed with the last 3 versions.

**Comment by twe4ked** [comment]
The man page for `pbcopy` is dated `January 12, 2005`.

**Comment by greduan** [comment]
Solid evidence. lol Can't believe I didn't think of that.

**Comment by martanne** [comment]
The latest commits use the helper scripts [`vis-copy`](https://github.com/martanne/vis/blob/master/vis-copy) and [`vis-paste`](https://github.com/martanne/vis/blob/master/vis-paste) to access the system clipboard.

After a successful `make install` you can try to yank into either the `"*` or `"+` register (they are currently the same).

It might or might not work on Mac OS X ...

**Comment by erf** [comment]
It works!

**Comment by xomachine** [comment]
The selection is not copied to the system clipboard (and cannot be used from external apps) via xsel without -b option. By default xsel uses XServer's primary buffer, which being replaced by clipboards content in some cases. Should not this option be added to vis-copy?

**Comment by TieDyedDevil** [comment]
Thanks for this. It'll save a lot of keystrokes.

Note that :w !shell-command... also works; this may be used in the short term to access xsel -ib.
 
On Sun, Jan 31, 2016 at 01:28:29AM -0800, Marc André Tanner wrote:
>    The latest commits use the helper scripts [1]vis-copy and [2]vis-paste
>    to access the system clipboard.
> 
>    After a successful make install you can try to yank into either the "*
>    or "+ register (they are currently the same).
> 
>    It might or might not work on Mac OS X ...
> 
>    —
>    Reply to this email directly or [3]view it on GitHub.
> 
> References
> 
>    1. https://github.com/martanne/vis/blob/master/vis-copy
>    2. https://github.com/martanne/vis/blob/master/vis-paste
>    3. https://github.com/martanne/vis/issues/107#issuecomment-177447573

-- 
"I think as musicians, we have more vision than we credit ourselves for. We should dive into it without reserve, and take the sort of risks it takes to be divisive and impactful. Things have yet to be done."
   Aaron Fowler Clark

"Do not seek to follow in the footsteps of the masters. Seek what they sought."
   Matsuo Basho

**Comment by erf** [comment]
Thoughts on adding an option 'set clipboard=unnamed' to sync default yank to clipboard?

**Comment by martanne** [comment]
I changed the scripts to use `xsel -b`.

As for the clipboard synchronization, I currently have no plans to implement that ...
