### ISSUE TITLE
 Feature Request: Lexer for sxhkdrc

### ISSUE THREAD

**Issue by jgarte** [martanne/vis#1077]
See the syntax highlighting provided by these Emacs packages for inspiration:

https://github.com/protesilaos/sxhkdrc-mode
https://github.com/xFA25E/sxhkd-mode

Should this go to upstream?

**Comment by ninewise** [comment]
Yes, please.

**Comment by tosch42** [comment]
@ninewise is there a reason you keep this (and #1076) open, even if it's "solved"? It seems to just pollute the issue list. Or do you wait until it's accepted upstream?

**Comment by ninewise** [comment]
I wait a bit to allow people to close the issue themselves, if they consider it done. But well.
