### ISSUE TITLE
Cursor stays in place when inserting text in a new file

### ISSUE THREAD

**Issue by erf** [martanne/vis#1084]
Cursor now stays in the same place when inserting text in a new file.

How to recreate:

1. open a new file
2. press `i` to insert text 
3. enter some text `hello`
4. cursor stays at first position `h`

This seem to have been introduced in commit: c22b2c2

**Comment by Disonantemus** [comment]
> Cursor now stays in the same place when inserting text in a new file.
> 
> How to recreate:
> 
>     1. open a new file
> 
>     2. press `i` to insert text
> 
>     3. enter some text `hello`
> 
>     4. cursor stays at first position `h`
> 
> 
> This seem to have been introduced in commit: [c22b2c2](https://github.com/martanne/vis/commit/c22b2c2937d9dd65d0609e57f948f08da7f5c5ea)

I'm still experiencing the same, last git:
~~~
> vis -v
vis v0.7-74-gc9737a7 +curses +lua +acl
~~~

Box:
~~~
OS: Arch Linux x86_64
Host: MS-7816 2.0
Kernel: 6.1.14-1-lts
Terminal: tmux
CPU: Intel i7-4790 (8) @ 3.600GHz
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
Memory: 2897MiB / 15939MiB
~~~

**Comment by mcepl** [comment]
Or you can use my fork at https://git.sr.ht/~mcepl/vis which has it merged in its master branch.

**Comment by Disonantemus** [comment]
> Yes, #1087 hasn't been merged yet. You can apply it locally in the meantime to get back up and running.

I'm no programmer, I just create github account to report issues.
I don't know how to do that. Sometimes I just do: `git clone <asdf>`
but I don't know how to merge with git or understand that.

**Comment by mcepl** [comment]
@Disonantemus you build vis yourself, right? If so then just do `git clone https://git.sr.ht/~mcepl/vis` instead of cloning from this GitHub repo and build the program.

**Comment by Disonantemus** [comment]
> @Disonantemus you build vis yourself, right? If so then just do `git clone https://git.sr.ht/~mcepl/vis` instead of cloning from this GitHub repo and build the program.

Thanks, I'm using your repo now!

**Comment by ninewise** [comment]
#1087 was merged, sorry for the wait. Do reopen should further problems ensue.

**Comment by mcepl** [comment]
Awesome, one commit merged, fourty-two to go!

**Comment by ninewise** [comment]
Matěj Cepl ***@***.***> wrote:
> Awesome, one commit merged, fourty-two to go!

I've mentioned before I maintain vis for fun, mcepl. Please stop trying 
to take every bit of fun out of it with sarcastic comments. Being 
nice in your interactions with other people isn't hard. I value your 
contributions but this is not OK.

**Comment by mcepl** [comment]
> Matěj Cepl ***@***.***> wrote:
> I've mentioned before I maintain vis for fun, mcepl. Please stop trying to take every bit of fun out of it with sarcastic comments. Being nice in your interactions with other people isn't hard. I value your contributions but this is not OK.

Being nice means also not standing in the way of others when they want to help, being nice means stepping out when you are not able to help, being nice means to apologize when you have not been able to click `[Merge]` button for two character change since August last year. Being nice doesn’t mean that you are the only one who is right and everybody else have to accommodate your whims. Being nice means not to preach to others that they should behave better when it is all about your problems.

**Comment by ninewise** [comment]
I'm sorry my lack of time is so frustrating to you, and that it comes to this.

Do you mind me checking on your fork which patches you've merged, as a guide to which I can merge more easily here?

**Comment by mcepl** [comment]
Of course, that’s the whole point of me maintaining the fork … I hoped to be able to authoritatively say which commits are if not well done (I am not that good C programmer and I don’t understand internals of vis enough to be able to say that), then at least which are harmless. `master` branch should be something which could be merged here in my opinion, `devel` is slightly more adventurous (but that’s what I am using). And that’s what makes it so frustrating … I am fairly certain that those forty-two commits to go should be at least benign (if not actually helpful, like e.g., #675 which allows whole list of interesting plugins, e.g., https://gitlab.com/muhq/vis-lspc). So, take whatever you want, those commits are not my copyright anyway.
