### ISSUE TITLE
[question] newline at end of file

### ISSUE THREAD

**Issue by dkwo** [martanne/vis#1088]
what is the recommended way to place a newline at the end of file in vis?
currently i get `\ No newline at end of file` all the time in git

Thanks.

**Comment by mcepl** [comment]
We were just discussing this on the [#vis-editor](irc://libera.chat/#vis-editor) channel and the conclusion was that the safest way would be adding to your `~/.config/vis/visrc.lua` something like this (see [vis API documentation](https://martanne.github.io/vis/doc/index.html) for more information):

```lua
-- adds a newline before each write if there is no newline
vis.events.subscribe(vis.events.FILE_SAVE_PRE, function (file, path)
    if
            file.size==0
            or file.size==1 and file:content(0,1)~="\n"
            or file.size>1 and file:content(file.size-2,file.size)~="\n\n"
    then
            file:delete(file.size,file.size)
            file:insert(file.size,"\n")
    end
    return true
end)
```

Alternative condition would be

```lua
if file:content(file.size-1,file.size)~="\n" then
```

Something like this would help?

**Comment by dkwo** [comment]
Thank you. That produces `visrc.lua:2: attempt to index a nil value (field 'events')`.
I must note that my visrc.lua was previously empty. Is there anything I'm missing, or even a sensible visrc that I could look at?

**Comment by mcepl** [comment]
Start with [the default visrc.lua](https://github.com/martanne/vis/blob/master/lua/visrc.lua).

**Comment by dkwo** [comment]
With
```
$ cat .config/vis/visrc.lua 
-- load standard vis module, providing parts of the Lua API
require('vis')

vis.events.subscribe(vis.events.INIT, function()
-- Your global configuration options
end)

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
	-- luacheck: no unused args
	-- Your per window configuration options e.g.
	-- vis:command('set number')
end)

-- adds a newline before each write if there is no newline
vis.events.subscribe(vis.events.FILE_SAVE_PRE, function (file, path)
	if
		file.size==0
		or file.size==1 and file:content(0,1)~="\n"
		or file.size>1 and file:content(file.size-2,file.size)~="\n\n"
	then
		file:delete(file.size,file.size)
		file:insert(file.size,"\n")
	end
	return true
end)
```
there's an undesired effect that, if a newline is already present, then another line is added at the end of file. Can this be avoided?

**Comment by ninewise** [comment]
Something like this should work? (Using mcepls alternative)

```lua
-- ensure none-empty files have a line ending
vis.events.subscribe(vis.events.FILE_SAVE_PRE, function(file, path)
›   if file.size ~= 0 and file:content(file.size - 1, 1) ~= "\n" then
›   ›   file:insert(file.size, "\n")
›   end
›   return true
end)
```

**Comment by dkwo** [comment]
Thanks, that seems to work as desired.
