### ISSUE TITLE
X/re/q doesn't work

### ISSUE THREAD

**Issue by QiBaobin** [martanne/vis#1090]
Thanks for the great work, it seems that `X/re-files/q` doesn't work.

**Comment by rnpnr** [comment]
It seems to work here. Can you give steps to reproduce?
What I did:
1. vis foo bar foobar
2. :X/foo/q
3. only bar is still open

**Comment by QiBaobin** [comment]
1. vise *.md
2. :X/md/q
3. only the first file are closed
4. :X/md/ i/test works well

**Comment by rnpnr** [comment]
I'm still not able to reproduce. I am however able to reliably produce a segfault by doing:
1. vis {a,b,c,d}.md
2. :X/md/ i/test
3. :X/md/q!
