### ISSUE TITLE
terminal no longer has transparency/opacity

### ISSUE THREAD

**Issue by plasmoduck** [martanne/vis#1103]
My terminal is normally transparent/opaque. When I open vis there is no longer transparency/opacity and it is a solid color background. How to keep the transparency/opacity?

**Comment by rnpnr** [comment]
You will need to use a theme that just passes through the terminal background. Something like erf's [minimal clear theme](https://github.com/erf/vis-minimal-theme/blob/main/minimal-clear.lua) or my [term theme](https://github.com/rnpnr/dotfiles/blob/master/.config/vis/themes/term.lua) should work.

If there is a particular theme you like you can modify it to just not set the background.

**Comment by plasmoduck** [comment]
I just use the default-16 theme cause it's the same as my existing terminal
colors (gruvbox), what do I have to change in default-16?

**Comment by plasmoduck** [comment]
Sorry, dark-16.lua is what I'm using.

**Comment by plasmoduck** [comment]
Thanks for your reply. I tried both the themes you included, unfortunatly they both seem to paint some background color, a blushish grey. Not sure what is happening?

**Comment by esdnm** [comment]
I wish the vis came with themes that takes transparent background into account. Or a mechanism by which without modifying a themes file a transparent background can be obtained

**Comment by rnpnr** [comment]
Patches are welcome!

I find transparency annoying in most cases but I will set it up to test any patches.

**Comment by lobre** [comment]
I also think that an editor such as vis should come with a theme that does not define a solid background and that respects the background defined by the terminal. This is how vis looks like by default in my xfce-terminal.

![image](https://github.com/martanne/vis/assets/3764103/1814b6fe-b996-4092-8ed7-cc48684bb3d8)

It is one of the first things that newcomers see, and it is disruptive. Before even thinking about how vis works, it directly distracts me into trying to find a "sane" theme that looks like ok with my terminal colour palette.

**Comment by ForestOctopus** [comment]
I downloaded Gruvbox color scheme by Pavel Pertsev (https://github.com/morhetz),which has this instruction in line 95:
```
-- To use your terminal's default background (e.g. for transparency), set the value below to 'back:default,fore:'..colors.fg1
```
So I set my line 96 as follow:
```
vis.lexers.STYLE_DEFAULT		= 'back:default,fore:'..colors.fg1
```
this make my suckless st terminal opacity function normaly.
I also find this method applie to default. In my case default-256.lua->zenburn.lua.
change  back to default
```
lexers.STYLE_DEFAULT = 'fore:#d7d7d7,back:default'
```
will work.
:-)

**Comment by SadielEd** [comment]
Hello I am using vis version 0.9 +curses +lua +acl in foot terminal and it respects my theme and transparency by default.
So maybe this issue can be closed.

![vis-screenshot](https://github.com/user-attachments/assets/dfdac7e8-391f-414e-97af-264d3da4cd75)

**Comment by rnpnr** [comment]
From #1040:

> Thanks for the info! I thought it should but didn't really set anything up for testing.
