### ISSUE TITLE
Feature Request: Plugin Integration for Vis as a Note-taking System

### ISSUE THREAD

**Issue by LaithOsama** [martanne/vis#1109]
Greetings!

I want to express my deepest gratitude for the remarkable, exquisite, and flawless software you have created. It has truly enriched my computing experience.

I am currently exploring the possibility of utilizing Vis as a comprehensive note-taking system. Therefore, I would like to inquire if there is a plugin integration available for Vis that would enable me to seamlessly use it for this purpose.

Having functionalities similar to vimwiki and org-mode within Vis would be absolutely fantastic, potentially prompting me to completely transition away from neo/vim. I understand that certain design considerations may come into play, but if feasible, I am willing to dedicate my efforts to learning Lua programming in order to develop a plugin that emulates something similar to vimwiki. I acknowledge that the plugin may initially offer limited functionality and capabilities, but it would serve as a stepping stone towards expanding its potential in the future.

Thank you for your time and consideration. I eagerly anticipate your response.

Best regards,
Laith.

**Comment by erf** [comment]
I'm not aware of anything like that but you see a list of plugins people have developed [here](https://github.com/martanne/vis/wiki/Plugins). 

The LUA api is available [here](https://martanne.github.io/vis/doc/), if you'd want to try to develop something like that. This issue tracker is for core vis development and therefor your request seem a bit out-of-scope.

**Comment by ninewise** [comment]
We don't really have a plugin for this current, indeed. If you're willing to make one, it's definitely welcome on the wiki page.

I'll close this ticket since this is not something to be solved in core, but feel free to ask questions here (or preferably, on IRC) if you're stuck.
