### ISSUE TITLE
Show defaults for Command line prompt settings in README

### ISSUE THREAD

**Issue by erf** [martanne/vis#111]
Show defaults for Command line prompt settings in README.

**Comment by martanne** [comment]
Do you intend to submit a patch for it?

**Comment by erf** [comment]
i can fix it

**Comment by erf** [comment]
Comments / suggestions
- set syntax on ( doesn't work. set syntax 'off' works but differs from 'no'. support both 0,1 on/off yes/no for all? )
- set show somearg 1 ( without '=' )
- set show 0 1 ( to enable/disable all )

I will make pr soon..
