### ISSUE TITLE
Setting default theme

### ISSUE THREAD

**Issue by vannotz** [martanne/vis#1112]
Very simple question, how do I set my default theme? I have this at my visrc.lu

```
require("vis")

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
        vis:command('set theme ashes')
end)
```
But this simply changes the theme when I open vis, I can see the theme changing for a split second. What I want is to set a default theme. 
Thank you in advance.

**Comment by erf** [comment]
Try set it on `vis.events.INIT`

**Comment by vannotz** [comment]
That does seem to work better, thank you.
