### ISSUE TITLE
16 ansi colors names

### ISSUE THREAD

**Issue by lobre** [martanne/vis#1138]
I would like to try to reproduce the theme I have always used in vim, which is [noctu](https://github.com/noahfrederick/vim-noctu), a simple theme for 16-color terminals.

In vim, I can refer to colors by their number.

```
hi Pmenu ctermfg=15 ctermbg=0
```

So I can easily target the 16 first colors. Kakoune also has names for those 16 first colors.

https://github.com/mawww/kakoune/blob/23afed056b14f66b345a4b36dd742848bec91ea2/src/color.cc#L12

In vis, I don't find if this is doable. I can see the 8 first colors are declared [here](https://github.com/martanne/vis/blob/312a16ea59000e63db477d3adfcf8e59ea09f478/lua/vis-std.lua#L23)

But how do I refer to the ones from 8 to 15?

**Comment by rnpnr** [comment]
duplicate of #1083

**Comment by lobre** [comment]
Thank you, if I understand, this means it is not supported yet and we can only the 8 first colors at the moment. No need to keep this issue open then. This can be followed in the linked issue.
