### ISSUE TITLE
.vis folder for undo/backup and last cursor position and .visrc for settings ?

### ISSUE THREAD

**Issue by erf** [martanne/vis#114]
Any plans for a .vis folder for optional undo/backup and last cursor position, and have you considered .visrc for options (down the road..) ?

**Comment by martanne** [comment]
Once there is a proper Lua API in place, sourcing a user provided 'configuration file' would make sense.  

The Persistent undo history was already discussed in #43 I still have no immediate plans to support that.

**Comment by erf** [comment]
Is the Lua API ready for configuration file?

**Comment by martanne** [comment]
I guess you have noticed [visrc.lua](https://github.com/martanne/vis/blob/master/visrc.lua) which gets sourced from these [paths](https://github.com/martanne/vis/tree/master/lexers#vis-integration) (minus the `lexers` directory)? As for the [API](https://github.com/martanne/vis#lua-api-for-in-process-extension) at this stage it is quite rudimentary and not properly documented.

However simple configuration changes should be possible. As an example the following enables line numbers:

    vis.command('set number')

**Comment by erf** [comment]
Great! That worked =)

However, shouldn't it search for visrc.lua in "$XDG_CONFIG_HOME/vis" first ?
