### ISSUE TITLE
Paste error, after installing dwl (dwm wayland fork) and wayland

### ISSUE THREAD

**Issue by Disonantemus** [martanne/vis#1140]
- If I do (Normal mode) `"*p`, I get the following error (no paste from system clipboard):
~~~
Command failed Failed to connect to a Wayland server: No such file or directory Note: WAYLAND_DISPLAY is set to wayland-0 Note: XDG_RUNTIME_DIR is set to /run/user/1000 Please check whether /run/user/1000/wayland-0 socket exists and is accessible.
~~~

- In terminal I did check variables:
~~~
$ echo $DISPLAY
:0
$ echo $WAYLAND_DISPLAY
wayland-0
~~~

- I think is related to `vis-clipboard`, but I don't know how to fix it.
- Workaround: (Normal mode) `:xsel -op` works as expected.

**Comment by mcepl** [comment]
On Sat Sep 30, 2023 at 3:58 PM CEST, Disonantemus wrote:
> ~~~
> Command failed Failed to connect to a Wayland server: No such file or directory Note: WAYLAND_DISPLAY is set to wayland-0 Note: XDG_RUNTIME_DIR is set to /run/user/1000 Please check whether /run/user/1000/wayland-0 socket exists and is accessible.
> ~~~

Please, give us the output of `echo $XDG_SESSION_TYPE`. Do you
have Wayland or Xorg based desktop?

**Comment by Disonantemus** [comment]
Sorry 4 late response, I'm no programmer, and didn't get any notification 4 this.

1. echo output:
~~~
$ echo $XDG_SESSION_TYPE
tty
~~~

2. [clipmenu](https://github.com/cdown/clipmenu) from Arch [Extra](https://archlinux.org/packages/extra/any/clipmenu/) repo.

3. I use **Xorg** everyday (with **dwm** window manager), but I did install and try _Wayland_ 2 weeks ago, maybe **vis** got confused because of that?

> On Sat Sep 30, 2023 at 3:58 PM CEST, Disonantemus wrote: ~~~ Command failed Failed to connect to a Wayland server: No such file or directory Note: WAYLAND_DISPLAY is set to wayland-0 Note: XDG_RUNTIME_DIR is set to /run/user/1000 Please check whether /run/user/1000/wayland-0 socket exists and is accessible. ~~~
> Please, give us the output of `echo $XDG_SESSION_TYPE`. Do you have Wayland or Xorg based desktop? Which clipboard manager you use? (not `xsel`, that’s Xorg-based).

---

OS: Arch Linux x86_64
Host: MS-7816 2.0
Kernel: 6.1.52-1-lts
Shell: fish 3.6.1
Resolution: 1920x1080
WM: dwm
Terminal: tmux
CPU: Intel i7-4790 (8) @ 3.600GHz
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590

**Comment by mcepl** [comment]
> 1. echo output:
> 
> ```
> $ echo $XDG_SESSION_TYPE
> tty
> ```

There’s something wrong there. Is this running in some kind of terminal emulator (xterm, gnome-terminal, foot, st, or something) in a graphical environment? To my knowledge only normal values of this variable are `x11` or `wayland` (depending on the type of the graphical environment).

**Comment by Disonantemus** [comment]
Maybe was:
- Wayland installation.
- An update.
- Needed reboot.

Because right now I get this ("empty" as expected):
~~~
$ echo $WAYLAND_DISPLAY

~~~
And **vis** work as should with `"*p`

---

Sorry 4 time U spend with this, I get that wasn't **vis** fault, just confused, maybe because some of the above.

PD: I still get this (inside Xorg with Kitty terminal, with|without tmux):
~~~
$ echo $XDG_SESSION_TYPE
tty
~~~

But it's working ok and not a problem.

**Comment by mcepl** [comment]
Weird, however, @rnpnr , I think we can close this one.
