### ISSUE TITLE
Search after invalid chars

### ISSUE THREAD

**Issue by jk411** [martanne/vis#1142]
echo 61 61 b6 62 62 0a | xxd -p -r >file
vis file

Search
"/b"
doesn't work,
characters after invalid char 0xb6 can't be found if cursor is before it

Last version of vis
compiled from sources
on Alpine Linux (musl)

**Comment by rnpnr** [comment]
duplicate of #1064

**Comment by mcepl** [comment]
> duplicate of #1064

So, why is this ticket not closed?
