### ISSUE TITLE
`win:style` styles more terminal cells than expected

### ISSUE THREAD

**Issue by fischerling** [martanne/vis#1147]
We noticed in https://github.com/fischerling/vis-lspc/pull/34 that the highlighting seems off around `\t` bytes.

This is reproducible by including something like

```lua
vis.events.subscribe(vis.events.WIN_HIGHLIGHT, function(win)
	win:style_define(43, 'back:red')
	win:style(43, 2, 2)
end)
```

in your `visrc.lua` file and opening a file containing only `\t\tx`.
Instead of highlighting the cell containing `x` (the third byte in the
file) the space after the first `\t` symbol up to and including the x is styled. 

Example Screenshot.
![20231012_19h16m02s_grim](https://github.com/martanne/vis/assets/1218430/e7e176a9-13e4-4789-9514-22274db97263)

**Comment by rnpnr** [comment]
Hi, this patch seems correct. I have it applied locally and will likely apply it to master soon.

**Comment by fischerling** [comment]
> Hi, this patch seems correct. I have it applied locally and will likely apply it to master soon.

What is the most convenient for you? Should I send it to the mailing list or open a PR here on Github?

**Comment by rnpnr** [comment]
> What is the most convenient for you?

Either or is fine. Maybe more people will look at it if its a Github PR but its hard to say.
