### ISSUE TITLE
Request: add variant of filter command that doesn't alter buffer

### ISSUE THREAD

**Issue by TieDyedDevil** [martanne/vis#115]
Add a variant of the filter command that doesn't alter the buffer.

One important application is for copying text to the clipboard. Attempting to use the filter command for this requires a script or pipeline that not only updates the clipboard, but also writes the selected text to stdout. This alters the buffer when in fact no change was intended.

Given an alternative command that doesn't alter the buffer, copying to the clipboard would become as simple as

```
:<new_cmd> xsel -i
```

Having the new command also write (non-empty) output to a temporary buffer would facilitate the use of commands that return information about the selection. For example:

```
:<new_cmd> wc -l
```

or

```
:<new_cmd> grep <something_interesting>
```

The command itself might be an option to the filter (:!) command or a completely separate command (e.g. :|).

**Comment by martanne** [comment]
Yes that is basically what `:w !` (notice the space) should do, right? Then the popular "trick" of writing read only files should also work `:w !sudo tee %` 

However instead of using the editor specific `%` I would like to use a real environment variable, maybe  `$%` if that is possible.

**Comment by martanne** [comment]
The latest commits might cover your needs? The integration could probably be improved further, but at least it serves as a starting point.

This could also be hooked up to the special paste registers to implement #107.

**Comment by martanne** [comment]
I added the `xsel` integration via registers.

Feel free to provide patches and/or reopen the issue if you encounter any issues.
