### ISSUE TITLE
Lua not working?

### ISSUE THREAD

**Issue by Chaqua** [martanne/vis#1158]
Steps:
```
sudo apt-get install lua5.4:i386
./configure --enable-lua
./configure && make && sudo make install
```
Maybe I am just to dumb to understand the documentation, but when I run .`/configure && make && sudo make install `
it is not able to find my lua.

`lua -v `output:
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio

And this is the ouput of `./configure && make && sudo make install`:
checking for liblua >= 5.2 ...
 checking for lua... no
 checking for lua5.4... no
 checking for lua5.3... no
 checking for lua5.2... no
 checking for lua-5.4... no
 checking for lua-5.3... no
 checking for lua-5.2... no
 checking for lua54... no
 checking for lua53... no
 checking for lua52... no

**Comment by mcepl** [comment]
What distro? What is the version of your installed lua54-dev?

**Comment by Chaqua** [comment]
Im using Ubuntu-WSL on Windows in school. And the version is included in the steps, or do you mean something else?

**Comment by mcepl** [comment]
On Fri Dec 22, 2023 at 7:13 PM CET, Thomas Baumeister wrote:
> Im using Ubuntu-WSL on Windows in school. And the version is
> included in the steps, or do you mean something else?

For building application linking to Lua, you need not only lua53
package (see https://packages.ubuntu.com/source/noble/lua5.3 for
the list of generated binary packages), but also liblua5.3-dev.

**Comment by mcepl** [comment]
This probably should be closed.
