### ISSUE TITLE
buffer_grow doubles the requested size

### ISSUE THREAD

**Issue by raylu** [martanne/vis#116]
https://github.com/martanne/vis/blob/563c515068fc63cdabe9ccec9292714c78fae8eb/buffer.c#L18

I'm not sure if you meant to double the size of the buffer (`buf->size`) every time or you do actually want to give double the requested size to reduce `realloc`s, but this seems like either a bug or worthy of a comment.

**Comment by raylu** [comment]
have you considered allocating `max(double the current size of the buffer, requested size)` instead?

**Comment by martanne** [comment]
This might indeed be slightly cleaner. However these buffers are used for relatively small things like macros/registers, hence it shouldn't really matter. Probably the most common case is to grow them by exactly one byte/character i.e. the difference between "double the current size of the buffer" and "double the requested size" will be 2.

**Comment by raylu** [comment]
Especially when adding 1 thing/byte at a time, it's common to [double the size of the entire buffer](https://en.wikipedia.org/wiki/Amortized_analysis#Dynamic_Array).

**Comment by martanne** [comment]
I'm obviously aware of that. What I'm trying to tell you is that the difference between the current code and your suggestion will be 2 bytes in the common case.

**Comment by martanne** [comment]
I decided to change the allocation strategy to your suggestion, hope it is clearer now.
