### ISSUE TITLE
[Feature Request]: exit with status code

### ISSUE THREAD

**Issue by mralusw** [martanne/vis#1165]
### What feature would you like to see?

Is there something like `vim`'s `:cquit` (exit editor with status code), so that at least I might use `vis` as `$GIT_EDITOR` or `$GIT_SEQUENCE_EDITOR`? Exiting with a status code aborts the commit / rebase / whatever operation caused the editor to be invoked.

**Comment by rnpnr** [comment]
Not built in but its easy to add via lua:

```lua
vis:command_register("cq", function() vis:exit(1) end)
```

**Comment by mralusw** [comment]
Ah. I found `qall[!] [code]`. I even managed to map it: `map mode lhs rhs` doesn't seem to accept a space within rhs, but `qall!1` without a space works.

Before that, I tried `vis:command_register("cq!", function() vis:exit(1) end)` but it doesn't seem to work with a bang.

**Comment by rnpnr** [comment]
I suggest you look at the [Lua documentation](https://martanne.github.io/vis/doc/#Vis:command_register) if you want to require the exclamation mark. `!` can not be part of a command name, it specifies the `force` parameter

**Comment by mralusw** [comment]
OK. For reference, to map `<backslash>Q` (like `<Leader>` in vi), add
```
  vis:command( "map normal \\Q :qall!\\ 1" )
```
in the `vis.events.subscribe(vis.events.INIT ... )` part of of visrc.lua. Though I wonder if there's a way to include a visrc.vis from Lua with normal commands (separate issue I guess).
