### ISSUE TITLE
[Feature Request]: command completion

### ISSUE THREAD

**Issue by mralusw** [martanne/vis#1167]
### What feature would you like to see?

Maybe I'm doing something wrong here, but is `:<TAB>` in the command line suppose to invoke filename completion, right from the start? I was about to try and see which settings the `:set` command accepts using `<TAB>`, but I couldn't get that far.

**Comment by ninewise** [comment]
Yes, tab in command mode always triggers filename completion. There's no distinction on previous characters. There's some plugins allowing more complicated completion, though.

See the comment on https://github.com/martanne/vis/issues/1007
