### ISSUE TITLE
[Feature Request]: How would I set an option in insert mode only?

### ISSUE THREAD

**Issue by roguh** [martanne/vis#1174]
### What feature would you like to see?

I would like to implement "smart hybrid line numbers" in vis, as described for vim [here](https://jeffkreeftmeijer.com/vim-number/).

This means I want absolute line numbers `set number` in insert mode, and relative numbers in all other modes `set relativenumber`. I don't see an event for when a mode changes, is there a way to accomplish this with the Lua API?

**Comment by fischerling** [comment]
You could do use a frequent event like `vis.events.HIGHLIGHT`.

Try something like:

```lua
do
  local last_mode = nil
  vis.events.subscribe(vis.events.WIN_HIGHLIGHT, function(win)
    if vis.mode == last_mode then
      return
    end

    last_mode = vis.mode
    if last_mode == vis.modes.INSERT then
      win.options.numbers = true
      win.options.relativenumbers = false
    else
      win.options.numbers = false
      win.options.relativenumbers = true
    end
  end)
end
```

in your `visrc.lua`.

It is not perfect because the number change lags one redraw behind, but maybe it helps.

**Comment by VehementHam** [comment]
Or you could remap all of the bindings that take you to insert mode. You would have them do what they normally do, but also run your command. Then `<Esc>` in insert mode would run the command to turn it off.

**Comment by VehementHam** [comment]
If you take my suggestion, I recommend turning it into a plugin.

**Comment by VehementHam** [comment]
In fact this sounds like a feature I want, so if you give me a few days, I will create a plugin for it.

**Comment by VehementHam** [comment]
Working on it now.

**Comment by roguh** [comment]
Thank you! I unfortunately haven't had time to do this, but I can test out your plug-in when it's ready.

Out of curiosity, what feature were you looking to use this for?

**Comment by roguh** [comment]
I think an event coming from the C source code would be ideal, I might try to add an event for when the mode changes. 

https://github.com/martanne/vis/blob/master/vis-core.h#L226

**Comment by VehementHam** [comment]
https://git.disroot.org/oink/vis-smart-numbers

**Comment by mcepl** [comment]
Obviously, this is not an issue to be tracked here, but a question which belongs more to [the vis email list](https://lists.sr.ht/~martanne/devel). Whichever way, @VehementHam ’s plugin is probably a good solution for your problem anyway.

@rnpnr , this could be probably be closed.

**Comment by roguh** [comment]
Good call, @mcepl. I just closed it and can email next time.

**Comment by VehementHam** [comment]
If you are using my plugin, you should run a `git pull`. I pushed some important changes.

**Comment by VehementHam** [comment]
I would like to mention that there is issues with the Change Operator, because it does not change to insert mode upon press, but instead waits for the next keybind to be pressed, and depending on what it is, changes to instert mode.

Other than that, the plugin works fine. I would love to see a mode changing event be added in the future.
