### ISSUE TITLE
[BUG] Syntax Highlighting Incorrect when TERM value is not set to foot in Foot

### ISSUE THREAD

**Issue by VehementHam** [martanne/vis#1175]
### Problem

When opening vis from ZSH, Bash, Fish, and Elvish, the syntax highlighting is horribly deformed. Here is a screenshot:
![image](https://github.com/martanne/vis/assets/75701545/17261004-f51a-4d49-8aa3-2081fcb8a7f3)

As you can see, the syntax highlighting on the right (ZSH) is wrong. The left is Nushell. Shells that vis functions correctly are include Ash, Ion, and as stated before, Nushell.

### vis version (vis -v)

vis 0.8 +curses +lua +acl

### Terminal name/version

foot version: 1.16.2 +pgo +ime +graphemes -assertions

### $TERM environment variable

xterm

**Edit:** This issue actually occurs when the `TERM` value is set to something other than `foot`.

**Comment by rnpnr** [comment]
Yes this is expected behaviour. When `TERM=xterm` curses assumes that the terminal does not support 256 colours. Foot by default supports it. I'm a little confused as to why you are setting `TERM=xterm` when you are using `foot`. If you must `TERM=xterm-256color` should work fine.
