### ISSUE TITLE
Problem with <C-n> in visual mode

### ISSUE THREAD

**Issue by marchelzo** [martanne/vis#118]
Whenever there is a word containing the selected word between the selected word and its next occurrence, the `<C-n>` feature (new cursor at next occurrence) does not work.

For example, try this in a new buffer: `word new_word word`, and then press `<C-n>` twice at the
beginning of the line. It will fail to highlight the second occurrence of `word`. But if you change `new_word` to say, `new_work`, then it works again.

**Comment by martanne** [comment]
Thanks for the detailed bug report, it should be fixed now.
