### ISSUE TITLE
Can't Change Keymaps

### ISSUE THREAD

**Issue by VehementHam** [martanne/vis#1182]
### Problem

When I try to change keymappings, they become very buggy, and do not do what they are supposed to.

### Steps to reproduce

Try using Vis with the following config that changes keymappings:
```lua
-- ...

vis.events.subscribe(vis.events.INIT, function()
	-- Your global configuration options
end)

vis.events.subscribe(vis.events.WIN_OPEN, function(win) -- luacheck: no unused args
	-- Your per window configuration options e.g.
	vis:command('set theme base16-tomorrow-night')
	vis:command('set number')
	vis:command('set cursorline')
	-- key mappings
	vis:unmap(vis.modes.NORMAL, "d")
	vis:unmap(vis.modes.NORMAL, "h")
	vis:unmap(vis.modes.NORMAL, "t")
	vis:unmap(vis.modes.NORMAL, "n")
	vis:map(vis.modes.NORMAL "d", "<left>")
	vis:map(vis.modes.NORMAL "h", "<down>")
	vis:map(vis.modes.NORMAL "t", "<up>")
	vis:map(vis.modes.NORMAL "n", "<right>")
end)

-- ...
```

### vis version (vis -v)

vis 0.8 +curses +lua +acl

### Terminal name/version

foot version: 1.17.2 +pgo +ime +graphemes -assertions

### $TERM environment variable

xterm-256color

**Comment by rnpnr** [comment]
A couple things: 
* Those bindings don't need a window open so I suggest you put them in the `INIT` event.
* You don't need to unmap first, the originals will just be overwritten.
* The pseudo-keys are case sensitive so it should be `"<Left>"` etc.

**Comment by VehementHam** [comment]
Thanks
