### ISSUE TITLE
html syntax highlight misses on single tags

### ISSUE THREAD

**Issue by jvvv** [martanne/vis#1196]
Single html tags like hr, input, and meta (etc) aren't getting highlighted.
My lua knowledge is pretty sparse, but here's a work-around that is working for me so far:
```
From 69243d5a88623f5e7d08eb79b827ad31aa893ece Mon Sep 17 00:00:00 2001
From: jvvv
Date: Mon, 17 Jun 2024 13:16:17 -0400
Subject: [PATCH] fix syntax highlight for html single tags

---
 lua/lexers/html.lua | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lua/lexers/html.lua b/lua/lexers/html.lua
index 9146b63..a0ce2e7 100644
--- a/lua/lexers/html.lua
+++ b/lua/lexers/html.lua
@@ -16,7 +16,7 @@ lex:add_rule('doctype',
 
 -- Tags.
 local paired_tag = lex:tag(lexer.TAG, lex:word_match(lexer.TAG, true))
-local single_tag = lex:tag(lexer.TAG .. '.single', lex:word_match(lexer.TAG .. '.single', true))
+local single_tag = lex:tag(lexer.TAG, lex:word_match(lexer.TAG .. '.single', true))
 local known_tag = paired_tag + single_tag
 local unknown_tag = lex:tag(lexer.TAG .. '.unknown', (lexer.alnum + '-')^1)
 local tag = lex:tag(lexer.TAG .. '.chars', '<' * P('/')^-1) * (known_tag + unknown_tag) * -P(':')
-- 
2.45.2

```

I'm running vis built from git HEAD  on alpinelinux edge.
I can also report this upstream to scintillua if that is desired.

**Comment by mcepl** [comment]
`vis` is taking its lexers from https://github.com/orbitalquark/scintillua, please, file your issue report there, and we will take it from them (of course, you are more than welcome to initiate another round of synchronization with their code).

@rnpnr , I think, this could be closed.

**Comment by mcepl** [comment]
Otherwise, added as a commit to https://git.cepl.eu/cgit/vis/vis/commit/?id=5629ca0091c2f7b3998e977441cc19cbb79653ce and after testing, I will submit it upstream.

**Comment by jvvv** [comment]
Just submitted: [https://github.com/orbitalquark/scintillua/issues/114](url)

**Comment by rnpnr** [comment]
This can stay open for now. We can bulk pull in the changes once its resolved upstream.

**Comment by jvvv** [comment]
Ok, got some good help from orbitalquark. There are tags that handle this case here but are not in the themes. I will post a PR soon that will solve this issue more correctly, but might first spend some time looking for similar issues with tags in other lexers that are not handled by the themes.

**Comment by rnpnr** [comment]
Oh I see now; those should actually be available to style but are just not included in the default themes. This line:
https://github.com/martanne/vis/blob/a7aac1044856abc4d1f133c6563fc604d7fe6295/lua/vis.lua#L287
 
replaces the `.` in the names with a `_`. If you add something like `lexers.STYLE_TAG_SINGLE = '...'` to your theme it should just work.

I don't have a good way of indicating all possible combinations in the themes besides just adding them and letting people tweak for their own preferences.

**Comment by jvvv** [comment]
I had hoped to prepare a more expansive set of changes. #1197 will have to do for now until I have more time.
