### ISSUE TITLE
Malformed System Clipboard Pasted Text 

### ISSUE THREAD

**Issue by TahaGTRC** [martanne/vis#1199]
### Problem

When pasting text from the system clipboard into vis, the pasted text is malformed (tried xsel and xclip). Specifically, each line of the pasted text is preceded by -unwanted- white spaces:
![2024-08-09_22-01](https://github.com/user-attachments/assets/4e29dfd7-812e-47c3-9946-ae3a01ac702e)

the text is displayed correctly in vim:
![2024-08-09_22-04](https://github.com/user-attachments/assets/451feff6-2765-4e6f-b78b-42f5b852ec36)

### Steps to reproduce

1. Copy text from somewhere
2. paste it into vis: `"+p` (or ctrl + v)

### vis version (vis -v)

vis 0.9 +curses +lua +acl

### Terminal name/version

st 0.9.2

### $TERM environment variable

st-256color

**Comment by acidrums4** [comment]
Maybe you have set autoindent on? You can try enabling/disabling it and seeing what happens with `set ai` or `set ai off`

**Comment by TahaGTRC** [comment]
Setting autoindent to off solved it, thanks!

**Comment by mcepl** [comment]
Do we support [bracketed paste](https://en.wikipedia.org/wiki/Bracketed-paste)?
