### ISSUE TITLE
[Feature Request]: Cython Syntax Support

### ISSUE THREAD

**Issue by jgarte** [martanne/vis#1212]
### What feature would you like to see?

This is a request to upport `mylib.pyx` files and syntax from the lexer.

**Comment by mcepl** [comment]
https://lists.sr.ht/~martanne/devel/patches/55453

For additional improvements in `lua/lexers/python.lua` you should talk with its upstream, where we pull all lexers from, https://github.com/orbitalquark/scintillua.

**Comment by mcepl** [comment]
This could be probably closed.
