### ISSUE TITLE
Up motion ends up on wrong char ?

### ISSUE THREAD

**Issue by erf** [martanne/vis#123]
See [hello.txt](https://www.dropbox.com/s/h0143ci7j95ldaf/hello.txt?dl=0)
If you set the cursor on `w`of  `world` on the middle line, and press `k` (up), the cursor is shifted to the right, in neovim it lands on the `w` one line up. Probably related to tabs and char length calculation.

**Comment by martanne** [comment]
There exist still some problems in this area, but this particular issue should be fixed.

**Comment by erf** [comment]
Awesome. Seems to work fine now.
