### ISSUE TITLE
Add new multi-cursor above or below line of min/max of current cursors

### ISSUE THREAD

**Issue by erf** [martanne/vis#124]
If i create a new cursor with `CTRL-j`, and then with `CTRL-k`, it creates the new cursor on the same position as the first cursor. I'm thinking a better behavior would be to add the new cursor above the line of the top cursor for `CTRL-k`and below the bottom cursor with `CTRL-j`.

**Comment by erf** [comment]
So you are basically growing/adding cursors above or below. It could also be an idea, to shrink cursors with `CTRL-ALT-k` `CTRL-ALT-j` .

**Comment by martanne** [comment]
This is covered by #93
