### ISSUE TITLE
CTRL-n in insert mode to autocomplete word in buffer

### ISSUE THREAD

**Issue by erf** [martanne/vis#128]
Feature request:
CTRL-n in insert mode to autocomplete word in buffer - like in vim.

**Comment by erf** [comment]
and CTRL-n to toggle between possible words.

**Comment by twe4ked** [comment]
It would be cool to write tests for these feature requests now we have a system in place. Would that be helpful Marc?

**Comment by martanne** [comment]
At this time tests for basic (hopefully working) editor functionality would be more helpful, see #166 for details.

**Comment by erf** [comment]
You are probably aware of this, but i though i mention it as a reference for possible menu when you want to show multiple word completions.
http://www.tldp.org/HOWTO/NCURSES-Programming-HOWTO/menus.html

**Comment by erf** [comment]
For those interested, i've implemented a naive approach to autocomplete word in PR #277
