### ISSUE TITLE
Autoindent inside bracket behaviour

### ISSUE THREAD

**Issue by erf** [martanne/vis#140]
If autoindent is enabled, shouldn't a tab be inserted if a newline is added to the start of a bracket with `o`?
```
function test(){
    //new line starts here
}
```

**Comment by martanne** [comment]
Maybe, see #33 for outdated code which did this and past discussion why this should probably not be part of the editor core.

Extending the Lua API to cover this use case would be an interesting exercise if only to test the general concept ...

**Comment by erf** [comment]
It's a simpler fix than the PR mentioned, but maybe there are other features that should be included as well.. so maybe best avoid adding it to core..

Agreed!

**Comment by martanne** [comment]
The built in auto indentation is deliberately language agnostic (and hence primitive). Language specific indentation rules should be implemented via the Lua API which as mentioned above might require some extensions.

As I do not really use auto indentation, I currently do not have a real incentive to work on it. Feel free to send patches.
