### ISSUE TITLE
`d)` deletes whole paragraph, not just sentence

### ISSUE THREAD

**Issue by erf** [martanne/vis#141]
`d)` deletes whole paragraph, not just sentence

**Comment by martanne** [comment]
Please provide a concrete example. What is your file content before? Where is the cursor? What do you type? `d)`? What do you expect as result? What actually happens?

The relevant function is [text_paragraph_sentence_next](https://github.com/martanne/vis/blob/df0dbaa1310acceed3b73c6f74be84eceea1aace/text-motions.c#L359) there are plenty of example usages of the iterator API in that file. Maybe you can try to fix it yourself?

**Comment by erf** [comment]
Given an text document as follows.
```
This is an sentence. This is another sentence.
```
Place cursor on start of line and press `d)` and whole line will be deleted, not just the first line.

I can have a look when i have time.

**Comment by martanne** [comment]
Mentioning that the motion on its own seems to work fine, would also have been helpful ;-)

Anyway these motion should probably be improved/rewritten at some point. But I hardly ever use them so it is fairly low priority.

**Comment by erf** [comment]
Ah yes, forgot to mention that ;)
Yes, i don't use them much either, only when writing some none-code stuff.

**Comment by erf** [comment]
But you fixed it! Great =)
