### ISSUE TITLE
Word wrap and line breaks

### ISSUE THREAD

**Issue by erf** [martanne/vis#142]
Option to wrap word and only line break on enter.

http://vim.wikia.com/wiki/Word_wrap_without_line_breaks

**Comment by martanne** [comment]
Again simply posting a link (describing various different options)  is not that useful. What exact behavior would you like and why?

Personally I do not want that the editor interferes with line wrapping at all. If I want to wrap my text (for example for mails which should not exceed 75 columns) I use an external tool such as `fmt(1)` which is hooked up to the `=` operator. A specialized tool can also take advantage of the hyphenation rules of your language etc.

**Comment by erf** [comment]
Allowing word wrapping makes it easier to read text documents. I would prefer not to figure out how to use an external tool for this, since i'm not a linux super geek.. also this seems to be a feature in most text editors.

Alternatively an option to not break lines, if you don't want to show all text on long lines of text for some reason. (Small terminal window?)

**Comment by martanne** [comment]
Two solutions:

1. Break your lines at reasonable widths
2. Enlarge your terminal window

 `:set nowrap` is difficult to (efficiently) implement given the core data structures underlying vis.
