### ISSUE TITLE
Segmentation fail

### ISSUE THREAD

**Issue by erf** [martanne/vis#143]
After editing a file (for a while) i pressed `:x` which caused an `segmentation fail` message. And the file only had one line now.. Hmm..

**Comment by martanne** [comment]
You really have to learn how to create useful bug reports. This is not enough information to do anything! Compile with `make debug` and provide a gdb backtrace (Google is your friend)? Detailed steps how to reproduce would also be useful ...

**Comment by erf** [comment]
I don't really know how to reproduce that error since i was working on a text doc for a while before exiting.. just thought i mention it..

**Comment by martanne** [comment]
Make sure you are compiling with `make debug` then instruct your system to generate core dumps when an application crashes. In Linux/bash this would be done with `ulimit -c unlimited`. No clue about Mac OS X. Then submit/analyze the generated core file.

**Comment by erf** [comment]
Ok, will look into that. I only experienced the crash once. `ulimit` is part of OSX.
