### ISSUE TITLE
Tab alignment

### ISSUE THREAD

**Issue by erf** [martanne/vis#144]
Tabbed text doesn't seem to align up.
```
hello    tabend
yo        tabend
```

**Comment by martanne** [comment]
I guess your talking about tab expansion i.e. the option `:set et` is on? Again I should not have to guess this, please provide more information when writing bug reports!

And yes the behavior is totally broken, see [expand_tab](https://github.com/martanne/vis/blob/df0dbaa1310acceed3b73c6f74be84eceea1aace/vis.c#L49) can you fix it? Hint: it currently does not take the cursor position into account, but always inserts a fixed number of spaces...

**Comment by erf** [comment]
Sorry for the lack of information, i will try to provide more information next time.
I have the following settings enabled
```
    vis.command('set tabwidth 4')
    vis.command('set expandtab')
    vis.command('set autoindent')
```
I then write `hello` press tab and write `tabend`, i then press `Enter` write `yo`and press `tab`two times, when i now write `tabend`it is not aligned with `tabend`on the first line.

That should be possible to fix..
