### ISSUE TITLE
Yank line doesn't work

### ISSUE THREAD

**Issue by erf** [martanne/vis#148]
I write
```
hello world <Enter>
```
I then go to normal mode and move cursor to start with `<ESC> k`.
I then yank and paste the line with `yy p`, but nothing happens.

It seems to happen only when i try to yank a line where the next line only has a `newline` char.
If i move the cursor one line down with `j`, below the text, then it works fine to paste `p`.

**Comment by TieDyedDevil** [comment]
Is this a display issue, or a typo in your report?

<ESC> u undoes your insert, leaving nothing to yank.

On Fri, Jan 15, 2016 at 4:18 AM, Erlend <notifications@github.com> wrote:

> I write
>
> hello world <Enter>
>
> I then go to normal mode and move cursor to start with <ESC> u
> I then yank and paste the line with yy p, but nothing happens
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/martanne/vis/issues/148>.
>



-- 
"I think as musicians, we have more vision than we credit ourselves for. We
should dive into it without reserve, and take the sort of risks it takes to
be divisive and impactful. Things have yet to be done."
   Aaron Fowler Clark

"Do not seek to follow in the footsteps of the masters. Seek what they
sought."
   Matsuo Basho

http://soundcloud.com/davidlamkins
http://reverbnation.com/lamkins
http://reverbnation.com/lcw
http://lamkins-guitar.com/
http://lamkins.net/
http://successful-lisp.com/

**Comment by erf** [comment]
I typed `u` first by mistake in the rapport - i have changed it to `k`. Could you try to recreate / confirm it?

**Comment by TieDyedDevil** [comment]
Yes, I see the behavior you reported.

$ vis
iHello world<Enter><esc>kyyp

results in this on the screen:
Hello world

~
~
...

when I expected to see:
Hello world
Hello world

~
~
...



Even stranger:

$ vis
iHello world<Enter>Goodnight moon<Enter><esc>kyyp

displays:
Goodnight moon
Goodnight moon

~
~
...

when I expected to see:
Hello world
Goodnight moon

~
~
...


On Fri, Jan 15, 2016 at 11:02 AM, Erlend <notifications@github.com> wrote:

> I typed u first by mistake in the rapport - i have changed it to k. Could
> you try to recreate / confirm it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/martanne/vis/issues/148#issuecomment-172054630>.
>



-- 
"I think as musicians, we have more vision than we credit ourselves for. We
should dive into it without reserve, and take the sort of risks it takes to
be divisive and impactful. Things have yet to be done."
   Aaron Fowler Clark

"Do not seek to follow in the footsteps of the masters. Seek what they
sought."
   Matsuo Basho

http://soundcloud.com/davidlamkins
http://reverbnation.com/lamkins
http://reverbnation.com/lcw
http://lamkins-guitar.com/
http://lamkins.net/
http://successful-lisp.com/

**Comment by TieDyedDevil** [comment]
I'm sorry. The final "expected" display in my previous message should have
been:
Hello world
Goodnight moon
Goodnight moon

~
~
...

On Fri, Jan 15, 2016 at 11:13 AM, David Lamkins <david@lamkins.net> wrote:

> Yes, I see the behavior you reported.
>
> $ vis
> iHello world<Enter><esc>kyyp
>
> results in this on the screen:
> Hello world
>
> ~
> ~
> ...
>
> when I expected to see:
> Hello world
> Hello world
>
> ~
> ~
> ...
>
>
>
> Even stranger:
>
> $ vis
> iHello world<Enter>Goodnight moon<Enter><esc>kyyp
>
> displays:
> Goodnight moon
> Goodnight moon
>
> ~
> ~
> ...
>
> when I expected to see:
> Hello world
> Goodnight moon
>
> ~
> ~
> ...
>
>
> On Fri, Jan 15, 2016 at 11:02 AM, Erlend <notifications@github.com> wrote:
>
>> I typed u first by mistake in the rapport - i have changed it to k.
>> Could you try to recreate / confirm it?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/martanne/vis/issues/148#issuecomment-172054630>.
>>
>
>
>
> --
> "I think as musicians, we have more vision than we credit ourselves for.
> We should dive into it without reserve, and take the sort of risks it takes
> to be divisive and impactful. Things have yet to be done."
>    Aaron Fowler Clark
>
> "Do not seek to follow in the footsteps of the masters. Seek what they
> sought."
>    Matsuo Basho
>
> http://soundcloud.com/davidlamkins
> http://reverbnation.com/lamkins
> http://reverbnation.com/lcw
> http://lamkins-guitar.com/
> http://lamkins.net/
> http://successful-lisp.com/
>



-- 
"I think as musicians, we have more vision than we credit ourselves for. We
should dive into it without reserve, and take the sort of risks it takes to
be divisive and impactful. Things have yet to be done."
   Aaron Fowler Clark

"Do not seek to follow in the footsteps of the masters. Seek what they
sought."
   Matsuo Basho

http://soundcloud.com/davidlamkins
http://reverbnation.com/lamkins
http://reverbnation.com/lcw
http://lamkins-guitar.com/
http://lamkins.net/
http://successful-lisp.com/

**Comment by martanne** [comment]
This is a display issue. Scroll up and you will see your expected content.

The problem is likely in `view_cursors_to`. Assume the current view port
before the put operation displays the range `[0, x]` then after the put
the cursor is moved to `x`. This triggers a [`view_viewport_down(view, 1)`]
(https://github.com/martanne/vis/blob/master/view.c#L1149).

The idea behind this was to fix the following behaviour at the end of the
view port. Try placing the cursor on the last line being displayed then
create a new line by pressing `<Enter>` and watch how the cursor is misplaced.

See also cff6ed5b6986cc22fe78288a9c7486026578ab47. Patches welcome ...
