### ISSUE TITLE
Center content option (feature request)

### ISSUE THREAD

**Issue by erf** [martanne/vis#151]
Would love an option `set center`to center/indent content, like in `distraction-free-mode`in some other editors. Then i could go fullscreen without twisting my neck too much.

**Comment by martanne** [comment]
vis doesn't have much "editor chrome" to hide. I would advice you to instruct your windowing system to display the terminal in a distraction free way ...

**Comment by greduan** [comment]
He probably means something like adding padding to the sides. So the editor knows not to draw in the 10 chars of each edge (for example), although from what I understand that would make it way slower to render?

**Comment by erf** [comment]
Padding is what i meant yes.

**Comment by twe4ked** [comment]
To reiterate what maryanne said, you could add padding using a windowing system. You could use tmux for instance and create three splits with vis in the centre column.
