### ISSUE TITLE
Star (*) does not match word

### ISSUE THREAD

**Issue by erf** [martanne/vis#152]
Star `*` does not match word. If you press `*` on top of word, it does not mark and move to similar word.

**Comment by erf** [comment]
The bug was introduced in commit 495cc3d

**Comment by TieDyedDevil** [comment]
It works for me, at least insofar as moving to the next word.

To the best of my knowledge, vis has never visually highlighted the word.


On Sun, Jan 24, 2016 at 04:04:06PM -0800, Erlend wrote:
>    Star * does not match word If you press * on top of word, it does not
>    mark and move to similar word
> 
>    —
>    Reply to this email directly or [1]view it on GitHub.
> 
> References
> 
>    1. https://github.com/martanne/vis/issues/152

-- 
"I think as musicians, we have more vision than we credit ourselves for. We should dive into it without reserve, and take the sort of risks it takes to be divisive and impactful. Things have yet to be done."
   Aaron Fowler Clark

"Do not seek to follow in the footsteps of the masters. Seek what they sought."
   Matsuo Basho

**Comment by TieDyedDevil** [comment]
Sorry that I responded before you added this information...

I had updated to b9e8d20 (which I believe is current as I write this) to check the behavior on my machine.


On Sun, Jan 24, 2016 at 04:06:32PM -0800, Erlend wrote:
>    The bug was introduced in commit [1]495cc3d
> 
>    —
>    Reply to this email directly or [2]view it on GitHub.
> 
> References
> 
>    1. https://github.com/martanne/vis/commit/495cc3d53cdb7182c98827f8aa0ad2726167daaf
>    2. https://github.com/martanne/vis/issues/152#issuecomment-174355100

-- 
"I think as musicians, we have more vision than we credit ourselves for. We should dive into it without reserve, and take the sort of risks it takes to be divisive and impactful. Things have yet to be done."
   Aaron Fowler Clark

"Do not seek to follow in the footsteps of the masters. Seek what they sought."
   Matsuo Basho

**Comment by erf** [comment]
I'm on OSX. Moving to the next word only works before 495cc3d . You are right about words not highlighting..

**Comment by martanne** [comment]
Yes the used regex features are probably not POSIX compilant. I only tested it with musl/glibc. I guess it doesn't work with *BSD either?

What happens when you search for a word via `/\<word\>`  (on the / prompt)?

**Comment by erf** [comment]
Searching for words with `/\<word\>` works fine.

**Comment by martanne** [comment]
Then `*` and `#` should also work as it uses the same mechanism. 

Closing, not enough information!

**Comment by erf** [comment]
Sorry i misunderstood, `/\<word\>` does NOT work, only `\word`. 
If i do a `printf(string)` like
```
int text_regex_compile(Regex *regex, const char *string, int cflags) {
    printf(string); 
```
It prints out `\<word\>`

**Comment by erf** [comment]
.. when pressing `*` over `word`

**Comment by erf** [comment]
i think `\(word\)`should work

**Comment by erf** [comment]
I think `\(word\)` should work

**Comment by martanne** [comment]
> I think `\(word\)` should work

What makes you believe that? It doesn't make much sense to me? Can you link to a document describing the function of `\(` and `\)`? The `\<` and `\>`  we are currently using are non-POSIX [assertions matching the beginning and end of a word](http://laurikari.net/tre/documentation/regex-syntax/#assertion) respectively.

Also I'm not sure you understand the issue the original patch solves (at least on musl/glibc based systems). Given the following document content:

```
foo-foobar-barfoo-foo
```

When the cursor is on the first `f` of the line pressing either `*` or `#` should move the cursor to the last `f` of the line.

**Comment by erf** [comment]
I was reading `Introducing Regular Expression` and i made a test program with `regex.h`to match a word, which worked, i also implemented it in vis, but i was not able to match the example you describe with `foo-foobar-barfoo-foo` - will to look more into this.

**Comment by c00kiemon5ter** [comment]
`\(word\)` on BRE creates a saved state which can be used either in the
same regex or some action (backtracking).
On ERE this works without escaping the parenthesis.

Actually, this is not part of BRE. It is just usually available on BRE mode
on systems that also support ERE.

..so.. `\(foo\).\1` would match any string that contains `foo` followed by
any character and then `foo` again.
The second `foo` comes out of the first saved state (`\1`) match
(`\(foo\)`).

If you're familiar with sed, it is very common to see this pattern, ie

```
$ echo "foo+bar" | sed 's/\(.*\)+\(.*\)/\2-\1/'
bar-foo
```

here, we match anything before the last occurring `+` and anything after it
we use `\(` and `\)` to save the matches
and substitute the result the otherway around with a `-` in place of `+`

all in all, this is totally unrelated to what `\<` and `\>` does

---

`\<` and `\>` implement word boundaries, the way lookahead and lookbehind
does.
it is common to also see them as `\b` which doesn't differentiate the
"direction" of the word

Word boundaries are not implemented in POSIX regex, so there is no actual
portable way to
use them - at least that I know of. Best way would be to use a library that
you know that it does
implement those and that they'll always be there.

Hope this helps - sorry for the long message.


On 31 January 2016 at 11:37, Marc André Tanner <notifications@github.com>
wrote:

> I think \(word\) should work
>
> What makes you believe that? It doesn't make much sense to me? Can you
> link to a document describing the function of \( and \)? The \< and \> we
> are currently using are non-POSIX assertions matching the beginning and
> end of a word
> <http://laurikari.net/tre/documentation/regex-syntax/#assertion>
> respectively.
>
> Also I'm not sure you understand the issue the original patch solves (at
> least on musl/glibc based systems). Given the following document content:
>
> foo-foobar-barfoo-foo
>
> When the cursor is on the first f of the line pressing either * or #
> should move the cursor to the last f of the line.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/martanne/vis/issues/152#issuecomment-177447977>.
>



-- 
*Ivan c00kiemon5ter Kanakarakis*  >:3

**Comment by c00kiemon5ter** [comment]
`\(word\)` on BRE creates a saved state which can be used either in the
same regex or some action (backtracking).

On ERE this works without escaping the parenthesis.

Actually, this is not part of BRE. It is just usually available on BRE mode
on systems that also support ERE.

..so.. `\(foo\).\1` would match any string that contains `foo` followed by
any character and then `foo` again.
The second `foo` comes out of the first saved state (`\1`) match
(`\(foo\)`).

If you're familiar with sed, it is very common to see this pattern, ie

```
$ echo "foo+bar" | sed 's/\(.*\)+\(.*\)/\2-\1/'
bar-foo
```

here, we match anything before the last occurring `+` and anything after it
we use `\(` and `\)` to save the matches
and substitute the result the otherway around with a `-` in place of `+`

all in all, this is totally unrelated to what `\<` and `\>` does

`\<` and `\>` implement word boundaries, the way lookahead and lookbehind
does.
it is common to also see them as `\b` which doesn't differentiate the
"direction" of the word

Word boundaries are not implemented in POSIX regex, so there is no actual
portable way to
use them - at least that I know of. Best way would be to use a library that
you know that it does
implement those and that they'll always be there.

Hope this helps - sorry for the long message.

**Comment by erf** [comment]
I believe word boundaries are solved in POSIX using `[[:<:]]word[[:>:]]`
See pull request #159 
 http://www.regular-expressions.info/wordboundaries.html
