### ISSUE TITLE
Error in mainloop: Function not implemented

### ISSUE THREAD

**Issue by jazzoo2** [martanne/vis#153]
After clone-ing the latest from master. 
Built per README.md

Running :
VIS_PATH=. ./vis config.h                                                                                                                  
Error in mainloop: Function not implemented

Please advise on futher debugging assistance if I may be of help.

**Comment by martanne** [comment]
What kind of system (libc/kernel) is this? For example what is the output of `uname -a`? If you are on linux then the output of `strace -o log ./vis && cat log` would be helpful.

For some reason [`pselect(2)`](https://github.com/martanne/vis/blob/master/vis.c#L850) seems to return `ENOSYS`.

**Comment by jazzoo2** [comment]
Have updated system while waiting for response. Not sure what combination of the many changes I've made.

Problem resolved.

PPS : vis ROCKS! Thanks for all your work!
