### ISSUE TITLE
Cannot turn off syntax highlighting

### ISSUE THREAD

**Issue by rich-coe** [martanne/vis#155]
In vim you can turn off syntax highlighting with ':syntax off'.
This is useful if you don't like the syntax highlighting.

Work-around:  
create empty file /usr/local/share/vis/lexers/theme/none.lua 
set environment variable VIS_THEME=none

**Comment by xomachine** [comment]
I think ':set syntax off' command can be used in this case.

**Comment by rich-coe** [comment]
That worked!  Thanks.
