### ISSUE TITLE
Using substitute command makes cursor jump to top-line

### ISSUE THREAD

**Issue by rich-coe** [martanne/vis#158]
Issue substitute command  :s/and/but/  with a line that contains the word or letters 'and'
cursor jumps to first line of the file and the screen is redrawn
type 'u' to undo
cursor jump to last line of the file and the screen is redrawn

Expected behaviour
The text is replaced on the current line.
The cursor remains on the current line.
Undo reverts the text back to the previous text.
The cursor remains on the current line.

**Comment by martanne** [comment]
Thanks, it should be better now. Cursor positioning after an undo might not yet be to your liking ...
