### ISSUE TITLE
Substitute single line fails on OSX

### ISSUE THREAD

**Issue by erf** [martanne/vis#160]
If i write
```
ihello world<Esc>:s/hello/test<Enter>
```
i expect `hello` to become `test`, but nothing happens and i get the error message:
```
Command failed: sed: 1: "s/hello/test": unterminated substitute in regular expression
```
If i add `/g` it works, but on all lines - in vim this only changes all occurrences on the current line. 

The same happens when in visual mode.

**Comment by martanne** [comment]
Add a trailing slash

    ihello world<Esc>:s/hello/test/<Enter>

**Comment by erf** [comment]
:+1:

**Comment by erf** [comment]
Seems to be another issue here:

**Comment by erf** [comment]
Seems to be another issue here, given:
```
hello world
hello world hello hello
hello world
```
I put the cursor on the first `hello` and write `:s/hello/test/`all the first `hello` on all lines are substituted, so i end up with:
```
test world
test world hello hello
test world
```

**Comment by greduan** [comment]
Just giving some thoughts, nothing concrete. If vis is using `sed` to do the replace then this is expected behaviour, as sed goes through the whole file, line by line.
