### ISSUE TITLE
Layout independent keybindings

### ISSUE THREAD

**Issue by xomachine** [martanne/vis#161]
There is a problem for all non-latin keyboard layout users. Current keybindings work only with latin letters. Every attempt to edit any non-latin text via vis makes user to perform a lot of layout switching instead of actually editing. It would be great if vis's keybindings will be independent from the current layout.

As temporary workaround the bash script below can be used to modify config.h and make it friendly to any non-latin layout (for layouts other than russian the "nonlatin" variable should be filled by analogues of symbols from "latin" variable, and " symbols should be escaped). 
Script usage:

- copy the script body to the new file [scriptname].sh in the "vis" source root folder
- type following command before compilation

``` bash
$ sh [scriptname].sh < config.def.h > config.h
```
[Script body](http://pastebin.com/EjGbQEjL)

**Comment by martanne** [comment]
I guess in vim you use the `:set langmap` feature? Which remaps keys if not in insert/replace mode, correct?

In vis this could be achieved by translating the keys in the [getkey](https://github.com/martanne/vis/blob/66a56c827efcac36e07d6ac34bd05681ab8364e9/vis.c#L747) function.

Something like

```C
if (!vis->mode->input) {
      const char *mapped = map_get(vis->langmap, key);
      if (mapped)
            return mapped;
}
```

Where `vis->langmap` would be a [map](https://github.com/martanne/vis/blob/master/map.h#L9) populated with your translation table.

**Comment by xomachine** [comment]
Actually I don't use vim.(It has lack of minimalism, that is the reason why I use vis)  But I've heard about this feature. Using the `:set langmap` does not allow to remap punctuation signs used in command syntax. For example in russian layout  ";" key should be mapped as "ж" letter. Another way to fix shortcuts in vim is using `:set keymap` command, but I have no idea how it works.

The best solution, in my opinion, would be handling keycodes instead of letters in all modes other than insert/replace and command line. As far as I know it is hard to achieve due to absence of necessary functionality in libtermkey.

**Comment by martanne** [comment]
> Actually I don't use vim.(It has lack of minimalism, that is the reason why I use vis) 

Good attitude, wondering when vis will become too bloated ;-)

Unless I'm missing something working with letters should work fine. What is wrong with the patch below? Add all your desired mappings to config.def.h.

```diff
diff --git a/config.def.h b/config.def.h
index 368e80c..4946ba2 100644
--- a/config.def.h
+++ b/config.def.h
@@ -3,6 +3,11 @@
 #define ALIAS(name) .alias = name,
 #define ACTION(id) .action = &vis_action[VIS_ACTION_##id],
 
+static const char *keymaps[] = {
+	"ж", ";",
+	NULL
+};
+
 static const KeyBinding bindings_basic[] = {
 	{ "<C-z>",              ACTION(EDITOR_SUSPEND)                      },
 	{ "<Left>",             ACTION(CURSOR_CHAR_PREV)                    },
diff --git a/main.c b/main.c
index 6b746ef..7c98ae8 100644
--- a/main.c
+++ b/main.c
@@ -1824,6 +1824,9 @@ int main(int argc, char *argv[]) {
 		}
 	}
 
+	for (const char **k = keymaps; k[0]; k += 2)
+		vis_keymap_add(vis, k[0], k[1]);
+
 	/* install signal handlers etc. */
 	struct sigaction sa;
 	memset(&sa, 0, sizeof sa);
diff --git a/vis-core.h b/vis-core.h
index dab22a0..a201828 100644
--- a/vis-core.h
+++ b/vis-core.h
@@ -150,6 +150,7 @@ struct Vis {
 	bool autoindent;                     /* whether indentation should be copied from previous line on newline */
 	Map *cmds;                           /* ":"-commands, used for unique prefix queries */
 	Map *options;                        /* ":set"-options */
+	Map *keymap;                         /* key translation before any bindings are matched */
 	Buffer input_queue;                  /* holds pending input keys */
 	Buffer *keys;                        /* currently active keys buffer (either the input_queue or a macro) */
 	Action action;                       /* current action which is in progress */
diff --git a/vis.c b/vis.c
index 848180f..35516de 100644
--- a/vis.c
+++ b/vis.c
@@ -341,6 +341,8 @@ Vis *vis_new(Ui *ui, VisEvent *event) {
 		goto err;
 	if (!(vis->search_file = file_new_internal(vis, NULL)))
 		goto err;
+	if (!(vis->keymap = map_new()))
+		goto err;
 	vis->mode_prev = vis->mode = &vis_modes[VIS_MODE_NORMAL];
 	vis->event = event;
 	if (event && event->vis_start)
@@ -371,6 +373,7 @@ void vis_free(Vis *vis) {
 	map_free(vis->cmds);
 	map_free(vis->options);
 	map_free(vis->actions);
+	map_free(vis->keymap);
 	buffer_release(&vis->input_queue);
 	for (int i = 0; i < VIS_MODE_INVALID; i++)
 		map_free(vis_modes[i].bindings);
@@ -422,6 +425,10 @@ bool vis_action_register(Vis *vis, const KeyAction *action) {
 	return map_put(vis->actions, action->name, action);
 }
 
+bool vis_keymap_add(Vis *vis, const char *key, const char *mapping) {
+	return map_put(vis->keymap, key, mapping);
+}
+
 static void window_jumplist_add(Win *win, size_t pos) {
 	Mark mark = text_mark_set(win->file->text, pos);
 	if (mark && win->jumplist)
@@ -763,6 +770,11 @@ static const char *getkey(Vis *vis) {
 	if (!key)
 		return NULL;
 	vis_info_hide(vis);
+	if (!vis->mode->input) {
+		const char *mapped = map_get(vis->keymap, key);
+		if (mapped)
+			return mapped;
+	}
 	return key;
 }
 
diff --git a/vis.h b/vis.h
index 6652f72..81a8890 100644
--- a/vis.h
+++ b/vis.h
@@ -138,6 +138,9 @@ const char *vis_mode_status(Vis*);
 /* associates the special pseudo key <keyaction->name> with the given key action.
  * after successfull registration the pseudo key can be used key binding aliases */
 bool vis_action_register(Vis*, const KeyAction*);
+/* add a key mapping which is applied for all modes except insert/replace
+ * before any key bindings are evaluated */
+bool vis_keymap_add(Vis*, const char *key, const char *mapping);
 
 enum VisOperator {
 	VIS_OP_DELETE,
```

**Comment by xomachine** [comment]
There is nothing wrong in case of addition `:set langmap`-like command in future. Otherwise I don't see any reason of adding (and checking) new bindings at runtime instead of compiletime. The script from first message can do it as well once before compilation.
It is much easier for user to type something like `qwertyuio... йцукенгш...` instead of manual editing config.def.h
Unfortunately, the syntax of classical `:set langmap` command not suitable due to reasons I've mentioned above. Alternative syntax can involve space character as separator (Hopefully, it has the same position in all layouts).
PS: I wonder if some variation of `:map` command (with reusing of [cmd_map](https://github.com/martanne/vis/blob/master/vis-cmds.c#L1033)'s code) might be used for such keymapping. Perhaps, it could allow to avoid creating unnecessary entities.
