### ISSUE TITLE
View moves down after paste word at end of buffer

### ISSUE THREAD

**Issue by erf** [martanne/vis#164]
When i paste some text at the last line, the view is moved down, so i only see the last thing i pasted. 
Example:
`ihello<Enter><Esc>kyyppppywjp`

**Comment by erf** [comment]
Thanks for the fix, but this could be improved further by moving the view to the bottom and not stopping at half height ( if you paste the same thing several times, it suddently appear as if its not pasting anymore halfway down ).

**Comment by martanne** [comment]
Won't happen, at least not by myself.
