### ISSUE TITLE
Wishlist for future Vis api/architecture features

### ISSUE THREAD

**Issue by erf** [martanne/vis#165]
These are not feature requests for Vis core, but i hope Vis will support the necessary api/architecture to enable plugins to support the following features some time in the future. 
1. **JSHint support** - plugins will need to be able to listen for buffer changes, run a process asynchronously and then manipulate the line color / gutter / text message.
2. **Persistent undo** - plugin can listen for undo / redo changes and save them to disk. Also load them at initialization.
3. **Key mappings** - key mappings in `visrc` also support for repeating characters like `jj` to `<Esc>`. A plugin could listen for key changes and override the default key mappings.

**Comment by martanne** [comment]
2) can not really be implemented as a plugin as it touches the core data structure of vis. Use your favorite version control software if you need persistent undo!
3) as previously mentioned in #48 I would like to avoid these kind of things. I consider it a good thing that the input code is independent of typing speed. This would complicate matters, for example when replaying a macro it would be necessary to distinguish whether `jj` was meant as Escape or not.

**Comment by erf** [comment]
I understand. Should i close this issue or leave it open for reference or if others want to include some 'wishes'?
