### ISSUE TITLE
have `vis somefolder` start up with file explorer ( like with `:edit .`)

### ISSUE THREAD

**Issue by erf** [martanne/vis#170]
When you try to open a folder with Vis, instead of writing an error, open the "file explorer" like when you press `:edit somefolder`.

**Comment by martanne** [comment]
I would like to keep the current behavior for now. One reason being that `:e .` might not work on all systems, because `slmenu` is missing.

You could always start vis (for example by means of a shell wrapper) as:
```
$ vis "+e directory"
```
if a directory is provided or simply run `:e .` within vis itself.
