### ISSUE TITLE
Inc / dec number moves cursor to start of word

### ISSUE THREAD

**Issue by erf** [martanne/vis#177]
Inc / dec number with `<Ctrl>a`, `<Ctrl>x` moves cursor to start of word - this differs from **vim** which moves the cursor to the end of word. Also in vim, you can type `<Ctrl>a` or `<Ctrl>x` on the line before the number.

**Comment by martanne** [comment]
Does it really matter?

This will not be changed (or at least I won't do it), the current state is good enough and it could be argued that these commands should not have been implemented in the first place. See also the [related mailing list thread](http://lists.suckless.org/dev/1602/28307.html).

**Comment by erf** [comment]
I guess not. It depends on how much you want vis to act like vim.
