### ISSUE TITLE
:vsp not recongized as :vsplit

### ISSUE THREAD

**Issue by radare** [martanne/vis#18]
vis can use just :v but maybe we want to keep compat with vim in that aspect.

**Comment by martanne** [comment]
In theory a trie should be used and a command should be recognized once its prefix is unique. However so far I wanted to avoid the complexity of doing so. The used regex could either be adapted to only check for the prefix i.e. `^vs.*` (meaning some non sense commands will be accepted) or the prefixes could be listed individually `^vs(p|pl|pli|plit)?$` which is rather ugly but should do the trick.

**Comment by martanne** [comment]
Should be fixed, I committed the ugly regexes for now.

**Comment by martanne** [comment]
Ok this is now implemented in a clean way by using a crit-bit tree based map which supports unique prefix queries (see commits 286e1911 and ce06f56c).
