### ISSUE TITLE
Swap char does not move one char forward like in vim

### ISSUE THREAD

**Issue by erf** [martanne/vis#181]
Swap char does not move one char forward like in vim.
Example:
```
iabc<Escape>0~~
```
Expected:
```
ABc
```
Result:
```
abc
```

**Comment by martanne** [comment]
This is a mess. The reason for this behavior is that in vis `~` is a mapping for `g~l` where the latter does not move the cursor. The easy way to "fix" this is to map `~` to `g~ll`. However this will not work when given a count. Not sure whether I care about that though ...
