### ISSUE TITLE
Repeat visual selection operations fails

### ISSUE THREAD

**Issue by erf** [martanne/vis#182]
Repeat visual selection operations fails (generic case).

Substitution example ( also fails with other ops delete, change etc ).
```
ihello<Enter><Escape>kyypkviwstest<Escape>w.
```
Expected:
```
test
test
```
Result:
```
test
testhello
```

**Comment by martanne** [comment]
This was [previously discussed](https://github.com/martanne/vis/issues/44#issuecomment-153144600) (with you!). I have no plans to implement this.

In general judging by your "tests" you seem to use visual mode a lot. This is probably not the best way to use a modal editor ...

**Comment by erf** [comment]
Forgot about that. I can remove visual mode from the tests.
