### ISSUE TITLE
Replace operation act like subsitute

### ISSUE THREAD

**Issue by erf** [martanne/vis#190]
When visually selecting some text and then pressing `r`, should make the editor go into pending mode, and when pressing a key, should replace the selection with given key and exit to normal mode. Now it acts like substitute, that is, immediatly deletes the content on `r`and goes into insert mode.

Example:

```
ihello<Escape>viwrg
```

Expected:

```
ggggg
```

Result:

```
g
```

**Comment by sshbio** [comment]
A temporary workaround for this is selecting the text to replace, and then using this comand: `:s/./g/g`.

**Comment by erf** [comment]
Thanks for the fix. I noticed now that you are unable to escape the operation after you press `r`,  instead you insert `<Escape>`, or remove the character based on if you are in visual or normal mode.  Not sure if this is worth a fix, but thought i mention it.
