### ISSUE TITLE
swift language support

### ISSUE THREAD

**Issue by erf** [martanne/vis#192]
It doesn't seem to be a Scintillua lexer for the swift language - support would be appreciated.

Ref:
https://github.com/toyamarinyon/vim-swift/blob/master/syntax/swift.vim

**Comment by martanne** [comment]
It should not be rocket science to add a swift lexer yourself based on one of the similar languages. Alternatively you can try your luck by asking on the [upstream Scintillua project mailing list](http://foicica.com/lists/).

Also ideally a lexer should be based on the language specification and not on some random syntax file of another editor. The closest I found for swift is [this document](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AboutTheLanguageReference.html#//apple_ref/doc/uid/TP40014097-CH29-XID_453). However it states:

```
The grammar described here is intended to help you understand the
language in more detail, rather than to allow you to directly implement
a parser or compiler.
```

WTF, is there no formal language specification publicly available?

**Comment by erf** [comment]
Here is a link to the Swift language reference. I'd like to take a jab at this when i have time, but it seem quite comprehensive.

https://docs.swift.org/swift-book/ReferenceManual/zzSummaryOfTheGrammar.html
