### ISSUE TITLE
lua error handling

### ISSUE THREAD

**Issue by eworm-de** [martanne/vis#197]
As of commit 979ab795 `vis` shows lua errors in a dedicated window/file. However this makes `vis` complain when `lpeg` is not installed:
```
/usr/share/vis/lexers/lexer.lua:856: module 'lpeg' not found:
        no field package.preload['lpeg']
        no file '/root/.config/vis/lpeg.lua'
        no file '/root/.config/vis/lexers/lpeg.lua'
        no file '/usr/local/share/vis/lpeg.lua'
        no file '/usr/local/share/vis/lexers/lpeg.lua'
        no file '/usr/share/vis/lpeg.lua'
        no file '/usr/share/vis/lexers/lpeg.lua'
        no file '/usr/share/lua/5.3/lpeg.lua'
        no file '/usr/share/lua/5.3/lpeg/init.lua'
        no file '/usr/lib/lua/5.3/lpeg.lua'
        no file '/usr/lib/lua/5.3/lpeg/init.lua'
        no file './lpeg.lua'
        no file './lpeg/init.lua'
        no file '/usr/lib/lua/5.3/lpeg.so'
        no file '/usr/lib/lua/5.3/loadall.so'
        no file './lpeg.so'
/usr/share/vis/lexers/themes/default-16.lua:4: attempt to index a nil value (local 'lexers')
```
In [README](/martanne/vis/blob/master/README.md) you claim that `lpeg` is a runtime dependency. So either make `lpeg` a hard dependency or suppress errors if `lpeg` is not loaded at all.

**Comment by martanne** [comment]
Does 73dda181924e869b298e026981613734bebdef7b fix/improve the issue? 

The downside is that most users who do not have `lpeg` installed, will not realize why the syntax highlighting does not work.

**Comment by eworm-de** [comment]
It does improve but not fix the issue. The window/file does no longer contain the message about lpeg, but it still has the message about the theme:
```
/usr/share/vis/lexers/themes/default-16.lua:4: attempt to index a nil value (local 'lexers')
```

**Comment by martanne** [comment]
Ok I missed that, adding `vis.lexers = {}` before the assignment `vis.lexers = require('lexer')` should fix it?

**Comment by eworm-de** [comment]
Yes, and the status line shows:
```
WARNING: could not load lexer module
```
I am fine with that, though you could add a hint about lpeg possibly missing.
I think missing lpeg is the most common case for failing lexer, no?

**Comment by martanne** [comment]
Yes another reason is that the `lexer` sub directory is not in a known location where vis expects it. This could be improved by also checking for its existence relative to the executable location.
