### ISSUE TITLE
No blink on OSX

### ISSUE THREAD

**Issue by erf** [martanne/vis#202]
Primary multiple cursor does not blink on OSX. If i open a syntax hl supported text file and there is a non space char, the primary cursor look like the other cursors. If it's on a space char it disappears. If i open a regular text file, the opposite happens - also moving from a an empty space, the primary cursor leaves behind a single underscore character.

**Comment by martanne** [comment]
Is it better now? I did indeed not test it with files without syntax highlighting. With the latest changes the color theme is now also loaded for these files. At least with [st](http://st.suckless.org/) it seems to work as expected ...

**Comment by erf** [comment]
The behaviour remains the same, both with and withouth syntax highlighting. (ps: i do not load a custom visrc.lua ..)

**Comment by martanne** [comment]
Well if blinking does not work for you, then change it to something else like underline or color it red etc.

Not sure whether blinking is such a good idea anyway ...

**Comment by erf** [comment]
Ah. terminial configuration was set to no blink - sorry. Closing.
