### ISSUE TITLE
Scrolling the window with <C-y> does not work consistently

### ISSUE THREAD

**Issue by joshaw** [martanne/vis#216]
Using the key `<C-y>` to scroll the window down down only seems to work when the cursor is on the first character in the line. Otherwise, the window jumps so that the cursor is at the top of the display. 

I believe the problem is in [`view_viewport_up`](https://github.com/martanne/vis/blob/master/view.c#L804-L834) (there is a note there about scrolling up being "somewhat tricky"!) but I'm afraid I haven't got anywhere with working out what may be up yet.

**Comment by martanne** [comment]
I haven't spent much time actually testing this. So feel free to re-open if you encounter an issue. If you do so, please supply detailed information how to reproduce.

**Comment by joshaw** [comment]
I happened to notice this change almost as it happened!

It looks like it fixes a number of the scrolling related issues, but looks like it has damaged scrolling up. With view more than a window's height from the top of a file, place cursor on first line and `k` to move up, screen jumps rather than moving 1 line. `j` seems to be fine.

**Comment by martanne** [comment]
>  k to move up, screen jumps rather than moving 1 line

Yes I noticed that too, is it bad though? I will have to spend some more time with the new behavior ...

**Comment by martanne** [comment]
> k to move up, screen jumps rather than moving 1 line

Since efe5f155bf526be4448ed8b4a0cda9072e107a79 this is also the case for `j`.

As noted elsewhere, I'm not yet sure whether I like the new behavior. Opinions?
