### ISSUE TITLE
Issue w/ changing themes

### ISSUE THREAD

**Issue by TieDyedDevil** [martanne/vis#221]
While working on a light-background theme I discovered that a lexer may capture variables that won't be reloaded when changing the theme.

For example:

I defined a new theme `light-16.lua` which has a different `STYLE_EMBEDDED` than does `dark-16.lua`.

My default theme is `dark-16`.

When I edit `README.md` and then `:set theme light-16`, the new `STYLE_EMBEDDED` is not applied because `markdown.lua`, which redefines `STYLE_EMBEDDED`, has already been loaded.

One way to resolve this, I think, would be to unload all the lexers just before the loop in `vis_theme_load()`. Unfortunately I don't understand the C->LUA API well enough to do this myself.

**Comment by martanne** [comment]
Yes the lexers would have to be *reloaded* for the changes to take effect. Lua caches all loaded modules hence not only those lexers used for the current set of windows but also all previously used ones would have to be reloaded. Maybe clearing the whole `package.loaded` table would work?

We currently support Lua based motions and text objects, in the long run it should also be possible to define `:commands` in Lua. Implementing this sort of thing in C is possible, but ugly. And the Lua based commands would be useful for other stuff too.

More generally speaking, I'm wondering whether run-time theme changing should be supported at all? I understand that it is sometimes useful, for example while traveling with changing lighting conditions. A friend of mine patched the `st` terminal emulator to change the default color palette via a key binding. That way all console applications pick up the change ...

**Comment by TieDyedDevil** [comment]
My application is to have a different color scheme for use with a video projector. The ones I've used don't seem to perform very well with dark backgrounds, especially with certain pairs like red on black and blue on black.

Personally, I'd be OK with removing `:set theme ...` and setting `VIS_THEME=...` in the environment.

Does your friend's `st` patch work with color pairs or only with individual colors? It seems to me that it'd be very difficult to make the latter usable in the general case.

**Comment by martanne** [comment]
> it should also be possible to define :commands in Lua

As of 130e629434c4d87a18a886e5f98fa83dd897f742 this should now work. Maybe this can be used to implement the theme changing and reload all required Lua modules?

My friend's `st` patch does simply modify the 16 standard colors. This obviously only works for applications using the 16 color palette.
