### ISSUE TITLE
Not able to use C-d C-u to move half-page up/down when in visual mode

### ISSUE THREAD

**Issue by erf** [martanne/vis#222]
Im not able to use C-d C-u in visual mode to move half-page up/down anymore. It would be nice to be able to do this if you only have one cursor enabled.

**Comment by martanne** [comment]
The reason this was changed is that with the `:x/pattern` command you might get multiple selections far apart in the text. By default the primary cursor will be focused. Pressing `C-u` or `C-d` is a quick way to check the other matches. If there was only one match then your proposal (scrolling) would modify the selection which is not what is expected.

There should probably be an indication on the status bar showing how many cursors are currently active. Even better would probably be something like `n/m` meaning the primary cursor is on selection `n` of `m`.

Also there was not much thought given to the `C-d` and `C-u` key bindings, maybe there are better options available? In visual mode `C-j` and `C-k` have the same effect.

Maybe you could simply use `C-b` and `C-f` which scroll full pages?

Or you could just add a custom key binding to your `visrc.lua` file somthing like:

    vis:command("map! normal <C-d> <window-halfpage-down>")

**Comment by erf** [comment]
I understand. I'll have to dig into `structural regular expressions` soon, which will probably make visual mode less necessary - it seem very useful so far in that i can create a bunch of cursor searching for a word. I was wondering will it remove the need to `write our own regular expression engine` as you mention in `README.md`? Showing number of cursors on the status bar seem useful ( you should probably make it optional in `visrc.lua` for minimalists ). Maybe some other key bindings might be useful, I'll have to think more about it, anyway i could just add custom binding for now as you suggests. I feel i lose focus when moving whole pages. Anyway, enjoying the editor and congrats on all the recent :star2: !

**Comment by martanne** [comment]
My example command above should of course have been (notice the correct mode this time): 
```
vis:command("map! normal <C-d> <window-halfpage-down>")
```

> Even better would probably be something like n/m meaning the primary cursor is on selection n of m

This should now be implemented. I'm closing this issue for now, because I prefer the current behavior.

The multiple cursor related key bindings should be revised at some point ....
