### ISSUE TITLE
using visrc.lua

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#225]
do i have to rebuild vis every time i edit visrc.lua? if so, i'd like to request that it be read on startup instead, like vimrc.

edit: ok, it's installed with the support files, and we can edit it there. can we have a file in our home directory to edit?

edit2: ok, we can use $XDG_CONFIG_HOME/vis. this should probably be stated in the readme.

**Comment by martanne** [comment]
It is sort of documented in the [manual page](https://github.com/martanne/vis/blob/master/vis.1#L22), but I agree documentation could certainly be improved.
