### ISSUE TITLE
Building on cygwin

### ISSUE THREAD

**Issue by giann** [martanne/vis#226]
How can I build this for cygwin ?
I tried https://github.com/martanne/vis/issues/195#issuecomment-200263182 but configure keeps complaining it doesn't find libtermkey

**Comment by martanne** [comment]
Does your closing of the issue indicate, that you manged to compile it?

Pushing libtermkey into upstream Cygwin or msys2 would be helpful ...

**Comment by martanne** [comment]
As mentioned [elsewhere](https://github.com/martanne/vis/issues/162#issuecomment-213526552) if you have the necessary dependencies installed via Cygwin, `make local` should now work (albeit with quite a few warnings).
