### ISSUE TITLE
Remove hard-coded color spec from Markdown lexer

### ISSUE THREAD

**Issue by TieDyedDevil** [martanne/vis#229]
This is essential for proper interaction with themes.

``` diff
diff --git a/lexers/markdown.lua b/lexers/markdown.lua
index 14380e9..0257010 100644
--- a/lexers/markdown.lua
+++ b/lexers/markdown.lua
@@ -91,7 +91,7 @@ M._tokenstyles = {
   h2 = hstyle..',size:'..(font_size + 4),
   h1 = hstyle..',size:'..(font_size + 5),
   code = l.STYLE_EMBEDDED..',eolfilled',
-  hr = 'back:black,eolfilled',
+  hr = l.STYLE_DEFAULT..',bold',
   link = 'underlined',
   link_url = 'underlined',
   link_label = l.STYLE_LABEL,
```

**Comment by martanne** [comment]
The toml and yaml lexers seem to have similar issues using the currently not supported syntax `%(color.red)`.

**Comment by TieDyedDevil** [comment]
Those are different. The intent seems to be to change the background color to red for invalid whitespace. I can't get that to happen; probably because of the unsupported syntax. On the other hand, the failure seems to be silent. I opened a YAML file and the highlighting seems fine.

Even if $(color.foo) was supported, this is is probably acceptable usage. A red background should render readably regardless of "usual" background colors (typically black, white and shades of gray). Of course, it'd be unfortunate (in more ways than one) if the user chooses a theme with a red background.

The original override in markdown.lua, on the other hand, assumes a light-colored background.

My recommendation is to leave the toml and yaml lexers alone for now.
