### ISSUE TITLE
Lua search path ignores configure's --prefix/--sharedir

### ISSUE THREAD

**Issue by strout** [martanne/vis#231]
This project looks very cool and I'm excited to try it out soon :)

I'm trying to write a [NixOS](https://nixos.org/) package for `vis`. NixOS puts its packages in a non-standard location (`/nix/store/<long hash>` instead of `/usr/local`), which passed as `--prefix` to the configure script. This value doesn't seem to make its way to `vis-lua.c`, however, so the default `visrc.lua` and `themes/default-16.lua` aren't found. See the output below when I run `vis` after installing it. In this case, `visrc.lua` is at `/nix/store/90gcngh2xxvpzwggmc0bv7lfkdqf9iq0-vis-0.2/share/vis/visrc.lua` and `default-16.lua` is at `/nix/store/90gcngh2xxvpzwggmc0bv7lfkdqf9iq0-vis-0.2/share/vis/lexers/themes/default-16.lua` -- I would expect those paths to be checked instead of (or in addition to) those starting with `/usr/local/share`.

If you prefer, I can make the change via pull request in the next couple of days.

Output of `vis`:

```
module 'visrc' not found:
        no field package.preload['visrc']
        no file '/nix/store/90gcngh2xxvpzwggmc0bv7lfkdqf9iq0-vis-0.2/bin/visrc.lua'
        no file '/nix/store/90gcngh2xxvpzwggmc0bv7lfkdqf9iq0-vis-0.2/bin/lexers/visrc.lua'
        no file '/home/steve/.config/vis/visrc.lua'
        no file '/home/steve/.config/vis/lexers/visrc.lua'
        no file '/usr/local/share/vis/visrc.lua'
        no file '/usr/local/share/vis/lexers/visrc.lua'
        no file '/usr/share/vis/visrc.lua'
        no file '/usr/share/vis/lexers/visrc.lua'
        no file '/usr/share/lua/5.2/visrc.lua'
        no file '/usr/share/lua/5.2/visrc/init.lua'
        no file '/usr/lib/lua/5.2/visrc.lua'
        no file '/usr/lib/lua/5.2/visrc/init.lua'
        no file './visrc.lua'
        no file '/usr/lib/lua/5.2/visrc.so'
        no file '/usr/lib/lua/5.2/loadall.so'
        no file './visrc.so'
module 'themes/default-16' not found:
        no field package.preload['themes/default-16']
        no file '/nix/store/90gcngh2xxvpzwggmc0bv7lfkdqf9iq0-vis-0.2/bin/themes/default-16.lua'
        no file '/nix/store/90gcngh2xxvpzwggmc0bv7lfkdqf9iq0-vis-0.2/bin/lexers/themes/default-16.lua'
        no file '/home/steve/.config/vis/themes/default-16.lua'
        no file '/home/steve/.config/vis/lexers/themes/default-16.lua'
        no file '/usr/local/share/vis/themes/default-16.lua'
        no file '/usr/local/share/vis/lexers/themes/default-16.lua'
        no file '/usr/share/vis/themes/default-16.lua'
        no file '/usr/share/vis/lexers/themes/default-16.lua'
        no file '/usr/share/lua/5.2/themes/default-16.lua'
        no file '/usr/share/lua/5.2/themes/default-16/init.lua'
        no file '/usr/lib/lua/5.2/themes/default-16.lua'
        no file '/usr/lib/lua/5.2/themes/default-16/init.lua'
        no file './themes/default-16.lua'
        no file '/usr/lib/lua/5.2/themes/default-16.so'
        no file '/usr/lib/lua/5.2/loadall.so'
        no file './themes/default-16.so'
```

**Comment by strout** [comment]
As an aside, should the PWD-relative paths be there? Editing a file in an untrusted directory which happens to contain a malicious `./visrc.lua` (or `./visrc.so`!) seems bad currently.

**Comment by martanne** [comment]
Thanks for packaging!

> If you prefer, I can make the change via pull request in the next couple of days.

Yes that would be appreciated.

As for the relative paths, they seem to originate from the default lua `package.path` which is extended by vis. They should probably be removed. It is not such a severe security issue because the search will stop upon first match which is either relative to the binary location (assumed to be trusted) or `/usr/{local,}/share/vis`.

**Comment by martanne** [comment]
> If you prefer, I can make the change via pull request in the next couple of days.

Any updates on this? It just got reported again as #269 ...

**Comment by chexxor** [comment]
I don't have a fix for the prefix issue, but I think I made a working Nix package for OP. I didn't test the Lua scripting stuff.
See: https://github.com/chexxor/vis.nix/blob/patch-1/vis.nix

**Comment by martanne** [comment]
> As an aside, should the PWD-relative paths be there? 

As of b2ec2cdff86a022f1eb0e267fe36e807b2446d2b they should be gone.

**Comment by martanne** [comment]
@chexxor thanks for packaging vis for NixOS!

Does there exist a "better" package link than to the [nixpkg github repository](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/vis/default.nix) I could refer to from the README?

**Comment by chexxor** [comment]
@martanne The Nixpkgs project has a CI system, called Hydra, which builds all packages and hosts the produced packages, but I don't see Vis in there yet. There's a ton of jobs to process, so I Hydra could be lagging behind. I'm not familiar with it, so perhaps it's a different issue.

I guess we'd be able to see it from a search on hydra.nixos.org, like this one: http://hydra.nixos.org/eval/1260469?filter=vis&compare=1260447&full=#tabs-unfinished
and the page would look like this: http://hydra.nixos.org/build/34460128

I'll keep an eye on Hydra to see if Vis package appears there. If not soon, then I'll post to their mailing list about it. In the meantime, that Github link should be ok.
