### ISSUE TITLE
make standalone fails on ubuntu 14.04

### ISSUE THREAD

**Issue by AndrewVos** [martanne/vis#233]
```
make[2]: libtool: Command not found
```

On 14.04 there are two requirements:

```
sudo apt-get install libtool libncursesw5-dev
```

Leaving this here for anyone else who encounters this.

**Comment by martanne** [comment]
Thanks for the information. An issue is probably not the right place to document this kind of stuff though. The make standalone target assumes that all build dependencies (of all third party libraries) are present on the system.
