### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by terhorst** [martanne/vis#235]
This issue arose when trying to create a Homebrew formula for vis (Homebrew/homebrew-core#127). There is already a [command of the same name](http://www.freebsd.org/cgi/man.cgi?query=vis&sektion=1&apropos=0&manpath=freebsd) in BSD (and hence, OS X). Our initial thought was to simply rename the binary, but then of course the manpage must be renamed and itself edited; some other vis-* commands should also be renamed; and renaming could cause other problems we haven't even thought of. It quickly gets to be a big headache. I don't have any good ideas here and wanted to see if you guys had any thoughts.

**Comment by terhorst** [comment]
Nevermind, just discovered #101.

**Comment by martanne** [comment]
Yes this is unfortunate, with hindsight it was probably a bad decision, [at the time](http://lists.suckless.org/dev/1409/23525.html) it seemed like a good reference/joke.

Maybe the whole project could be renamed once a major milestone is reached / 1.0 is released. This won't solve the issue in the short term though.

Renaming the binary in homebrew will only cause more confusion and is the wrong thing to do.
