### ISSUE TITLE
<Space> map bug

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#246]
if i run `:map! normal <Space> h`, the behavior doesn't change, and when i run `:help`, there are two normal mode mappings listed for `<Space>`. mapping with `" "` works fine.

**Comment by joshaw** [comment]
That's odd, I was looking into exactly this issue not 15 minutes ago.

You can set up key aliases in `config.h` (as a work around for the moment) to set up a mapping with a space since a literal space can be used there, eg

    { " ",           ALIAS("h")     },

**Comment by aeosynth** [comment]
a literal space can be used with the map command: `:map! normal " " h`  works

**Comment by martanne** [comment]
Yes `<Space>` is a special case. We should either document this or replace any `<Space>` with a literal space when setting up a key binding.

**Comment by martanne** [comment]
bd1d849b2033b04a372542c59d458d4f8279c937 should fix this, not completely sure whether it is a good solution though, because in insert/replace mode a literal space has to be used ...

**Comment by martanne** [comment]
This caused other issues #280 therefore we are back to a literal space ...

**Comment by aeosynth** [comment]
is there any  point to this line then? https://github.com/martanne/vis/blob/master/config.def.h#L54:

	{ " ",                  ALIAS("<Space>")                            },

**Comment by aeosynth** [comment]
> We should either document this

still needs documentation
