### ISSUE TITLE
 make standalone fails on Debian GNU/Linux 8 (jessie)

### ISSUE THREAD

**Issue by sparrisable** [martanne/vis#248]
make standalone gives the following message on Debian GNU/Linux 8 (jessie):

make -C dependency/build//libtermkey-0.18 PREFIX=/home/peter/Dokument/programs/vis/vis-0.2/dependency/install/usr termkey.h libtermkey.la
make[2]: Går till katalogen ”/home/peter/Dokument/programs/vis/vis-0.2/dependency/build/libtermkey-0.18”
make[2]: Inget behöver göras för ”termkey.h”.
libtool --quiet --mode=link --tag=CC musl-gcc -rpath /home/peter/Dokument/programs/vis/vis-0.2/dependency/install/usr/lib -version-info 13:0:12 -lncursesw -o libtermkey.la termkey.lo driver-csi.lo driver-ti.lo
/usr/bin/ld: cannot find -lncursesw
collect2: error: ld returned 1 exit status

**Comment by martanne** [comment]
Thanks for the report, do you plan to investigate the issue and follow up with a patch?

These make targets (`standalone` and `local`) are intended for advanced users/developers who are comfortable building from source and debugging the resulting breakage.

Either we should fix these issue or simply remove the reference from the README. I personally won't have time to debug this kind of issue on various distributions ...

Also as a general remark, it is typically a good idea to set the locale to English when reporting error messages.

**Comment by sparrisable** [comment]
Thanks for your fast reply. My intention was just to report the behavior on a system that I use.
I completely understand that it is not practical to debug every distribution. 
I noticed that there are binaries for some distributions, I guess that one of these might be a "primary" distribution that vis is developed on.

**Comment by sparrisable** [comment]
I got the vis executable by adding a -L directive by hand. 

The following command failed for me in ../dependency/build/libtermkey-0.18/:
libtool --quiet --mode=link --tag=CC musl-gcc -rpath /mnt/disk_100gb/programs/vis/vis/dependency/install/usr/lib -version-info 13:0:12 -lncursesw -o libtermkey.la termkey.lo driver-csi.lo driver-ti.lo

I ran the following manually (adding -L with the same directory as the rpath):
libtool --quiet --mode=link --tag=CC musl-gcc -rpath /mnt/disk_100gb/programs/vis/vis/dependency/install/usr/lib -L /mnt/disk_100gb/programs/vis/vis/dependency/install/usr/lib -version-info 13:0:12 -lncursesw -o libtermkey.la termkey.lo driver-csi.lo driver-ti.lo

Then I ran "make standalone" again and it worked.

**Comment by josuah** [comment]
I can tell `make local` and worked on arch:

```
Linux archbang 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```

Not `make standalone, though.  It could not some lua C functions.

I am learning about compilation and C thanks to this.

**Comment by josuah** [comment]
I could also compile vis locally, with all libraries build locally as well, without using the special `local` or `standalone`:

```
export PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1
export PKG_CONFIG_ALLOW_SYSTEM_LIBS=1
export CFLAGS="-I$LOCAL/include -L$LOCAL/lib"

./configure
make PREFIX="$PREFIX" install
```

**Comment by josuah** [comment]
I could also build under Android with termux.

Libtermkey (required by vis), libtool (required by libtermkey), m4 (required by libtool) all failed to compile, so I used the termux provided ones, but after that, the whole vis compilation came without issue (without lua binding).
