### ISSUE TITLE
Pasting text from clipboard produces extra spaces

### ISSUE THREAD

**Issue by erf** [martanne/vis#249]
Pasting the following lines of text from the clipboard, with an extra space at the begninning of each line
```
 line1 of text
 line2 of text
 line3 of text
```
will produce the following
```
 line1 of text
  line2 of text
   line3 of text
```
adding an extra space for each new line of text.

If two spaces before each line of text, two extra spaces will be added per pasted line and so on.
```
  line1 of text
    line2 of text
      line3 of text 
```

**Comment by martanne** [comment]
Define "pasting"? `"*p` should work?

You likely have auto indentation enabled? Your pasted new line will cause vis to copy the leading white space from the previous line etc. Vim has `:set paste` for this kind of stuff...

**Comment by erf** [comment]
I was refering to pressing `<cmd>v` in `insert mode`, with `auto indentation` enabled - `"*p` works.
