### ISSUE TITLE
Autocompletion in prompt 

### ISSUE THREAD

**Issue by jvoisin** [martanne/vis#25]
It would be great to have some autocompletion in the prompt, like for `set syntax <tab>` to get all available syntaxes, or `r <tab>` to get every files in the current folder.

**Comment by martanne** [comment]
I would rather avoid the complexity for command options if possible.

For file names I plan to use [slmenu](https://bitbucket.org/rafaelgg/slmenu) not yet 100% sure how/if it will work in practice.

The idea is to run something like `ls -1 | slmenu` then open whatever is printed to stdout. This could then be wrapped in a shell script which checks whether the output is a directory and if so reruns slmenu with the content of it etc.

**Comment by jvoisin** [comment]
In vim, I'm using the following script for fuzzy-matching:

```
    " DMENU + VIM = <3
    " Strip the newline from the end of a string
    function! Chomp(str)
        return substitute(a:str, '\n$', '', '')
    endfunction

    " Find a file and pass it to cmd
    function! DmenuOpen(cmd)
        let fname = Chomp(system("find . -type f -readable | dmenu -i -l 20 -p " . a:cmd))
        if empty(fname)
            return
        endif
        execute a:cmd . " " . fname
    endfunction

    " ctrl + t: open a new tab
    map <c-t> :call DmenuOpen("tabe")<cr>
```

**Comment by tqtifnypmb** [comment]
Maybe simple auto-completion is necessary , like `q <tab> ==> qall`

**Comment by martanne** [comment]
Unique prefixes of commands are recognized that is you can simply type `qa`. I agree that something like `:help set` which displays all available options might be useful.

**Comment by martanne** [comment]
I just [pushed a change](https://github.com/martanne/vis/commit/a657e8499ab04bf8b9b4ffcb954acee574d239a1) implementing the file opening stuff I had in mind. My shell scripting skills are quite rusty, would be nice if a few people could give it at try. Make sure you have [vis-open](https://github.com/martanne/vis/blob/master/vis-open) and either [slmenu](https://bitbucket.org/rafaelgg/slmenu) or [dmenu](http://tools.suckless.org/dmenu/) in `$PATH`.

Then within vis do something like `:open *.[ch]`.

**Comment by martanne** [comment]
Did anyone try it out? I'm going to close this issue since the existing solution is fine for me and tab completion for individual options doesn't seem to be worth it. (If someone wants to implement it, [map_prefix](https://github.com/martanne/vis/blob/master/map.h#L26) and [map_iterate](https://github.com/martanne/vis/blob/master/map.h#L23) are probably a good starting point).
