### ISSUE TITLE
vim modeline support

### ISSUE THREAD

**Issue by tycho** [martanne/vis#256]
Just discovered vis a couple days ago on Hacker News, and am starting to add some issues for my wishlist items.

I've got several projects that have varying formatting rules (some use spaces, some use tabs, varying tab widths, etc). It would be nice if vis supported vim modelines, such as:

```
/* vim: set ts=4 sts=4 sw=4 et: */
```

```
/* vim: set ts=8 sts=8 sw=8 noet: */
```

This would require some new options to enable handling of modelines. Vim uses the option "modeline" as a flag to enable/disable handling of modelines, and the option "modelines" to indicate the number of lines to read at the head and tail of the file to search for the modeline specifiers.

I'd recommend not going full-vim on this feature though. Accepting arbitrary modelines by default could be potentially dangerous. I'd recommend starting with only only allowing cosmetic flags to be altered. Perhaps it would be useful to have an option whitelisting specific options to be modified by a modeline?

This would also require adding some new options and aliases for existing ones:
- The existing "tabwidth" option would need to be "tabstop" with an alias "ts" to be vim-compatible.
- "expandtab" would need an alias "et", with an optional "no" prefix to disable it.
- "softtabstop" ("sts") would need to be implemented (and the definition of "tabwidth" would need to change accordingly)
- "shiftwidth" ("sw") would need to be implemented, if auto-indenting is implemented (I haven't looked)

**Comment by tycho** [comment]
You could also add support for new vis modelines like:
```
/* vis: set tabwidth=8: */
```
or similar.

And then you could handle vim modelines by mapping the vim option names to vis-specific options (e.g. 'ts' -> 'tabwidth').

**Comment by martanne** [comment]
In principle I don't like modelines, simply use tabs for indentation and spaces for alignment and let each developer set the preferred tabwidth. However I realize this is not practical in the real world.

This should be implemented in one of the [Lua event handlers](https://github.com/martanne/vis/blob/a07e827462350b64106ba14b8b62d74c3ebc090c/visrc.lua#L202). Here is a link to the [modeline format used by vim](http://vimdoc.sourceforge.net/htmldoc/options.html#modeline).

Also vis might require some cleanups related to option handling, some should apply globally, some to the current file, others only to the current window etc.

**Comment by tycho** [comment]
I totally agree that "tabs for indentation, spaces for alignment" is the One True Way(tm) to write code, but sadly it doesn't always apply. Some people are rabidly opposed to tabs. And then there are whitespace-sensitive languages like Python. :(

Even if this is implemented in a Lua event handler, we'd still need to support the necessary options I mentioned in the first post. And yes, properly scoping the options will be a pain... Need to think about that.

**Comment by hzhou** [comment]
I disagree the so called "tabs for indentation, spaces for alignment" unless the alignment is restricted to inside-the-line alignment. When alignment is the leading spaces, then it visually is not distinguishable from indentation and you end up with tab/space mixture. I do think the editor options should be greatly simplified but I do not agree that "simply use tabs for indentation". My habit is use 4 spaces for indentation and always leave tab size to be default 8. Changing tab size often screw up some code that happen to have space/tab mixtures, such as those with vim's softtab setting, while space of 8 indentation is just too wide.

I wrote a gist (https://gist.github.com/hzhou/a99506767b5c8b6bcb9c64edbe5c3e03) to summarize my proposal.

**Comment by tycho** [comment]
http://vim.wikia.com/wiki/Indent_with_tabs,_align_with_spaces

**Comment by hzhou** [comment]
@tycho I was against the scenario of "continuation of lines alignment". It simply interferes with indentation. And the idea of using invisible tab/space differentiation in a semantic way is just bad idea.

For in-the-line alignment, there is no argument. But then there is no issue -- no editor options/features are concerned here.

**Comment by tycho** [comment]
sure there are. not every project has the same indentation policies.

**Comment by hzhou** [comment]
@tycho, there are what?

**Comment by raedwulf** [comment]
When using vim, you can use scripts to visually distinguish tabs and spaces: this is done either by adding a symbol for either tabs or spaces using :set list and :set listchars.
My preferred way is to have different background colours for tab indentation: https://github.com/nathanaelkane/vim-indent-guides

I'm quite busy at the moment, but either one of those are viable options for indent with tabs + align with spaces.  Hopefully someone has the time to implement them.

**Comment by eworm-de** [comment]
How about going with editorconfig?
http://editorconfig.org/

**Comment by aeosynth** [comment]
editorconfig has an official [lua](https://github.com/editorconfig/editorconfig-core-lua) binding to locate and parse `.editorconfig` files

**Comment by seifferth** [comment]
There are actually plugins for both [vim modelines][1] and [editorconfig][2] available by now. Links are included [in the wiki][3]. I guess that solves this issue.

[1]: https://github.com/lutobler/vis-modelines
[2]: https://github.com/vktec/vis-editorconfig
[3]: https://github.com/martanne/vis/wiki/Plugins#existing-plugins

**Comment by martanne** [comment]
I haven't actually used these plugins, but it is definitively the right way to provide this functionality.
