### ISSUE TITLE
~ doesn't map to $HOME

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#273]
`:e ~/foo` opens a new file, instead of the file located at `$HOME/foo`.

**Comment by martanne** [comment]
Is 69c43ac9c75c3b3b07845942e9bcf24f78217239 good enough? I do not want to handle this kind of stuff inside the editor ...

**Comment by aeosynth** [comment]
command failed. am i supposed to use `vis-open`? is there an example on using it?

**Comment by martanne** [comment]
Yes. First check in a shell whether `./vis-open` works (it should list the current directory content), then place it somewhere in `$PATH` or do `sudo make install` if you have `/usr/local/bin` in your `$PATH`.

**Comment by aeosynth** [comment]
`Neither slmenu nor dmenu found`

i'm not sure if i'm interested in installing either of those

**Comment by martanne** [comment]
As mentioned  in #266 maybe it would be best to just bundle `slmenu` as `vis-menu` ...

**Comment by martanne** [comment]
The current behavior with an external tool, letting the shell perform the expansion seems good enough.

Whether we wan't to bundle such a tool with vis is an orthogonal question to that.
