### ISSUE TITLE
`viB` when bottom of bracket is below screen view, moves view all the way down

### ISSUE THREAD

**Issue by erf** [martanne/vis#274]
Doing `viB` when bottom of bracket is below screen view, moves the view all the way down so only the bottom of the bracket is showing. It would be better if the bottom of the view is set to the bottom of the bracket, if the bracket is below current screen view.

**Comment by martanne** [comment]
This should be fixed by c8d1e2296688a77d7b0024cc572164dae694cd87.

**Comment by erf** [comment]
Thanks for the fix, but i think it could be improved further by setting the bottom of the view to the bottom of the bracket, so that you can see as much as possible of your selection.

**Comment by martanne** [comment]
Just use `o` to display the other end of the selection.
