### ISSUE TITLE
vis->event

### ISSUE THREAD

**Issue by hzhou** [martanne/vis#275]
It appears that if you directly call vis_lua_start, vis_lua_file_open, etc. directly, you don't need VisEvent and you can cut quite a few lines and save some detours for developers.

**Comment by hzhou** [comment]
I guess maybe the VisEvent table is a set up to switch from multiple alternatives of lua interfaces. I think it can be accomplished simpler with 7 macros and defined in config.h, which is a better place than in main.c.

**Comment by martanne** [comment]
Lua support is currently optional, therefore `vis_lua_*` functions should not be called directly from `vis.c`. Furthermore you might want to invoke another programming language (Scheme?) thus this is designed as general notification mechanism. Also different editor instances created with `vis_new` could have different registered callbacks...
