### ISSUE TITLE
:wq while editing with multiple cursors deletes entire file contents

### ISSUE THREAD

**Issue by t-mw** [martanne/vis#276]
To reproduce, create a file with several lines, place multiple cursors on the lines with `Ctrl-K` and then quit with `:wq` while the cursors are still active. All of the lines within the file are deleted, expect for the line of the primary cursor.

**Comment by martanne** [comment]
This should hopefully be fixed, but as the necessary changes touched quite a bit of "safety critical" code, one should use it with appropriate care ...

**Comment by t-mw** [comment]
Ok, thanks for the quick reply. I've tried writing a simple test in case of regressions.
