### ISSUE TITLE
Wrong cursor position at the bottom line in insert mode

### ISSUE THREAD

**Issue by vwyu** [martanne/vis#278]
I am not sure if this issue was discussed before. I go into insert mode in an empty file and press enter key (`<CR>`) until I reach the bottom line on the screen. In the bottom line, the cursor is shown on the second column. I would expect it to stay on the first.

**Comment by vwyu** [comment]
![issue](https://cloud.githubusercontent.com/assets/13724876/14632053/7d34c580-0651-11e6-9f80-0f84f4ca92ef.gif)

**Comment by martanne** [comment]
Thanks for the detailed report! With the latest changes this behavior should be improved, for now the last `~` will always be displayed. This seems good enough.
