### ISSUE TITLE
Make o and O work with a given number

### ISSUE THREAD

**Issue by erf** [martanne/vis#279]
Make o and O work with a given number, so that you can insert multiple new lines. 

NOTE: This is not a VIM functionality, but i thought it might be an good idea.

**Comment by martanne** [comment]
You need to be more specific, what behavior would you expect? Place a new cursor on every new line?

**Comment by erf** [comment]
I meant you would insert n number of newline chars if given a number before 'o' and 'O'

**Comment by martanne** [comment]
Why is that useful, certainly doesn't seem to me ...

**Comment by erf** [comment]
I had a usecase earlier, but no biggie. Could perhaps be usefull to also be able to insert any chars n number of times ( as discussed here http://stackoverflow.com/questions/5054128/repeating-characters-in-vim-insert-mode). You could perhaps use a macro for this - if you were able to repeat a macro n number of times.

**Comment by erf** [comment]
..but i do like the idea of consistently being able to repeat all operators.
