### ISSUE TITLE
let text_find_next return -1 if not found

### ISSUE THREAD

**Issue by erf** [martanne/vis#281]
I have a problem with `text_find_next` in `text-motions.h` - if i try to find a matching text starting on pos `x`, and the match is on pos `x`, how do i know if there is a match or a `not found`? I suggest this method return `-1` for a `not found`, and not the original position.

Update: I will make a pull request for this soon..

**Comment by martanne** [comment]
Changing this will break things, the current code relies on this behavior because the cursor should remain at the same position if no match is found. Join the the IRC channel `#vis-editor` on freenode if you want to discuss your problem ...
