### ISSUE TITLE
vim linewise behavior

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#287]
maybe i just need to get used to it, but there are many places where vis and vim differ with start/end of line behavior. one example: in vis, pressing `a` at eol moves the cursor to the start of the next line, whereas in vim, the cursor stays on the current line. can we have the vim behavior?

**Comment by george-b** [comment]
Just as a heads up I would suggest reading the following regarding newline addressability in vis.

https://github.com/martanne/vis/pull/54

Maybe you are already aware but if not it explains the behavior of vis.

**Comment by martanne** [comment]
@aeosynth the example you gave should be fixed, could please report some of the "many places where vis and vim differ with start/end of line behavior"?

**Comment by aeosynth** [comment]
thanks for fixing `a`. i will not be able to test and give more examples
for at least a week.

On Wed, Apr 27, 2016 at 2:44 AM, Marc André Tanner <notifications@github.com

**Comment by martanne** [comment]
I'm going to close this for now. Feel free to reopen, if you encounter an issue, but please provide a concrete example/steps to reproduce.
