### ISSUE TITLE
Solarized theme displayed incorrectly

### ISSUE THREAD

**Issue by goldani** [martanne/vis#293]
I am using iTerm2 with the Solarized Dark color preset. When I use the command `:set theme solarized` I don't see the correct Solarized colors (instead, I see a grey background with green highlighting). I have attached a screenshot of visrc.lua open in the editor after setting the theme. 

<img width="563" alt="screen shot 2016-04-26 at 6 39 25 pm" src="https://cloud.githubusercontent.com/assets/6405321/14839397/6c1be632-0bdf-11e6-9d5e-98e67badf841.png">

`infocmp | grep colors` gives

    xterm-256color|xterm with 256 colors,
	    colors#256, cols#80, it#8, lines#24, pairs#32767,

**Comment by martanne** [comment]
The default solarized theme is intended to work with a standard terminal (i.e. without a special terminal theme). You might try #268 by @larryhynes.

But yes themes could certainly be improved, previous attempts (they might need to be updated for multiple cursor related properties) include:
 * [seti](https://github.com/martanne/vis/pull/150)
 * [papercolor](https://github.com/jceb/dotfiles/blob/master/config/vis/lexers/themes/papercolor.lua)

**Comment by goldani** [comment]
#268 by @larryhynes did the trick.
