### ISSUE TITLE
Can't delete final empty line

### ISSUE THREAD

**Issue by ianh** [martanne/vis#294]
**Reproduction Steps**
Open `vis` and type `ix<ESC>o<ESC>dd`.

**Expected Result**
The blank line that was inserted by `o` is replaced visually with a tilde `~`.

**Actual Result**
The cursor moves but the line seems to remain.

**Version**
v0.2-180-gd6effd0

**Comment by martanne** [comment]
Yes this is a known "problem", I would like to clarify that this is actually "just" a display issue i.e. the actual file content is as expected. See also [this comment](https://github.com/martanne/vis/issues/237#issuecomment-207770581) for further explanation.

**Comment by Screwtapello** [comment]
Vim has the somewhat quirky `eol` option to record whether the last line of the file includes the trailing EOL. It seems like this would be a more intuitive way to control that - if the last line ends with an EOL, there's visually blank line at the end. If you delete that blank line, then the file will be written out without a trailing EOL.

On the other hand, it's inconsistent with what other editors do, and will probably confuse a lot of people into deleting their trailing EOLs.
