### ISSUE TITLE
Entering insert mode with `a` and then leaving it advances the cursor

### ISSUE THREAD

**Issue by ianh** [martanne/vis#296]
**Reproduction Steps**
Enter some text into vis.  Move the cursor to the beginning of the text.  Alternate pressing `a` to enter insert mode and `<ESC>` to leave it.

**Expected Result**
Like in vim, the cursor moves back and forth, but returns to the same place after you press `<ESC>`.

**Actual Result**
The cursor continues to move rightward with each `a` and `<ESC>`.

**Version**
v0.2-180-gd6effd0

This is the opposite of vim, which moves the cursor backward if you press `i` and `<ESC>` over and over.  Feel free to close this if the difference is intentional, but it is a little jarring coming from vim.

**Comment by joshaw** [comment]
The `a` and `i` movements as well as new line addressibility has been discussed [here](https://github.com/martanne/vis/pull/54).

**Comment by ianh** [comment]
I think what I'm actually reacting to is not the cursor movement, but the lack of response to `<ESC>`.  In vim, the cursor moving left gives you feedback that you're back in command mode.  I feel a little uncertain in vis when I press `<ESC>` and nothing happens.

Not sure what the right way to fix this is: is there a way to style the cursor differently in insert/command mode?  I think that would resolve the issue for me.

**Comment by ianh** [comment]
Anyway, thanks for the quick reply.  Closing this since it's by design.  I'll see how much I get used to the lack of feedback; this may just be a non-issue.
