### ISSUE TITLE
Lines with the same width as the terminal shouldn't wrap

### ISSUE THREAD

**Issue by ianh** [martanne/vis#297]
Create a line in vis with the same width as your terminal, then another line after that line.  the first line shouldn't wrap, but does.

**Version**
v0.2-180-gd6effd0

The fact that you can move the cursor past the end of the line complicates this.  Vim solves it (if you press `a` at the end of a line) by placing the cursor at the beginning of the next line without wrapping.

The last line of the file behaves differently: the line doesn't wrap, but the cursor disappears entirely if you move it to the end of the line.

**Comment by martanne** [comment]
As discussed in IRC this is currently intended behavior. Newlines are addressable and take up a screen cell.
