### ISSUE TITLE
wish list

### ISSUE THREAD

**Issue by wthurein** [martanne/vis#300]
1.
One thing I find myself doing quite a bit in Vim is to copy from an edit buffer and paste into the substitute command.
It seems that in Vis we currently cannot do that.
(It is possible to copy/paste within the command buffer internally though.)
I did find a closed issue in which you mentioned that registers are not mirrored, so I guess it's a known issue.
Still it would be great if it is possible somewhere down the line.

2.
The other thing is I don't know if there is a way to view/traverse buffers currently.
That would be nice too, either Vim's way or something like :bb in Elvis.

**Comment by martanne** [comment]
1. should be possible by using an explicit register for example `"ayiw:<C-r>a` should copy the word under the cursor and paste it into the command prompt.

2. i'm not quite sure what you refer to by "Vim's way". Currently in vis you can't have a buffer which is not being displayed in at least one window. Switching between windows is done by means of `<C-w>w`, `<C-w>j`, `<C-w>k` etc. see `<F1>` or `:help` for a list of all key mappings.

**Comment by wthurein** [comment]
1. Thanks.

2. I was assuming it's similar to Vim, Elvis, etc., that if you open a file, then split-open another file, and do :quit on one of the windows, the buffer is still there in the background, just not visible. But I see that's not the case.

**Comment by martanne** [comment]
Regarding 2. I want to avoid complex buffer/file management for now. At some point I would like to experiment with a proper client/server architecture, then this could be reconsidered. See also #130 for some related thoughts.
