### ISSUE TITLE
SIGWINCH issues on FreeBSD, recommendations for resolution?

### ISSUE THREAD

**Issue by mqudsi** [martanne/vis#302]
Out-of-the-box vis does not build on FreeBSD:

```
--- vis ---
cc -pipe -Os -fPIE -fstack-protector-all -I/usr/local/include     -I/usr/local/include/lua52   -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DLUA_COMPAT_ALL -std=c99 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -DNDEBUG -D_FOR  FY_SOURCE=2 -D_BSD_SOURCE -DVERSION=\"\" -DVIS_PATH=\"/usr/local/share/vis\" -DCONFIG_LUA=1 -DCONFIG_SELINUX=0 -DCONFIG_ACL=0 array.c buffer.c libutf.c main.c map.c register.c ring-buffer.c  sam.c text.c text-motions.c text-objects.c text-regex.c text-util.c  ui-curses.c view.c vis.c vis-lua.c vis-modes.c vis-motions.c  vis-operators.c vis-prompt.c vis-text-objects.c -Wl,-z,now -Wl,-z,relro -pie -L/usr/local/lib -ltermkey -lncursesw    -L/usr/local/lib -llua-5.2 -lm -lc -o vis
main.c:2142:23: error: use of undeclared identifier 'SIGWINCH'
        sigaddset(&blockset, SIGWINCH);
                             ^
1 error generated.
ui-curses.c:1162:12: error: use of undeclared identifier 'SIGWINCH'
        sigaction(SIGWINCH, &sa, NULL);
                  ^
1 error generated.
*** [vis] Error code 1
```

In `signal.h`:
```
#if __BSD_VISIBLE
#define SIGWINCH        28      /* window size changes */
#define SIGINFO         29      /* information request */
#endif
```

From [os.freebsd.newbies](http://osdir.com/ml/os.freebsd.newbies/2005-01/msg00122.html):

> There are a few features which are traditional for BSD systems, but
> whcih are incompatible with e.g. POSIX. These tend to be hidden
> behind #ifdef __BSD_VISIBLE, so that programs only see them if they
> want them.
> 
> __BSD_VISIBLE is #define's automatically by sys/cdefs.h, but you can
> disable that with a special option to gcc (-traditional, I think).

I can see `vis` does not make heavy use of `#ifdef` (thank God). What is your recommendation for resolution here?

It compiles fine like this:
```
env CFLAGS='-D__BSD_VISIBLE' ./configure
make
sudo make install
```

**Comment by martanne** [comment]
Thanks for the report! The proper place for these kind of default flags is in [`configure`](https://github.com/martanne/vis/blob/205be8532390e588bef839edc0cea2cc36b096a7/configure#L212), adding a line like:

```
FreeBSD)   CFLAGS_STD="$CFLAGS_STD -D_BSD_SOURCE -D__BSD_VISIBLE" ;;
```

should work?

@tony and @lanodan have shown past interest in vis for FreeBSD (see #195), maybe they have further comments.

**Comment by martanne** [comment]
I committed this fix for now, even though it is probably not correct/standard conforming. For the future it would be nice to determine the correct set of feature test macros.

This thread has some more information about [_BSD_SOURCE vs. __BSD_VISIBLE](http://lists.freebsd.org/pipermail/freebsd-standards/2004-March/000471.html).
