### ISSUE TITLE
suggestion: make <C-n> find matches in a circular motion

### ISSUE THREAD

**Issue by erf** [martanne/vis#305]
Suggestion: make `<C-n>` find matches in a circular motion, so that after hitting end of text, look for more matches at the beginning of the file.

**Comment by Screwtapello** [comment]
You're talking about `<C-n>` in normal mode that adds a cursor and moves to the next instance of the word, yes? Not `<C-n>` in insert mode.

**Comment by erf** [comment]
Yes
