### ISSUE TITLE
Visible lines when autoindent is enabled

### ISSUE THREAD

**Issue by vwyu** [martanne/vis#314]
I enable autoindent in an empty file, go into insert mode, press space and then press enter (`<CR>`). I would expect to have 2 visible lines on the screen, but I only see 1.  More specifically, I would expect to see the two lines and have the cursor on the second one. 

It seems that the number of visible lines in the view remain unchanged only when autoindent is used at the end of the file. I guess this issue may be related to `view_cursors_scroll_to` or `view_cursors_to`.

**Comment by martanne** [comment]
Replacing the call to [`view_cursors_scroll_to`](https://github.com/martanne/vis/blob/cd89f1c9898ae02033faab34d72f2e14981088ec/vis.c#L1141) with one for `view_cursors_to` should fix it?

If this is indeed the case I can commit a fix later tonight ...
