### ISSUE TITLE
Improve complete-word

### ISSUE THREAD

**Issue by erf** [martanne/vis#319]
I compared the new `complete word` functionality from 0cb6e49b796881cbb8b754051eae10a7151ebd99 with `vim` and here is a couple of suggestions for improvement.
- Replace current word by the first match, and don't include it in the search.
- Complete word by pressing `Space` not just `Enter`, so you don't have to create a newline char.
- Replace current word, with suggestion, each time you press `Ctrl-n`.

**Comment by martanne** [comment]
With the latest commits these issues should be fixed?

@Shugyousha I ported the improved partial substring matching from dmenu, I hope it works as expected? If you want to keep using dmenu then I would suggest to symlink `vis-menu` to it.

**Comment by erf** [comment]
The initial word is gone now and I'm able to select a word suggestion by pressing `Enter` without creating a new line, but im not able use `Space` to select a word. Also the current word ( under the cursor ) should be replaced by the current selction. And the current suggested word should rotate to the begining after the last suggestion.

**Comment by Shugyousha** [comment]
On Thu, May 19, 2016 at 10:07:33AM -0700, Marc André Tanner wrote:
> @Shugyousha I ported the improved partial substring matching from
> dmenu, I hope it works as expected? If you want to keep using dmenu
> then I would suggest to symlink `vis-menu` to it.

Works perfectly, thanks! In that case there is no need for dmenu for me.


Cheers,

Silvan

**Comment by martanne** [comment]
After using the functionality a bit, the current behavior seems fine. 

Remember the goal of the project is not to simply duplicate vim behavior. Instead try to use it in the "vis way", instead of repeatedly pressing `C-n` to cycle through completion candidates, use space separated search terms to narrow down the set of candidates.

**Comment by erf** [comment]
I still think some of these issues could be improved. Would you accept PR's?

**Comment by erf** [comment]
Oh, did not see you could continue typing in search field after `C-n` - neat!
