### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by josuah** [martanne/vis#328]
I imagined the `README.md` file, that looks to be the home page of vis, could have some logo on top, even if it is as simple as this:

![image](https://cloud.githubusercontent.com/assets/7250745/15624463/8adfec50-2488-11e6-8358-53a31ff3a806.png)

Or something more in the style of suckless.org, sta.li, or [sxiv](https://github.com/muennich/sxiv).

Or maybe as well a patchwork like your avatar.

Or none at all, I am just proposing. :)

**Comment by martanne** [comment]
I won't say no to a good looking logo. Unfortunately I probably have neither the time nor the talent to actively contribute to this. One idea would be to use something inspired by the [vis logo](https://www.vis.ethz.ch/en/services/merchandising), but I would first have to check the copyright/trademark status of it.

![vis-logo](https://forum.vis.ethz.ch/images/vis/vis_inforum_logo.png)

So yes, proposals welcome.

**Comment by sshbio** [comment]
I am not sure to have the skills neither, but I can try...  The one I took was very neutral: just a font.  The one you proposed is more fancy and colorful, so let's free our creativity!

The copyright may not be that much an issue if we take inspiration, but if the logo is being different.

**Comment by sshbio** [comment]
Here are propositions for a curve to use.  It is possible to change:
- the number of elements (here is 2 times 6, but it could be 3 times 2, or just 3...)
- the spiral/straight balance (intensity of the curve, how much should it spin)
- the thickness of each elements
- how many and how thick the tips should be split (little bars effect at the exterior of each element)
... and what not!

**Comment by sshbio** [comment]
And of course, this is just one proposition, there can be a totally different design, do not hesitate to ask. :)

**Comment by erf** [comment]
For an editor that strives to be minimalistic, i find the proposed logo too complex. I think the simple textual logo or something similar is better.

**Comment by sshbio** [comment]
@erf: I worked with big images, but this will be a logo, not a fulscreen thing.  Now that I consider this, it looks rather complex indeed.

I will make a simpler version, with less elements and see if it is better.

Maybe even ASCII art could work.

**Comment by sshbio** [comment]
Here is an image that looks a bit more like the proposition from @martanne and may be simpler:

11: 
![curve2](https://cloud.githubusercontent.com/assets/7250745/15649855/f96aece0-2674-11e6-98a7-48edb552ead7.png)

But I still keep in mind simple typography.

**Comment by sshbio** [comment]
Other editor logos:

![Jaspa nanoemacs](http://www.jasspa.com/images/nlogo.png) ![Jaspa nanoemacs](http://www.jasspa.com/images/logo.png) ![jedit](http://www.jedit.org/images/logo.png) ![elvis](http://elvis.the-little-red-haired-girl.org/images/elvis-icon.gif)

```
                   :::                         The                   
     iLE88Dj.  :jD88888Dj:                                           
   .LGitE888D.f8GjjjL8888E;        .d8888b.  888b    888 888     888 
   iE   :8888Et.     .G8888.      d88P  Y88b 8888b   888 888     888 
   ;i    E888,        ,8888,      888    888 88888b  888 888     888 
         D888,        :8888:      888        888Y88b 888 888     888 
         D888,        :8888:      888  88888 888 Y88b888 888     888 
         D888,        :8888:      888    888 888  Y88888 888     888 
         D888,        :8888:      Y88b  d88P 888   Y8888 Y88b. .d88P 
         888W,        :8888:       "Y8888P88 888    Y888  "Y88888P"  
         W88W,        :8888:                                         
         W88W:        :8888:      88888b.   8888b.  88888b.   .d88b. 
         DGGD:        :8888:      888 "88b     "88b 888 "88b d88""88b
                      :8888:      888  888 .d888888 888  888 888  888
                      :W888:      888  888 888  888 888  888 Y88..88P
                      :8888:      888  888 "Y888888 888  888  "Y88P" 
                       E888i                                         
                       tW88D
```

![New emacs logo](http://www.gnu.org/software/emacs/images/emacs.png)

This one is not an editor logo, but another image of the Vis group @martanne talked about:

![vis](https://wiki.vis.ethz.ch/img/logo.png)

By combining a modified 11 and composing it like the Vis group logo, we get something like this:

![vis curve3](https://cloud.githubusercontent.com/assets/7250745/15651027/20f51102-267d-11e6-8b59-3f6d186381c5.png)

**Comment by sshbio** [comment]
The [font](www.dafont.com/fr/nasalization.font?text=VIS) used [permits to use it for a logo](http://typodermicfonts.com/license).  It is inspired from the [old NASA logo](https://en.wikipedia.org/wiki/NASA_insignia), which I feel to fit the [galaxy shaped](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/M101_hires_STScI-PRC2006-10a.jpg/983px-M101_hires_STScI-PRC2006-10a.jpg) spiral.

**Comment by josuah** [comment]
No need to clutter the issue tracker, so closing this.

**Comment by martanne** [comment]
@josuah thanks for your effort, I will eventually come back to the Logo discussion. However, we should probably first decide if/when we want to rename the project (i.e. address #338).

**Comment by skogshjort** [comment]
Sorry for bumping a closed issue, but here is something I whipped together. The inspiration behind it is the multiple cursors. The coloring is just experimentation. The font is Fira Sans. Thank you for an promising editor! Hugs.

![](https://scontent.fbma2-1.fna.fbcdn.net/v/t1.15752-9/59914155_454154935358048_3775112988592177152_n.png?_nc_cat=102&_nc_ht=scontent.fbma2-1.fna&oh=3b4f4e07ab22f8c3b9371b4e9991b279&oe=5D603731)

**Comment by jetgogol** [comment]
My suggestion for logo design. Like you said in suckless.org style.

![VisLogo](https://user-images.githubusercontent.com/118782557/203191601-544d5185-35a0-4bcc-80fc-e480726074c8.png)

About name. I think vis should be renamed to vs. It will emphasize legacy-free conception and it faster to type. I having vs alias about 3 months and have no problems with it.

**Comment by andreisou** [comment]
![vis-logo](https://github.com/martanne/vis/assets/71538656/c26508bb-e570-4eb9-b5ba-a03c5290cb36)
My proposal for a logo. I'm by no means a professional designer and this one definitely has it's flaws. Any feedback is appreciated.

**Comment by VehementHam** [comment]
Who's won?

**Comment by VehementHam** [comment]
From the looks of the conversation, this one seems to have won (IDK):
![image](https://github.com/martanne/vis/assets/75701545/7311c0e8-0733-4b7e-97c1-e899416fe4a5)
Anyways whichever one it was, I beleive the original intent of this issue was to have the logo on the `README`.
