### ISSUE TITLE
dot repeat error

### ISSUE THREAD

**Issue by erf** [martanne/vis#334]
I was able to reproduce the dot repeat error, whilst searching for and deleting the `;` char.

Example: 
```
ihello;<Escape>yypp/;xn.
```
Result:
```
hello;
xn.;
hello;
hello
```

Expected:
```
hello
hello;
hello
```

**Comment by sshbio** [comment]
I noticed it as well.  It also occur with this shorter version here: `ihello<Escape>/l<Enter>x.` which produces this:

---
`ihello<Escape>`
```
hel
x.lo
```
---
`/l<Enter>x`
```
helo
```
---
`.`
```
hel
x.lo
```
---

So what it did is adding the step 2 and 3 input into the buffer: `l<Enter>x.`

That is: everything after the '/' key have been pressed (calling the `PROMPT_SEARCH_FORWARD` action).  Also, the editor is left in insert mode, unless I added an additional `<Escape>` key in the sequence.

Then I also tested with the `:` command, and I get the exact same issue.

So if:
1. I enter `ihello<Escape>/<Enter>`, I should be in insert mode after the dot;
2. I also add `<Escape>`, I should be back to normal mode;
3. I insert more commands, they should be interpreted as keyboard input in normal mode;

Only the 1 and 2 works all of the time.  The 3 worked not as I expected: If after 1 and 2 I enter `dd.` it acts like `i<enter><escape>dddd` (I pressed `<Enter>` to escape the empty `/` prompt).

**Comment by sshbio** [comment]
Maybe something in [`vis-prompt.c`](https://github.com/martanne/vis/blob/master/vis-prompt.c#L153-L174) is involved, as it is common to both `:` and `/` actions.

By the way, if I delete the initial `:` (with `<C-u>`), and add a `/`, I can immediately start a search query.  That is a great feature, and looks like a bit to ACME's text is executable anywhere.  It feels like a great adaptation to text-only interface.
