### ISSUE TITLE
build fails on CentOS7

### ISSUE THREAD

**Issue by WuBingzheng** [martanne/vis#335]
I try to build `vis` on CentOS 7.2, but it fails when `make`:

    /usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: relocation R_X86_64_32S against `__libc_csu_fini' can not be used when making a shared object; recompile with -fPIC
    /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: could not read symbols: Bad value
    collect2: error: ld returned 1 exit status

versions:
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)
GNU ld version 2.23.52.0.1-55.el7 20130226

**Comment by martanne** [comment]
I don't have a CentOS system at hand and therefore can't test it myself, however it seemed to work in the past.

Regarding your specific error, try removing the `-fPIE` and `-pie` flags from the `config.mk` file generated by configure.

**Comment by rickywu** [comment]
I got the same problem on latest CentOS 7

@martanne Can you test in docker container?
