### ISSUE TITLE
Allow selected or copied text to be output in the `vis -` stream editing mode.

### ISSUE THREAD

**Issue by vrthra** [martanne/vis#340]
I love the stream editing mode of `vis -`, and use it very often. I notice that very often, only particular lines in the stream are of importance to me from the text stream. Currently, I manage by inserting a `grep` ahead of `vis -`. Is there any chance vis could support a command line switch to either output the selected lines or the text in the default register?

**Comment by sshbio** [comment]
> output the selected lines or the text in the default register

If vis get text from standard input, it will write to standard output at saving, with :wq

If it there is something selected (even multiple cursors), there will only be the selection sent to standard output.  This is how it works for [dvtm](http://github.com/martanne/dvtm).

Is that what you expected?

**Comment by vrthra** [comment]
@sshbio of course, I did not realize that I had to write to stdout using :wq.

**Comment by sshbio** [comment]
No problem :)
