### ISSUE TITLE
move primary cursor independent from the other cursors

### ISSUE THREAD

**Issue by lammermann** [martanne/vis#343]
For my workflow it would be great if I could hit a shortcut and than move the primary cursor independent of the other cursors. This way I could place some cursors, make the primary cursor independent move to an arbitrary section in the text and place another cursor.
The same shortcut could be used to move all cursors again (also, all text adding, deleting, changing commands should end the independent movement).

I haven't seen this workflow elsewhere  so maybe I didn't got multiple cursors and want to use them wrongly. Does this workflow make sense to you?

**Comment by sshbio** [comment]
Most of the time, when I want to use multiple cursors, it is at places that have something in common, and most often again, I can use sam structural expressions:

1. `:x/pattern/` to place cursors at each match);
2. Filter them with `:g/pattern/` to only keep the lines that match;
3. Eventually remove the few special case that remain.

To place the cursors at specific position, I use the `t` and `f` vim commands to reach the `{` or whatever char I was targeting.

But maybe there will be some special cases that would make placing cursors by hand more convenient.

**Comment by lammermann** [comment]
Thank you very much.
I haven't read about toms cmd language before because I expected it to be just like vims cmd line. Now I'm pretty sure this will improve my workflow immensely. Could imagine there would still be some use for this kind of shortcut in special cases but for most things sams cmd lang will work out very well (even much better than manual placing)

**Comment by sshbio** [comment]
I haven't seen sam command language combined with multiple cursors elsewhere... It is really a nice feature indeed!

**Comment by mcepl** [comment]
Nobody seem to pick up on this. Do we need to keep this ticket around?

**Comment by rnpnr** [comment]
Yes I think everything here is covered already with sam. Closing.
