### ISSUE TITLE
o/O doesn't work in operator pending mode

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#345]
see title

**Comment by martanne** [comment]
Could you please provide a detailed example? Thanks

**Comment by aeosynth** [comment]
open a new file, type `i<C-o>o` . expected: a new line, got: nothing.

**Comment by aeosynth** [comment]
vis' concept of an 'operator' (at least in this mode) seems very different from vim; vis allows any number of motions, whereas vim takes only one.

**Comment by martanne** [comment]
Operator pending mode is not involved (yes the vis help text is wrong), `<Ctrl-o>` should temporarily switch to normal mode.

This was never properly implemented in vis. I suggest to remove `<Ctrl-o>` completely as it introduces unnecessary complexity for negligible gain.

Your particular use case can at least approximately be satisfied with a mapping:
```
:map! insert <C-o>o <Escape>o
```

**Comment by aeosynth** [comment]
removing `<C-o>` is fine. this issue is valid until then
