### ISSUE TITLE
`vis -v` exits with error code 1

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#351]
in bash:

```
$ vis -v
vis v0.2-329-gc61e409
$ echo $?
1
```

edit: on arch linux, built from git

**Comment by eworm-de** [comment]
This is because we use the emergency exit with `vis_die()` to print the version and exit.

Is there an easy way to implement a clean exit path without `vis_die()`? Or does it make sense to extend `vis_die()` to have an exit status?
```
void vis_die(Vis *vis, int status, const char *msg, ...);
```
The version part would look like this:
```
vis_die(vis, EXIT_SUCCESS, "vis %s\n", VERSION);
```

**Comment by eworm-de** [comment]
Answering myself (with some hints from @martanne on irc):

We call `main()` -> `vis_run()` -> `vis_args()` (where option `-v`is processed) -> `vis_die()`.

But early in `main()` (before calling `vis_run()`) we initialize ncurses with `vis_new()`. This results in three possible code pathes:
* Process the options before ncurses is initialized. We do not have to care, can print the version to terminal and exit.
* Properly uninitialize ncurses before printing version and exit.
* Take the emergency exit and let `vis_die()`do the dirty work.

Currently we do the latter. First option is desired, but requires some cleanup...
