### ISSUE TITLE
request: confirm

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#352]
[`help 'confirm'`](http://vimdoc.sourceforge.net/htmldoc/options.html#'confirm')

```
When 'confirm' is on, certain operations that would normally
fail because of unsaved changes to a buffer, e.g. ":q" and ":e",
instead raise a dialog asking if you wish to save the current
file(s).
```

i would like this option in vis, but it's not the most important thing

**Comment by martanne** [comment]
As mentioned in the referenced issue #416 I'm not a big fan of these confirmation dialogs.
