### ISSUE TITLE
realpath() is not c99

### ISSUE THREAD

**Issue by katlogic** [martanne/vis#353]
But a glibc extension. And due to missing prototype, vis will crash (cygwin/msys).

Easily fixed with -std=gnu99 (_GNU_SOURCE is apparently not enough, at least with msys). Not sure if that is optimal if c99 compliance is one of the goals.

**Comment by martanne** [comment]
The C standard isn't relevant for this. `realpath(3)` is standardized by [POSIX.1-2008](http://pubs.opengroup.org/onlinepubs/9699919799/functions/realpath.html). Earlier versions of POSIX did not specify that a buffer should be allocated in case the second argument is `NULL`. vis relies on this behavior. As for the prototype, it should be available when including `stdlib.h` and having `_XOPEN_SOURCE` defined which vis does.

In the past I tested vis with Cygwin (without msys) and it seemed to work, but this might have been before realpath was first used in 3032669cd9bf8d2a564f9eb37bc9a58bbb317314. In any case this seems to be a msys (or Cygwin) issue.

@joshaw seems to primarily use vis on Cygwin, maybe he has some insight.

I should probably also add a note to the README that besides a C99 compiler a POSIX.1-2008 environment is expected.

**Comment by joshaw** [comment]
Yes, I'm using vis almost exclusively under cygwin at the moment, and it compiles fine with the default makefile (having `./configure`'ed). Not sure what information I can give that would be helpful, but if there's anything, just let me know.

**Comment by katlogic** [comment]
Turns out this is bug was fixed few months ago (http://x.cygwin.com/ml/cygwin-cvs/2016-q1/msg00141.html). Replacing the header does the right thing. Before,  this snipped could be found in stdlib.h:

```
#ifndef __STRICT_ANSI__
_PTR    _EXFUN(reallocf,(_PTR __r, size_t __size));
char *  _EXFUN(realpath, (const char *__restrict path, char *__restrict resolved_path));
int     _EXFUN(rpmatch, (const char *response));
#endif
```

A configure check for working POSIX.1-2008 might be in order (by -Werroring realpath, as sys/features.h claims it knows about it, yet merrily ignores it), or just point out users need very recent cygwin/msys.
