### ISSUE TITLE
Configure fails on Tiny Core Linux

### ISSUE THREAD

**Issue by BinaryBen** [martanne/vis#368]
Trying to build on Tiny Core Linux as an alternative to the included vi. I am getting an error:

`line 46: syntax error: unexpected "}"`

Not sure, but it looks right to me on reviewing the code. What else could be wrong?

**Comment by martanne** [comment]
The relevant code of `configure` stems from [musl libc](http://git.musl-libc.org/cgit/musl/tree/configure#n54) and seems fine.

I don't know what shell Tiny Core Linux uses, it might be buggy?

To work around this issue you could manually provide a `config.mk` file containing the necessary make variable definitions.

**Comment by BinaryBen** [comment]
Thanks for looking martanne. TCL uses busybox. Not sure how to manually provide a config.mk, but I'll look into it.

**Comment by martanne** [comment]
Busybox contains different shells, `ash` is probably the most capable/popular one. I'm a bit surprised because busybox is often used in combination with musl and I assumed this would work. Are you on the latest version?

To manually provide the necessary make variables, just create a `config.mk` file in the build directory of vis. On my current system it looks like this:

```
# This version of config.mk was generated by:
# ./configure
# Any changes made here will be lost if configure is re-run
SRCDIR = .
PREFIX = /usr/local
EXEC_PREFIX = $(PREFIX)
BINDIR = $(EXEC_PREFIX)/bin
MANPREFIX = $(PREFIX)/share/man
SHAREPREFIX = $(PREFIX)/share
CC = cc
CFLAGS = -pipe -Os -fPIE
LDFLAGS = -Wl,-z,now -Wl,-z,relro
CFLAGS_STD = -std=c99 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -DNDEBUG -D_FORTIFY_SOURCE=2
LDFLAGS_STD = -lc
CFLAGS_AUTO = -fstack-protector-all
LDFLAGS_AUTO = -pie
CFLAGS_CURSES = -I/usr/include/ncursesw  
LDFLAGS_CURSES = -lncurses  
CFLAGS_TERMKEY = -I/usr/local/include  
LDFLAGS_TERMKEY = -L/usr/local/lib -ltermkey  
CONFIG_LUA = 1
CFLAGS_LUA = -I/usr/include/lua5.2   -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DLUA_COMPAT_ALL
LDFLAGS_LUA = -llua5.2  
CONFIG_ACL = 0
CFLAGS_ACL = 
LDFLAGS_ACL = 
CONFIG_SELINUX = 0
CFLAGS_SELINUX = 
LDFLAGS_SELINUX = 
```
You will have to adapt it to match your system.

However I would strongly suggest to resolve your shell issues, it might show up in other places too.

**Comment by BinaryBen** [comment]
Thanks Martanne, I have discovered that the error was indeed to do with the shell. I haven't been able to build it yet (errors with the dependencies), but it is at least getting past this error when I change the configure shebang to explicitly use bash (though I will try ash next). /bin/sh is symlinked to busybox which was causing problems with the `>>>` code (I think).
