### ISSUE TITLE
Deleting last sentence in a paragraph, also removes newline char

### ISSUE THREAD

**Issue by erf** [martanne/vis#369]
Not sure if this is expected behaviour but deleting the last sentence in a paragraph using `d)`, also removes the newline character after the period.

Example, given:
```
Hello world. #ello world.

Hello world. Hello world.
```
Where # is the cursor, pressing `d)`gives the following result in `vis`.
```
Hello world. Hello world. Hello world.
```
When in `vi`, the result is:
```
Hello world. 

Hello world. Hello world.
```

**Comment by martanne** [comment]
@schachmat already improved these some time ago in b4f1609e637dba2405c7c8de0dcdc86e2fac0752, maybe he could to take another look ;-)

**Comment by erf** [comment]
This behaviour seem to originate from when deleting the last word on a line, which differs from `vim`, that is if you have:
```
#ello

Hello
```
With cursor on `#` and press `dw`, in `vis` the result is:
```
Hello
```
When in `vim` the result is:
```


Hello
```
So in `vis` a `word` does not seem to end at `newline`.

**Comment by martanne** [comment]
The effect is indeed the same, however word and sentence motions are implemented completely independently. This is a different issue which was previously discussed. In vim the word motion behaves differently depending on whether it is used in combination with an operator. `w` without a previous operator moves to start of the word on the next line, whereas `dw` only deletes to the end of the line.

**Comment by schachmat** [comment]
I recommend to not follow vim in this case, since it would mean to implement different behaviours for the same operator.
