### ISSUE TITLE
Highlight 80 characters limit

### ISSUE THREAD

**Issue by adriangrigore** [martanne/vis#370]
Hey,

I was wondering if something like this is possible: http://stackoverflow.com/questions/2447109/showing-a-different-background-colour-in-vim-past-80-characters.

Thanks!

**Comment by Screwtapello** [comment]
Vis supports `:set colorcolumn 80` to highlight the background of the 80th column, just like Vim.

Unlike Vim it doesn't support a comma-delimited list of columns, just the one.
