### ISSUE TITLE
Count is skipping over insert command (i)

### ISSUE THREAD

**Issue by e3krisztian** [martanne/vis#372]
I expect the insert command

```
4i#<ESC>
```

to produce

```
####
```

however it just produces a single `#`.

Worse still:

```
0123456789
```

with cursor before `0` entering

```
4i.<ESC>d<SPACE>
```

gives

```
.456789
```

while I am expecting (checked in `vi`, `vile`)

```
...0123456789
```

When used within a macro (macro is only an insert command) the count skips over the macro. Given a macro

```
qqi.<ESC>q
```

the command

```
4@qd<SPACE>
```

gives

```
.456789
```

too.

**Comment by e3krisztian** [comment]
My `vis` version is quite old (however it is the current version on Arch linux):

    Build Date      : Sat 26 Mar 2016 11:07:54 PM CET

**Comment by martanne** [comment]
Thanks for the detailed report!

Vis does not move the cursor when leaving insert mode, apart from that your examples should now hopefully work.
