### ISSUE TITLE
Could not load lexer module, yet lpeg is installed.

### ISSUE THREAD

**Issue by polyglotCipher** [martanne/vis#378]
vis v0.2-349-g010dcd6
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
lpeg-1.0.0 as `/usr/local/lib/lua/5.3/lpeg.so`
./configure --enable-lua

Builds fine. When run displays: `WARNING: could not load lexer module, is lpeg installed?`

Possibly related:
To build I had to recompile Lua with `-fPIC` after getting an error suggesting to try `-fPIC` on vis. After some searching I found I had to do it to Lua instead.

**Comment by polyglotCipher** [comment]
Maybe there is an issue with the way I am installing lpeg. I am not using the package the would normally be downloaded from apt in Mint (the distribution I am using). I am manually compiling version 1.0.0 as listed above directly from the source code provided in the lpeg website. Additionally, I ran the ```test.lua``` script that is included with lpeg and it passes fully in any directory.

**Comment by Shugyousha** [comment]
What are the LDFLAGS_LUA in config.mk when you are compiling vis?

I may be wrong, but I think it's likely that you are linking to the wrong lua version when compiling vis. The lua version you are linking to is not the same one for which you have installed the lpeg package (so it links to a lua version other than 5.3 for which you have installed the lpeg package).

**Comment by polyglotCipher** [comment]
```-llua -lm -ldl```

I checked ```/usr``` and ```/usr/local```, I only have Lua 5.3.3 binaries and directories. In vis, ```:h``` only lists the 5.3 version of the lua directories.

**Comment by martanne** [comment]
The `:help` output only lists the package paths for Lua files. In practice they will most likely be the same as for Lua C modules except for the different file extension. Printing `package.cpath` from the vis startup script should give you the exact search paths.

Even simpler, just modifying `visrc.lua` to load the (seemingly missing) lpeg module without any error handling around it, should open a new window with a "stack trace" indicating all file names which have been tried.

You mentioned that you compiled Lua yourself, by default Lua does not include the release number (3rd version component) in its default C path (grep for the `LUA_CPATH_DEFAULT` define in the Lua source). So you either have to override this while compiling or place an appropriate symlink in your directory structure (`5.3 -> 5.3.3`).

**Comment by polyglotCipher** [comment]
I couldn't figure out how to `print package.cpath` and actually being able to see it.

Putting `require('lpeg')` at the top of `visrc.lua` gets me this when I run vis:
```
error loading module 'lpeg' from file '/usr/local/lib/lua/5.3/lpeg.so':
        /usr/local/lib/lua/5.3/lpeg.so: undefined symbol: lua_gettop
```
Also,
```
#define LUA_CPATH_DEFAULT \
		LUA_CDIR"?.so;" LUA_CDIR"loadall.so;" "./?.so"
```
where are you wanting me to add `.3`? I don't think vis is having any trouble finding the file. I also doubt releases are ever separated by patch number.

**Comment by martanne** [comment]
> I couldn't figure out how to print package.cpath and actually being able to see it.

The idea is to do something like `vis > log && cat log` or for short messages replacing the Lua `print(...)` function with `vis:info(...)` should also work.

As of commit 47e82949164c23973dbad72d3982d9aef557d118 the `package.cpath` is also displayed at the end of the `:help` output.

In any case you seem to have a mismatch between the used Lua and LPeg versions. This is not a vis related issue.
