### ISSUE TITLE
Map Semicolon to Colon in visrc

### ISSUE THREAD

**Issue by codri** [martanne/vis#379]
Hi,

I would like to map ";" to ":". I've tried to add this to the visrc.lua file, and it doesn't work.
Is this possible?

```lua
require('vis)

vis.events.win_open = function(win)
   vis:command('map normal ; :')
end
````

**Comment by josuah** [comment]
I think it requires quotes, like that: `map normal ";" ":"`

So

```lua
require('vis)

vis.events.win_open = function(win)
   vis:command('map normal ";' ":"')
end
```

**Comment by codri** [comment]
thank you for the suggestion @josuah, tried it, and unfortunately it doesn't seem to work.

**Comment by martanne** [comment]
The quoting is fine, the problem is that there already exists a mapping for `;` hence you need to force the map command by specifying `!`. Also global mappings should probably be placed into the `start` event, there is no need to set them for each new window.

```lua
vis.events.start = function()
        vis:command('map! normal ; :')
end
```

**Comment by codri** [comment]
Thank you @martanne , the `!` did the job. And thank you for the tip about the start event.
