### ISSUE TITLE
Autommands - Implemented as a plugin

### ISSUE THREAD

**Issue by codri** [martanne/vis#380]
Autocommands are essential for my vim workflow.
Is it possible to recreate them with a plugin?

**Comment by josuah** [comment]
There are already some hooks that does the same thing.  At the moment there are a very few.

You can see them at [Lua API for in-process extension](https://github.com/martanne/vis#lua-api-for-in-process-extension) of the REAME.

**Comment by codri** [comment]
I've had a look at the list. Can't find the events for opening an event for file open/save/close.
I used autocommands to run some tools on save, there doesn't seem to be an event for file save.


Copied from documentation:

events hooks:
- start()
- quit()
- win_open(win)
- win_close(win)
- theme_change(name)

**Comment by josuah** [comment]
This would have been convenient indeed... Maybe it is not a lot to add: In the C source code, right after opening a file, make a call to a lua function using the lua C API.

**Comment by martanne** [comment]
Hi, the following 3 additional events are now exposed through the Lua API:

* `file_open(file)`
* `file_save(file)`
* `file_close(file)`

Is this good enough for your purpose? The "plugin" interface is still rather young, suggestions for API improvements can also be posted to issue #292.

**Comment by codri** [comment]
@mar
