### ISSUE TITLE
Inconsistent `r` behaviour when langmap is used

### ISSUE THREAD

**Issue by lxyd** [martanne/vis#382]
Hi!
Langmap is superb, but I have some issues with it.

Please, try the following:
1. Register Russian letter 'к' as equivalent to 'r' ```:langmap к r```
2. Enter some text, for example: ```мошка```
3. Return to normal mode and change keyboard layout to Russian
4. Try to replace the Russian 'м' letter with Russian 'к' letter by typing ```кк```
5. See the result: ```rошка``` (notice the English 'r' instead of Russian 'к')

From the user's perspective, second letter is an argument for the `r` command and should be entered in the current keyboard layout, but it is langmapp'ed too. So, it's impossible to replace a letter with another letter which is non-latin and has a langmap mapping.

This issue seems to be hard to solve because in similar situation some bindings should be translated both, for example ```пл```(```gk```), but I think, you should know about it.

**Comment by martanne** [comment]
Hi, thanks for the report! I haven't actually tested it with Russian, but I think it should work now?

**Comment by lxyd** [comment]
Yeah, it works! Thank you )

But I noticed one another thing: `dd` is not working when langmapped (don't know if it was working earlier).

**Comment by martanne** [comment]
`dd` should now also work, the language map was ignored for operator pending mode.

@xomachine originally proposed the feature, maybe he encountered other issues which should be fixed?

**Comment by lxyd** [comment]
Yes, `dd` is working now. But… Well, yet another one popped up :) Now with non-latin command_register.
Opened a separate issue #387 for it, because it is not related with langmap.
