### ISSUE TITLE
Cannot register non-latin command via vis:command_register

### ISSUE THREAD

**Issue by lxyd** [martanne/vis#387]
I'm trying to register a Russian synonym command for `q` (langmap shouldn't be involved in this situation):
```
  vis:command_register('й', function(argv, force, win, cursor, range)
    vis:command('q')
  end)
```

But the registered command does not work. Vis seems to be aware of the registered command (it doesn't show `Unknown command` message), but it just does nothing when the command is invoked. Registering Latin command (for example `qqq`) works fine.

**Comment by martanne** [comment]
Ok, while it should now be possible to register non-latin command names. Your "aliasing" code is incomplete and depending on the used command potentially dangerous. You don't pass on the force variable i.e. whether the command was executed with a `!`. While this could be fixed, there is no way to pass on the range to which the command should apply.

**Comment by lxyd** [comment]
It is now working, thank you again :)
I just wanted aliases for `q`, `w` and `wq` as most frequently used ones. No fancy ranges needed.
And ok, got it about the `!` mark.
