### ISSUE TITLE
consider gazelle for parsing

### ISSUE THREAD

**Issue by nwmcsween** [martanne/vis#4]
https://github.com/haberman/gazelle

**Comment by martanne** [comment]
Do you know what the current project status is? It doesn't seem to be that actively developed.

I'm considering switching to a [Parsing Expression Grammar](https://en.wikipedia.org/wiki/Parsing_expression_grammar) based approach, more concretely a [lua based implementation](http://www.inf.puc-rio.br/~roberto/lpeg/). See #81 for details.
