### ISSUE TITLE
Customize special white space replacement symbols

### ISSUE THREAD

**Issue by yblein** [martanne/vis#401]
I really like displaying special white space characters with replacement symbols but the `▶` for tabs is a bit heavy. (Instead, I'm used to `›` which I find much nicer).
The current symbols are hardcoded in the array [`symbols_default`](https://github.com/martanne/vis/blob/5aa0a68d3d5af745b97ddec576f0bbfbe18ed2ab/view.c#L105). Could we expose a configuration function to Lua so that we can customize these symbols?

**Comment by martanne** [comment]
As a short term solution I can change the default symbols. In the long term it might make sense to move more of the drawing code to Lua and enable it to modify the text representation. This approach would be a lot more flexible and might allow us to implement stuff like: #384, #370 and #342 in Lua.
