### ISSUE TITLE
Mappings with Meta-key do not work when langmap is active

### ISSUE THREAD

**Issue by lxyd** [martanne/vis#404]
Hello again! Yet another langmap-related issue found :)

Please, try the following:

1. Register `M-k`, for example:
    ```
    map normal <M-k> 10<cursor-screenline-up>
    ```
2. Create langmap with `k`:
    ```
    langmap л k
    ```
3. Change keyboard layout and try to use `M-л` for cursor moving

**Comment by martanne** [comment]
I haven't actually tested it much, feel free to reopen if there is still a problem ...

**Comment by lxyd** [comment]
Well, things become even worse: now langmap'ed keys cause random movements and also garbage appears in command line when I press `ж` langmapped to `:`. Seems like vis is now trying to langmap some characters in `<cursor-screenline-up>` string or something.

**Comment by martanne** [comment]
Try again, was a light night coding screw up.

**Comment by lxyd** [comment]
Perfect! Thank you )
