### ISSUE TITLE
Pressing Esc and then a movement key starting at insert mode, prints <M-key_pressed>

### ISSUE THREAD

**Issue by josegl** [martanne/vis#415]
If you are in insert mode, press the `esc` key and intermediately after pressing the `esc` key press another key, it's like if it doesn't have time enough to leave the insert mode, and it writes `<M-key_pressed>`. If you wait a little since you press the `esc` key, it works as it should.

**Comment by martanne** [comment]
After e9f28e98dd09a444fe5ce8a149745e08f9d4228e you should be able to configure the used delay at run time. In your case a shorter delay than the default of 50ms might help. Are you using a terminal multiplexer? These induce an additional delay, which has to be configured independently.

**Comment by josegl** [comment]
Yes I use both abduco and dvtm. when I run an abduco session, it automatically runs dvtm without arguments AFAIK. I've done some test and changing the delay to 10 ms both in dvtm and vis it is more usable so far.

Thank you for your help.

**Comment by martanne** [comment]
I'm not sure we can do better than providing settings to change the used default timeouts. I'm closing this for now.
