### ISSUE TITLE
Running shell commands from the : prompt

### ISSUE THREAD

**Issue by larryhynes** [martanne/vis#416]
When I issue a `:! pwd` or `:! ls` I would expect to see the output of that command, possibly with a vi-style 'Press return'. Instead I see nothing. Am I missing something here, or what is the expected behaviour of running a shell command?

**Comment by josuah** [comment]
Maybe vis does not wait for the user to press return and then redraw immediately after the end of the command:

- Vis starts the command which prints its output;
- The control comes back to vis;
- It clears the screen which overwrite the command output.

**Comment by Shugyousha** [comment]
On Wed, Nov 23, 2016 at 01:20:03PM -0800, Josuah Demangeon⠠⠵ wrote:
> Maybe vis does not wait for the user to press return and then redraw
> immediately after the end of the command:
> 
> - Vis starts the command which prints its output;
> - The control comes back to vis;
> - It clears the screen which overwrite the command output.

That's what I remember vis doing as well. Not sure what would be the
best way to handle it (or even if it should be handled).

**Comment by larryhynes** [comment]
From the help:

```
:-Commands
! shell-command                Run the command
```

So it is supposed to be handled, in some fashion. Or I've completely misunderstood its intention. (Which is very possible; I am mentally feeble, and quite old.) Run the command where? Do what with the output of the command?

**Comment by Shugyousha** [comment]
On Thu, Nov 24, 2016 at 12:01 AM, larryhynes <notifications@github.com> wrote:
>
> From the help:
>
> :-Commands
> ! shell-command                Run the command
>
> So it is supposed to be handled, in some fashion. Or I've completely misunderstood its intention. (Which is very possible; I am mentally feeble, and quite old.) Run the command where? Do what with the output of the command?

The command *is* run so we handle that just fine :) What I meant is,
if we should show the output of a command started that way and wait
for user input to redraw vis. We could try to only wait for user input
before redrawing if the command produced some output (and not only
side effects) *or* if the command produced some output on stderr, etc.

Vim waits for user input before redrawing even when you just run ":!".
I think the simplest and most useful way to handle this is to just
return when running a shell command (like we do now) *but* to allow
people to pipe output to  pagers (like 'less') if they want to see the
output (that does not work in vis for some reason (we are not spawning
a shell, maybe?) but I am not sure I will have time to look into the
code to see why that is at the moment.

**Comment by martanne** [comment]
There are multiple issues in play here: the question of how to display command output and some unrelated bugs in the redirection mechanism of the relevant I/O commands.

A few general comments regarding the former:
* I don't particularly like introducing these user confirmation prompts, this also applies to #352.
* If you wan't to interact with an interactive shell command another option is to use job control i.e. press `<C-z>` to suspend vis do whatever you want, come back with `fg`.

As for the `:` commands, there are a couple different use cases which all more or less go through the same code path but with different redirections and file ranges:
 *  `|` filters range: active range -> stdin, stdout -> replaces text range, stderr -> first line diagnostic output to user
 * `<` replace range with output of command, if command doesn't use its stdin this is equivalent to `|`: empty range -> stdin, stdout -> replaces text range, stderr -> user message
 * `>` pipe text to command, ignore its output: range -> stdin, stdout -> /dev/null (not literally, but we ignore it, this is actually another bug we should not block attempting to read from it for example when a long running background process is started), stderr -> user message
 * `!` run interactive commands: keyboard input stdin -> stdin, stdout -> stderr (this is currently not the case and part of the reason why no output is shown), stderr -> stderr

Fixing stdout redirection for `!` should allow commands like `:!/bin/sh` (currently the output is not displayed). However, this will break anything using `vis-menu(1)`  i.e. the file open dialogs `:spl .`, as well as filename `<C-x><C-f>` and word `<C-n>` completion in insert mode etc. The reason being that the interactive menu is currently launched similar to a `!` command, but with additional input piped to it. If stdout no longer points back to vis then we can't read out the selection. The correct solution would be to start `vis-menu` as a filter and let it re-open stderr itself (as it already does for stdin). This would probably also obsolete the `interactive` flag currently passed to `vis_pipe`, instead an invalid range would be enough to signal interactive mode.

**Comment by Shugyousha** [comment]
On Thu, Nov 24, 2016 at 12:28 PM, Marc André Tanner
<notifications@github.com> wrote:
> There are multiple issues in play here: the question of how to display
> command output and some unrelated bugs in the redirection mechanism of the
> relevant I/O commands.
>
> A few general comments regarding the former:
>
> I don't particularly like introducing these user confirmation prompts, this
> also applies to #352.
> If you wan't to interact with an interactive shell command another option is
> to use job control i.e. press <C-z> to suspend vis do whatever you want,
> come back with fg.

Personally, I agree with you here. I don't like confirmation dialogs
when they are not strictly necessary and if you want to see the output
of a shell command you can

1. either use job control (as you mentioned) or
2. use another terminal emulator to run the command or
3. read the output of your command into your file in vis using :< (and
then undo the change again with 'u')


> As for the : commands, there are a couple different use cases which all more
> or less go through the same code path but with different redirections and
> file ranges:
>
> | filters range: active range -> stdin, stdout -> replaces text range,
> stderr -> first line diagnostic output to user
> < replace range with output of command, if command doesn't use its stdin
> this is equivalent to |: empty range -> stdin, stdout -> replaces text
> range, stderr -> user message
>> pipe text to command, ignore its output: range -> stdin, stdout ->
>> /dev/null (not literally, but we ignore it, this is actually another bug we
>> should not block attempting to read from it for example when a long running
>> background process is started), stderr -> user message
> ! run interactive commands: keyboard input stdin -> stdin, stdout -> stderr
> (this is currently not the case and part of the reason why no output is
> shown), stderr -> stderr
>
> Fixing stdout redirection for ! should allow commands like :!/bin/sh
> (currently the output is not displayed). However, this will break anything
> using vis-menu(1) i.e. the file open dialogs :spl ., as well as filename
> <C-x><C-f> and word <C-n> completion in insert mode etc. The reason being
> that the interactive menu is currently launched similar to a ! command, but
> with additional input piped to it. If stdout no longer points back to vis
> then we can't read out the selection. The correct solution would be to start
> vis-menu as a filter and let it re-open stderr itself (as it already does
> for stdin). This would probably also obsolete the interactive flag currently
> passed to vis_pipe, instead an invalid range would be enough to signal
> interactive mode.

Nice analysis and overview! You will have to decide which approach you
want to take.

**Comment by larryhynes** [comment]
FWIW I'm not agitating for a confirmation dialog, it was mentioned simply as part of what one might expect when running a shell command in a vi-like editor. (Running `!ls` in `sam -d`, or `ed` just prints the output, there is no confirmation dialog.) So we can park that, at least insofar as it relates to my query.

I'm aware of, and use, `< > |`. I'm not in any doubt as to what they do or how they function. So we can put those out of sight.

And so we return to `!`. I'm not even sure that I *want* to see the output of `:! ls`, but given that we're saying

```
! shell-command                Run the command
```

isn't there an entirely reasonable expectation that I *would* see the output?

> The command *is* run so we handle that just fine :)

If I run a command, and that command has output, I sort of expect to see that output as part of accepting that the command "is run". i.e. is  an `ls` command that doesn't return any output, really an `ls` command? (We're getting into "if a tree falls in a forest..." territory here, but still.)

Now, if I enter `:! /bin/sh`, or `:!/bin/mksh`, things take another turn for the unexpected. I leave vis and get a shell prompt, but that's it; no commands appear to be available to me (e.g. `ls` returns nothing, as does `/bin/ls`, and `which ls`, etc.). `exit` bring me back to vis.

So now that I have some grasp on what `!` doesn't do, I suppose I'm questioning the inclusion, and the meaning, of 

```
! shell-command                Run the command
```

in the help. The reality of running `! shell-command` is, in my experience, quite different to what one might reasonably expect.

**Comment by martanne** [comment]
@larryhynes I wasn't dismissing the issue you raised, my last comment simply tried to summarize the different modes of operation which the `vis_pipe` function has to support. In doing so we diagnosed two problems: 1. stdout of interactive commands was wrongly redirected (causing part of the display problem), 2. output streams which the consumer has no interest in were not redirected to `/dev/null`. Both of these were hopefully fixed with the latest commits.

As a result `:!/bin/sh` should now work as expected?

This leaves us with the user interface issues. The problem is that vis immediately redraws itself over the command output as described in the first comment by @josuah. For commands like `:!pwd` it would probably make sense to display the output in a new empty file/window i.e. it would be an alias for:
```
:new
:<pwd
```
This of course is not the right behavior for interactive commands like `:!/bin/sh`.
As already mentioned there are other options available (job control, `:<` and undo etc) to see command output, this is good enough for my use cases. Personally I think `:!` is simply the wrong tool for what you want.

However, I'm always open for improvement suggestions. Also feel free to propose better help texts.

**Comment by Earnestly** [comment]
I was testing using these commands for tools like `shellcheck` and while I had some success it required a bit of inelegance.

In a deliberately broken shell script I ran `:|shellcheck "$vis_filepath"` only to be told that the `Command failed`.  I was a bit confused by this because of course the command is going to exit non-zero.

In a roundabout of thinking I realised vis may be suppressing output (even stdout) if the command terminates non-zero, and the workaround I threw at it was `:|shellcheck "$vis_filepath" || true` and behold it worked.

I greatly benefit from tools like shellcheck, various static analysers and other lint checkers to make up for my flaws of being human, but vis is making it slightly unobvious as to how this can be done nicely (either via inline annotation like vim's wonderful `:makeprg` or producing a `:new` buffer displaying the issues).

Sorry if I'm missed the important documentation but how is such a usecase expected to be handled?

*PS: Does vis have a way to express something like vim's `<cfile>`?*

**Comment by raphael-proust** [comment]
The command `:!pwd | less` does work here and provides a user confirmation.

**Comment by mcepl** [comment]
> |shellcheck "$vis_filepath"

This is almost certainly wrong. Didn’t you want `!shellcheck “$vis_filepath”` instead (exclamation mark instead of pipe)?

**Comment by Archargelod** [comment]
I prefer to use `! <command>; read`.
It executes the command, incrementally displays the output and then wait for Enter or EOF (Ctrl-d).
