### ISSUE TITLE
can't use terminal fg/bg colors since moving theme code to lua

### ISSUE THREAD

**Issue by gvvaughan** [martanne/vis#425]
prior to commit e29a0da9deef521694247421e, I was able to use:

```lua
lexers.STYLE_DEFAULT = ''
```

And vis would use the default bg and fg colors from my terminal - super useful for me because I flip my terminals between solarized light and dark, and could  use the same vis theme for both.

Similarly, the colors used in vis' solarized background don't match the Terminal.app solarized theme background, which makes the terminal appear to flash when suspending and resuming vis.

Can we please retain support for terminal default colors somehow? (or if it is still possible, please mention how in the docs somewhere)

Thanks for an awesome (and Lua!) editor... I use it every day :-)

**Comment by martanne** [comment]
Are you sure it is using the theme file you expect? Try to add a `vis:info("HERE I AM")` at the end of the theme file and check whether it is reached.

**Comment by gvvaughan** [comment]
Yep... I have my themes in `~/.config/vis/themes/` and select it from `~/.config/vis/visrc.lua` with `vis.events.theme_change('solarized-terminal')`.

Adding the info call you suggest to the end of my visrc.lua echos "HERE I AM" into the command area on startup.

**Comment by gvvaughan** [comment]
oops: s/end of visrc.lua/end of solarized-terminal.lua/

**Comment by martanne** [comment]
I tried it with [st](http://st.suckless.org) and the [solarized patch](http://st.suckless.org/patches/solarized) with the following vis theme changes:
```
lexers.STYLE_DEFAULT = ''
lexers.STYLE_NOTHING = ''
```
It seems to work fine here. In the meantime a lot of files have been shuffled around and the theme setting code also slightly changed (adapt your `visrc.lua` file accordingly). Give it another try?

**Comment by gvvaughan** [comment]
Yes, that works perfectly again  now :-)
