### ISSUE TITLE
[discussion] Why both libtermkey and libncurses?

### ISSUE THREAD

**Issue by josuah** [martanne/vis#428]
I am only asking because I am curious.

Unlike libncurses, libtermkey is rarely pre-installed on a system, and everything could have been done with libncurses.

Is [that](http://www.leonerd.org.uk/hacks/vim/fixtermkeys.html) the reason ?  With libtermkey the way to go as libncurses can not evolve anymore ?

If one had to start a whole new project, would you recommand [libtickit](http://www.leonerd.org.uk/code/libtickit/) ?  There was a depcrecation notice on the [libtermkey page](http://www.leonerd.org.uk/code/libtermkey/) pointing at libtickit as a replacement.

**Comment by aeosynth** [comment]
libtermkey is deprecated, but libtickit is not ready to replace it + curses:

https://github.com/neovim/neovim/pull/5556#issuecomment-258500203

> Ultimately this entire behaviour would become a lot simpler in neovim if it just used libtickit to handle terminal IO; though I'm aware it's not quite ready for that yet.

**Comment by erf** [comment]
@josuah see #250

**Comment by josuah** [comment]
Thanks you for pointing me out these issues.  Got plenty to read now.  :)
