### ISSUE TITLE
error when no theme is set

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#429]
```
/usr/local/share/vis/vis-std.lua:22: bad argument #2 to 'style_define' (string ex
pected, got nil)
```

when no theme is set in `visrc.lua`, a default theme should be set, instead of giving an error

**Comment by xcko** [comment]
On vis v0.2-544-g5b689ba I don't have this problem with the default visrc.
I find the visrc changes frequently between updates, have you updated versions recently?

**Comment by aeosynth** [comment]
i'm using the latest git: e1beca0

**Comment by xcko** [comment]
This is what is in my system visrc that handles setting the theme. 
`vis.events.subscribe(vis.events.INIT, function()`
	`-- Your global configuration options`
	`--vis:command("set theme ".. (vis.ui.colors <= 16 and "default-16" or "default-256"))`
`end)`
The vis man page also mentions that it will source the first visrc found, maybe this section is missing in your visrc? Or have I totally misunderstood your bug, and you're saying this shouldn't be needed at all in the visrc?

**Comment by aeosynth** [comment]
try building the latest git. with your commented out `set theme`, vis should show the error. i don't know which git commit your version relates to.

**Comment by aeosynth** [comment]
@martanne the cursor is not visible now when no theme is set
