### ISSUE TITLE
Storing undo history to disk

### ISSUE THREAD

**Issue by erf** [martanne/vis#43]
I understand the algorithm already supports infinite undo history, but are you planning on adding support for saving this history to disk, so you can undo/redo if you open a file later?

**Comment by martanne** [comment]
No at the moment I have no plans to do so.

**Comment by erf** [comment]
Ok - I'll close this issue then.

**Comment by dirkson** [comment]
+1 for this feature. I can no longer imagine switching to an editor without this feature, no matter how much I like its list of non-goals.
