### ISSUE TITLE
Move c files to src folder

### ISSUE THREAD

**Issue by erf** [martanne/vis#438]
Suggestion: move all `.c` and `.h` files to `src` folder for a cleaner root folder.

**Comment by martanne** [comment]
Why? Developers should get easy access to the source. The only advantage I can think of is a less cluttered github landing page (because the file list is shorter). If we did proper marketing we would probably have our own homepage anyway ...

**Comment by erf** [comment]
"less cluttered github landing page" was my initial thought as well
