### ISSUE TITLE
substituting lines behaviour

### ISSUE THREAD

**Issue by erf** [martanne/vis#440]
I would prefer `vim`'s behavour when substituting lines of text, that is to leave the cursor on a new line with the same indentation. This makes it easier to continuing typing or pasting new content.

If you have the following in `vim`:
```
function someFunc()
     hello
     world
end
```
Selecting the lines with `hello world` and pressing `s`, will leave the cursor at `#`.
```
function someFunc()
    #
end
```
In `vis`, the result is:
```
function someFunc()
#nd
```

**Comment by martanne** [comment]
Doesn't seem to work in the vim I have currently access to.

Won't happen in vis core, write a Lua script to do what you want.

**Comment by erf** [comment]
I got it working using the following keymapping:
```
	vis:command("map! visual-line s dO")
``
