### ISSUE TITLE
vis is available for gentoo

### ISSUE THREAD

**Issue by lanodan** [martanne/vis#441]
I have vis in my overlay for quite some time now, and my overlay is in the official list.
You can see it here: https://gpo.zugaina.org/app-editors/vis

**Comment by josuah** [comment]
Thank you!

There is an [ongoing thread](https://github.com/martanne/vis/issues/338) about a potential name change for vis, to avoid name clash.  Maybe you want to keep an eye on this.

**Comment by lanodan** [comment]
Well renaming the atom aka package would probably breaks few thing, but isn’t a real issue and there should not be an atom name conflict (thanks to gentoo’s categories)

**Comment by josuah** [comment]
This make things easy in this kind of situation.

**Comment by lanodan** [comment]
Bug report for inclusion in official git repo : https://bugs.gentoo.org/show_bug.cgi?id=613820

**Comment by martanne** [comment]
The release was finally tagged, feel free to update [packaging related information on the wiki](https://github.com/martanne/vis/wiki/Distribution-Packages).

Thanks!
