### ISSUE TITLE
Add sam address for what-you-see-on-screen

### ISSUE THREAD

**Issue by erf** [martanne/vis#451]
Suggesion: 
Add a special sam address / range character for matching with content in the current view.

I did the following to select all lines in view ( which would have been easier if `Window.viewport` had a `line_start` and `line_finish` ):
```
	function select_inside_view(args)
		local v = win.viewport
		local p = win.cursor.pos
		win.cursor.pos = v.start
		local l0 = win.cursor.line
		win.cursor.pos = v.finish
		local l1 = win.cursor.line
		win.cursor.pos = p
		--vis:info(string.format('viewport l0 %d l1 %d', l0, l1))
		local s = string.format(':%d,%dx', l0, l1)
		vis:command(s)
	end
	
	vis:command_register('xi', select_inside_view)
```
However, i am not aware of a way to append a pattern or other commands after this, maybe you should be able to register commands with patterns, in addition to simple names?

**Comment by martanne** [comment]
Not 100% sure what you want, but something like the following might work:

```Lua
vis:map(vis.modes.NORMAL, "Q", function()
        local win = vis.win 
        if #win.cursors > 1 then 
                vis:info("More than 1 cursor exists")
                return 
        end 
        win.cursor.selection = win.viewport
        vis.mode = vis.modes.VISUAL; 
        vis:feedkeys(":"); 
end, "Select viewport") 
```
