### ISSUE TITLE
Missing digraphs feature

### ISSUE THREAD

**Issue by KolesnichenkoDS** [martanne/vis#460]
In Vim I can use `<C-k>` shortcut in insert mode to insert special characters ([digraphs](http://vimdoc.sourceforge.net/htmldoc/digraph.html)):

```viml
<C-k>l*    " for λ
<C-k>FA    " for ∀
<C-k>(-    " for ∈
```

**Comment by joshaw** [comment]
I think this would be best implemented in lua as a plugin, it's basically
just a long list of mappings all sharing the `<C-k>` prefix.

On 15 Jan 2017 3:46 pm, "Daniil Kolesnichenko" <notifications@github.com>
wrote:

In Vim I can use <C-k> shortcut in insert mode to insert special characters
(digraphs <http://vimdoc.sourceforge.net/htmldoc/digraph.html>):

<C-k>l*    " for λ<C-k>FA    " for ∀<C-k>(-    " for ∈

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/martanne/vis/issues/460>, or mute the thread

**Comment by martanne** [comment]
With the latest changes something like the following should work:

```Lua
vis:map(vis.modes.INSERT, "<C-k>", function(keys)
        if #keys < 2 then
                return -1 -- need more input
        end
        local digraph = keys:sub(1, 2)
        if digraph == "l*" then
                vis:feedkeys('λ')
                return 2 -- consume 2 bytes of input
        end
end, "Insert digraph")
```
How to (space) efficiently store and lazy load the diagraph table upon first use is left as an exercise for the reader.

However, it might make more sense to implement this as a standalone utility which can be used from multiple applications. It would get the digraph as argument and print the corresponding symbol to stdout. I believe such a tool was once posted to the suckless mailing list, I will have to check my mail archive.

**Comment by josuah** [comment]
This is what I found about digraphs on suckless.org mailing list archives: https://duckduckgo.com/?q=digraph+site%3Ahttp%3A%2F%2Flists.suckless.org%2Fdev%2F&t=fpas&ia=web

> ^Au
> echo "bind u digraph 'U+'" >>~/.screenrc

They talked about a screen command in this case and not a whole program.

I can not promise a lot, but I could try to propose some very basic digraph program with someheader with:

``` C
struct digraph *digraphs[] = {
        { .digraph = "pp", .content = "¶" },
        { .digraph = "*p", .content = "π" },
        ...
}
```

It could be used for dvtm as well.

**Comment by martanne** [comment]
It would probably be easiest to follow the format of RFC1345 and write a script to generate the corresponding C table.

```C
#include <locale.h>
#include <stdio.h>
#include <string.h>
#include <wchar.h>

typedef struct {
	const char name[2];
	const wchar_t code;
	const char *description;
} Digraph;

static const Digraph digraphs[] = {
	/* TODO: - write script to generate table from RFC 1345
	 *         https://tools.ietf.org/html/rfc1345
	 *       - write manual page
	 */
	{ "L*", 0x039b, "GREEK CAPITAL LETTER LAMDA" },
	{ "FA", 0x2200, "FOR ALL" },
	{ "(-", 0x2208, "ELEMENT OF" },
	{ { 0 }, 0, NULL },
};

int main(int argc, char *argv[]) {
	setlocale(LC_ALL, "");

	wchar_t codes[argc-1];
	memset(codes, 0, sizeof(codes));
	
	for (int i = 1; i < argc || (i == 1 && argc == 1); i++) {
		for (const Digraph *d = digraphs; d->name[0]; d++) {
			if (argc == 1) {
				wprintf(L"%s %lc %s\n", d->name, d->code, d->description);
			} else if (strcmp(argv[i], d->name) == 0) {
				codes[i-1] = d->code;
				break;
			}
		}
		if (i < argc && !codes[i-1]) {
			fprintf(stderr, "Unknown digraph: `%s'\n", argv[i]);
			return 1;
		}
	}

	for (int i = 0; i < argc-1; i++)
		putwchar(codes[i]);
	return 0;
}
```

Not sure whether we care about binary size (probably not in this case) or if using `wchar_t` and the locale system (or just always outputting UTF-8) is a good idea.

Also not really tested.

**Comment by josuah** [comment]
I came up with this script, which will work only for the set of digraphs in the rfc in text format: https://tools.ietf.org/rfc/rfc1345.txt

``` sh
# remove the page breaks by seeking '\f' characters (shown '^L' in less).
awk -v RS='\n\n[^\n]*\n\f\n[^\n]*\n\n\n' '{ print; }' rfc1345.txt |

# extract the relevant section
sed -n '/^4\.  CHARSETS$/,$ d; /^ SP /,$ s/^ // p' |

# join back the split lines
awk '{
	if ($0 ~ /^               /) {
		trail = $0
		gsub(/^ */, "", trail);
		print last " " trail;
	} else if (last !~ /^               /) {
		print last;
	}

	last = $0;
}' |

# transform the output into a C header
sed -r 's/^(..[^ ]*) +([0-9a-f]{4}) +(.*)/\t{ "\1", 0x\2, "\3" },/' |

# escape the '"'
sed 's/ ""/ "\\"/; s/"",/\\"",/'
```

The script is available here: [rfc1345.sh](https://github.com/martanne/vis/files/733044/rfc.txt)
Output: [out.txt](https://github.com/martanne/vis/files/733060/out.txt)


There is a caveat, though: there are lines with more than two characters per digraphs, such as

```
...
{ "D->", 0x1e12, "LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW" },
{ "d->", 0x1e13, "LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW" },
{ "E-!", 0x1e14, "LATIN CAPITAL LETTER E WITH MACRON AND GRAVE" },
{ "e-!", 0x1e15, "LATIN SMALL LETTER E WITH MACRON AND GRAVE" },
{ "E-'", 0x1e16, "LATIN CAPITAL LETTER E WITH MACRON AND ACUTE" }
...
```

**Comment by josuah** [comment]
The binary is only 108K while compiled with gcc.

UTF-8 output is not a problem for me.  Localized, single-bytes characters encoding will not be able to display most of the runes.

In future, if requested, it is still possible to add more options.

**Comment by martanne** [comment]
Thanks, the longest sequence seems to be `1000RCD`.

I assumed that the symbols are always exactly 2 bytes long. Apparently that is not the case. Handling those longer symbols correctly would be easier if the data were available in Lua (because we could look up whether the current input keys are a valid prefix of a symbol).

If we still want to use a standalone utility, we could let it terminate with exit code 2 in that case. 

> It could be used for dvtm as well.

Do you have a particular usecase in mind?

**Comment by josuah** [comment]
`digraph` could also handle the keyboard input itself, setting tty in raw mode.
Inserting a digraph would be as simple as calling `digraph` command like what is done for `vis-open`, and then inserting its output in the buffer.

I imagined dvtm to call digraph on some key and insert the output in a similar way to `Mod + p`.

**Comment by martanne** [comment]
> digraph could also handle the keyboard input itself, setting tty in raw mode.

The problem with that approach is that the last insertion will no longer be repeatable with `.`

Anyway I have updated the [code of my post above](https://github.com/martanne/vis/issues/460#issuecomment-275426869) which should now be capable to do both. Compiling the file and placing the resulting binary as `vis-digraph` somewhere in `$PATH` together with the following Lua snippet (e.g. loaded from the init event) should work?

```Lua
vis:map(vis.modes.INSERT, "<C-k>", function(keys)
	if #keys < 2 then
		return -1 -- need more input
	end
	local file = io.popen(string.format("vis-digraph '%s' 2>&1", keys:gsub("'", "'\\''")))
	local output = file:read('*all')
	local success, msg, status = file:close()
	if success then
		if vis.mode == vis.modes.INSERT then
			vis:insert(output)
		elseif vis.mode == vis.modes.REPLACE then
			vis:replace(output)
		end
	elseif msg == 'exit' then
		if status == 2 then
			return -1 -- prefix need more input
		end
		vis:info(output)
	end
	return #keys
end, "Insert digraph")
```

@KolesnichenkoDS, @josuah can you try this out and report whether it works?

**Comment by josuah** [comment]
I am putting the output of the script straight in the tree, as it is not something that is likely to change (June 1992) and it is still possible to update it here from the script in this issue.
