### ISSUE TITLE
n and N after reverse search with ?

### ISSUE THREAD

**Issue by xcko** [martanne/vis#470]
After doing a reverse search with ?, n goes to the next forward result, not the next result in reverse.

This is the opposite of vi/vim behaviour.

**Comment by aeosynth** [comment]
> The intention is *not* to be bug for bug compatible with vi(m)

i prefer this behavior

**Comment by oxalorg** [comment]
In my opinion, since the search already wraps around by default, there is no need of `?` at all.

**Comment by Shugyousha** [comment]
On Sat, Jan 21, 2017 at 02:10:44AM -0800, Mitesh Shah wrote:
> In my opinion, since the search already wraps around by default, there is no
> need of ? at all.

For me there is.

If you work with bigger files (100MB+) it often happens that the string
you are searching for occurs hundreds of times in a file. You do not want
to cycle through all hits if you know that the particular hit you are
looking for is further up from your cursor position.

I have no problem with the current behaviour of vis though.

**Comment by erf** [comment]
I would prefer it to be consistent with vim. It makes sense to me to use 'n' to search again in the same direction.

**Comment by xcko** [comment]
erf wrote:
> I would prefer it to be consistent with vim. It makes sense to me to use 'n' to search again in the same direction.

I would also prefer that it be internally consistent. ; and , both switch directions after using TtFf.
Why should there be a difference when searching across lines to searching within a line?

**Comment by martanne** [comment]
Like @aeosynth I prefer the current behavior for interactive usage. 

I like the fact that `n` (`N`) always searches forwards (backwards) irrespective of how the initial search was performed (e.g. `*`, `#`, `/pattern`, `?pattern`, `:-/pattern` `:+/pattern` etc). There can be times when quite some time passes between the initial search and the need to advance to the next (previous) match. In that case I most likely know whether I want to go forwards or backwards, but not how the initial search was performed.

As far as inconsistencies are concerned `gn` and `gN` always operate on the next/previous match irrespective of the initial search direction. So vim is not really self-consistent either.

It could probably be argued that the vim behavior is preferable for non-interactive usage (e.g. macros, mappings etc.) if you want to skip a couple of matches independent of the search direction.

**Comment by lafrenierejm** [comment]
@martanne wrote:

> As far as inconsistencies are concerned `gn` and `gN` always operate on the next/previous match irrespective of the initial search direction. So vim is not really self-consistent either.

As @xcko pointed out, vis is interally inconsistent with how it handles `;` and `,` versus the behavior of repeating searched.  This seems undesirable.
