### ISSUE TITLE
Execute command on keyboard sequence in short time interval

### ISSUE THREAD

**Issue by erf** [martanne/vis#48]
Would be cool to execute commands by pressing two keys in a short time interval. Also unicode characters would be nice.

I'm used to j+j for ESC in vim.

Btw. Thanks for vis, it works great for large text files!

**Comment by martanne** [comment]
I have currently no plans to implement something like this. I would expect `jj` to move 2 lines down irrespective of the typing speed.

> Also unicode characters would be nice.

Can you be a bit more specific. Are you referring to the insertion of Unicode codepoints with `^Vunnnn` in insert/replace mode? I would like to eventually support that, feel free to open a new issue.

**Comment by erf** [comment]
Ok. I was thinking when you are in insert mode.

Unicode chars seem to work now, like: æøå

2015-07-08 19:48 GMT+02:00 Marc André Tanner <notifications@github.com>:

**Comment by martanne** [comment]
> Are you referring to the insertion of Unicode codepoints with `^Vunnnn` in insert/replace mode?

[This should now work](https://github.com/martanne/vis/commit/38f00e3e8a50e1690dcb78cf1eca8b6befb7173b).

**Comment by erf** [comment]
Great work on the unicode codpoints.

Regarding 'jj', that should only work when you are in insert mode (so no
moving down two lines).


2015-07-20 10:29 GMT+02:00 Marc André Tanner <notifications@github.com>:
