### ISSUE TITLE
Deselecting multiple cursors

### ISSUE THREAD

**Issue by erf** [martanne/vis#480]
If you have the following:
```
hello, hello, hello, 
hello, hello, hello, 
hello, hello, hello, 
```
And select all commas with `:x/,`, and then press `C-l` to to deselect all cursors except primary cursor ( maybe i have misunderstood this behaviour ), there still exist three cursors on the first column like the following ( # is cursor ).
```
hello# hello, hello, 
hello# hello, hello, 
hello# hello, hello, 
```
And i then have to press `C-c` to remove the last cursors.

**Comment by martanne** [comment]
`:help` reads:
```
<C-l>                 Remove all but the count cursor column
```
A default count of 1 is assumed, hence only the cursors of the first column remain.

If you instead did `2<C-l>` then only the second cursor on every line would remain etc.

Similarly, if you did `2<C-c>` then the second cursor on every line would be removed letting the first and third intact.

To remove the selections (i.e. switch to normal mode) you press `<Escape>` to dispose all but the primary cursor you again press `<Escape>`.

It is currently not possible to remove all but the primary selection and remain in visual mode. It would be easy to implement though.

**Comment by erf** [comment]
Ok, i think it makes more sense for me to map `<C-c>` to `<Escape>`.
