### ISSUE TITLE
Name of current file in commands

### ISSUE THREAD

**Issue by raphael-proust** [martanne/vis#482]
In vim, the idiom `%` is expended to the name of the current file. This is useful especially for interacting with the shell (e.g., `:!git add %`, `:!cp % /foo/bar`).

In sam, the environment variable `$samfile` is set in all shell commands. In acme `$%`.

Considering the integration of shell in vis is closer to sam/acme, the environment variable would be better (IMHO). I have a mild preference for the acme variable because it's shorter and I'm more used to acme.

Would this be considered for vis?

This restricts the use of the file-name-in-command to shell commands. E.g., no `:0 i/\/* %: ISC license \/*/` – although this specific one can be done with `:0 <echo …`.

**Comment by martanne** [comment]
I also prefer `$%`, the following should in theory work:

```diff
diff --git a/vis.c b/vis.c
index 1f4d9a5..3f012e1 100644
--- a/vis.c
+++ b/vis.c
@@ -1547,6 +1547,10 @@ int vis_pipe(Vis *vis, Filerange *range, const char *argv[],
                close(perr[0]);
                close(perr[1]);
                close(null);
+
+               if (vis->win->file->name)
+                       setenv("%", vis->win->file->name, 1);
+
                if (!argv[1])
                        execlp(vis->shell, vis->shell, "-c", argv[0], (char*)NULL);
                else
```

It also shows up when doing `:0 < env | grep %=` however for some reason this doesn't work: `:0 < echo $?`.

Indeed the following which should roughly be what vis does internally doesn't seem to work either:
```
env '%=filename' /bin/sh -c 'echo $%'
```
changing the variable name from `%` to something else makes it work. I will later have to investigate what the problem is.

**Comment by raphael-proust** [comment]
As support for investigation: `env '%=filename' 9 rc -c 'echo $%'` displays "filename" as it should. All other shells I have on hand fail with "$%".

**Comment by martanne** [comment]
It has been pointed out that the environment variable name `$%` is not required to be handled by [POSIX utilities](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html). We probably have to settle for something longer (and more inconvenient).

**Comment by raphael-proust** [comment]
The link says “The name space of environment variable names containing lowercase letters is reserved for applications. Applications can define any environment variables with names from this name space without modifying the behavior of the standard utilities.”

so:  
`$visfile`  
`$vf`  
`$fname`  
`$file`  
`$filename`
?

Alternatively (maybe less readable):  
`$_`  
`$__`  
`$_vf`
?

**Comment by martanne** [comment]
`$_` would have been my preferred choice, but although it is [not reserved by POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xcu_chap02.html#tag_23_02_05_03) it seems commonly used by various shells (e.g. ksh, [bash](https://www.gnu.org/software/bash/manual/bashref.html#Special-Parameters)).

I think we should add some prefix (e.g. `$vis_`) to not interfere with existing variables of shell scripts which might be executed.

In 2464589156b1c75a883b6320328c3479a95dc6ae I went with `$vis_filepath` and `$vis_filename`, hope that works for you?

Maybe we could use `$__` as a shortcut for one of these?
