### ISSUE TITLE
backslash char-code in text argument of a, i, and c

### ISSUE THREAD

**Issue by raphael-proust** [martanne/vis#486]
Currently, the commands a, i, and c can include any characters. However, in practice, this is limited to characters that users can type into their terminal. Even though some mechanisms such as XCompose make it relatively easy to input many characters, it is difficult to input control characters and combining unicode runes.

Is it worth adding support for `\uXXXX` or similar escape mechanism? There is already escape code to support `\1`, `\&`, etc. so the change would not introduce new control structures.

**Comment by martanne** [comment]
I would agree if the primary focus was non-interactive usage (e.g. like `ssam(1)`), but within vis the command prompt is implemented as a regular file. As a consequence you can use features like `<C-v>uXXXX` (verbatim insertion) or `<C-k>XX` (digraphs). Isn't this good enough?

**Comment by raphael-proust** [comment]
The `<C-v>` mode works. (Sorry I missed it in the doc.)

I tested it (lightly) and even combining characters work. E.g., `:x/[ia]/a/̀/` (the combining accent is between the two slashes) adds an accent to all `a`s and `i`s.
