### ISSUE TITLE
<C-d> removes all indentation

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#487]
in insert mode, i use `<C-d>` to remove one level of indentation, but since it's implemented as `<Escape><<i`, on a blank line, this triggers the new behavior to remove all indentation. `<C-t>` is also affected.

**Comment by martanne** [comment]
Using `<Escape>` is probably a bad idea anyway because it breaks repeatability?

I don't really use auto indent, but the following might work? 

```
:map! insert <C-d> <vis-operator-shift-left><vis-operator-shift-left>
:map! insert <C-t> <vis-operator-shift-right><vis-operator-shift-right>
```

**Comment by aeosynth** [comment]
:+1: that works
