### ISSUE TITLE
configure not detecting lpeg, but still works

### ISSUE THREAD

**Issue by erf** [martanne/vis#492]
I have installed `lpeg (1.0.1-1)` using `luarocks` on `Ubuntu`, but when i run `configure` it says `liblpeg .. no` ( this is the same on `macOS` ).
I do get syntax highlighting now ( but the colors are the same as mentioned in  #456 ).

**Comment by martanne** [comment]
The configure message just means that [lpeg is not built in statically](https://github.com/martanne/vis/wiki/FAQ#syntax-highlighting-does-not-work-how-can-i-fix-it). See [this FAQ entry regarding the color issues](https://github.com/martanne/vis/wiki/FAQ#my-terminal-colors-are-messed-up-what-is-going-on).

Also [Ubuntu seems to have packaged lpeg](http://packages.ubuntu.com/search?suite=all&arch=any&searchon=names&keywords=lua-lpeg) so there is probably no need to use luarocks.

**Comment by MarSoft** [comment]
How or where do I obtain `liblpeg`? I tried to download `lpeg` and build it, but it yields just an ordinary `lpeg.so` with a bunch of `.o` files - but no `liblpeg`.

**Comment by martanne** [comment]
Indeed the Makefile shipped with lpeg doesn't produce an archive for static linking. You will have to create it yourself with something like:

```
ar rcu liblpeg.a lpvm.o lpcap.o lptree.o lpcode.o lpprint.o && ranlib liblpeg.a
```
