### ISSUE TITLE
Visual selection change after line-wise backward selection and indent

### ISSUE THREAD

**Issue by mjwhite** [martanne/vis#501]
If I create a line-wise visual selection backwards (with upwards line or paragraph movements) then apply an indent operation, the selection is reduced to a smaller number of lines at the top.

For example, create a file with the following lines:
```
one
two
three
four
```

Put the cursor on line `four` and press `V k k k >` to visually select four lines and indent the block to the right. After this operation, only the first one or two lines remain selected (seems to vary), and subsequent operations only apply to those.

Similar behaviour with backward paragraph line-wise selection `{`. But it doesn't seem to reproduce with forward line or paragraph selection; nor with character-wise visual selection (`v` rather than `V`).

**Comment by mjwhite** [comment]
In fact it seems to be to do with the cursor location:
- If you use character-wise selection in the above example `v k k k > > > >` the cursor moves around - it jumps forward through the buffer with each successive indent.
- If you move the cursor back to the end of the selection `v k k k o > > > >` (or `V` etc) everything behaves properly.
- If you select forwardwards from `one` then put the cursor at the top `V j j j o > > >` you see the problem behaviour.

**Comment by martanne** [comment]
Thanks for the analysis, I also recently noticed that it is broken. I suspect the issue is related to 2ac88768ec2a643fe4a91f1bcde476fb5ec662c8 (not verified).
