### ISSUE TITLE
Create more options for `gq` Operator

### ISSUE THREAD

**Issue by theNerd247** [martanne/vis#519]
I might not be able to find it, however, would it be possible to add cmdline options to pass to the `fmt` tool? The use case is more for blocks of text that are prefixed with comments and I want to keep those comments in place. The current implementation of `gq` uses the default options of `fmt` which is the prefix is not set and textwidth is set to 75. I sometimes I require 80 or 100 textwidth. Is there already a way to pass these options to `fmt`...or should I write a plugin?

**Comment by martanne** [comment]
With the latest changes something like the following should work?

```Lua
vis:operator_new("gq", function(file, range, pos)
	local status, out, err = vis:pipe(file, range, "fmt")
	if not status then
		vis:info(err)
	else
		file:delete(range)
		file:insert(range.start, out)
	end
	return range.start -- new cursor location
end, "Formating operator, filter range through fmt(1)")
```

This does not take different language specific formatters into consideration, but it should illustrate the basic idea.

Furthermore it is now possible to define `:set` options from Lua.

**Comment by theNerd247** [comment]
Excellent! This will work. I think fancier formatting should be handled by larger tools such as astyle or hlnt (for Haskell code).
