### ISSUE TITLE
No tags

### ISSUE THREAD

**Issue by beefcurtains** [martanne/vis#52]
:heart: :heart: :heart: Please create a tag some time, much appreciated! :heart: :heart: :heart:

**Comment by martanne** [comment]
Why? Just use current git HEAD for now.

If you are talking about a proper release, then collecting a minimal list of bugs to fix / features to implement would be a start. Also more testing. I plan to add a "high-level" test suite which feeds keyboard input to both vis and vim and then compares their respective results.

**Comment by Ypnose** [comment]
Adding a tag starting by <code>0.</code> won't do any harm to you. And it will be much easier for packagers, to do the job using tarballs. Or maybe you don't want the packagers to include your <code>EDITOR</code> in the repositories.

**Comment by martanne** [comment]
The thing is there are still some bugs left (e.g. the recently fixed #47) which could cause some damage to your system. Ideally I would like to fix those before releasing an official version. Once you get a bad reputation for being unreliable it is hard to gain mindshare. On the other hand a release or more publicity in general might attract more developers ...

**Comment by beefcurtains** [comment]
It already exists in Void Linux, but we recently stopped accepting git packages and would like to switch the remaining -git packages to proper tags/releases. Just create one whenever you are ready and we'll change the relevant template files.

Closing because this isn't really a bug, sorry to bother you :sob:
