### ISSUE TITLE
escape delay can't be set to 0

### ISSUE THREAD

**Issue by whilealive** [martanne/vis#529]
I don't know if this is intended but even if I do "set escdelay 0" there is a delay when using the escape key to change from insert to normal mode. So if I quickly type "Esc-o", for example, it inserts <M-o> in insert mode instead of leaving it and accepting the o key.

**Comment by martanne** [comment]
Can you provide a bit more context information? Are you by chance using a terminal multiplexer?

I updated the [FAQ entry](https://github.com/martanne/vis/wiki/FAQ#m-key-is-inserted-whenever-i-press-escape-and-key-in-short-succession) concerning this issue.

**Comment by whilealive** [comment]
Thanks for the FAQ entry. Now it's clear to me. Yes, the problem only appears within tmux. I've set its "escape-time" to 0 which fixes it.
