### ISSUE TITLE
Non-Goals

### ISSUE THREAD

**Issue by rychipman** [martanne/vis#53]
I think the project would benefit greatly from stating some explicit non-goals. In fact, I think that in order to satisfy the stated goal summary from the README

> "80% of vim's features (in other words the useful ones) implemented in roughly 1% of the code"

it is _necessary_ to clearly delineate what kinds of things the editor will not handle. Feature creep is insidious, but good planning can head it off before it ever becomes a problem.

**Comment by rychipman** [comment]
To clarify, I think that the "Stuff which vim does which I don't use and have no plans to add" section in the README is very useful and a good step in this direction. However, I think it would also be useful to delineate non-goals on a higher level.

Generally, when evaluating design decisions, it would be nice to have some considerations about the future direction of the project to serve as guidelines and reference points.

**Comment by martanne** [comment]
Do you have anything special in mind?  In general I would like to keep vis reasonably simple such that different things can be tried with relative ease.

It might be a better idea to list explicit goals? The (partially outdated) [TODO section of the README](https://github.com/martanne/vis#todo) could be a start.

**Comment by martanne** [comment]
I've added a section to the [README](https://github.com/martanne/vis#non-goals) feel free to suggest improvements.
