### ISSUE TITLE
ip/ap text objects at the end of a paragraph

### ISSUE THREAD

**Issue by josuah** [martanne/vis#543]
```
While the cursor is at the end of a paragraph,
like this one: #

And when I trigger an action using the "ip" or "ap" text objects,
the second paragraph, this one, will also be affected (deleted for "dap",
formatted for "gqip"...).
```

Is this the intended behavior?  If I put the cursor back one character, it only act on the first one.

Tracing potential origin:

- config.h: `TEXT_OBJECT_PARAGRAPH`
- main.c: `VIS_TEXTOBJECT_PARAGRAPH`
- vis-text-objects.c: `text_object_paragraph`
- [text-objects.c at line 172](https://github.com/martanne/vis/blob/04fdfe6e0720cf815d0d61189fdd36872ad816f7/text-objects.c#L172) `r.end = text_paragraph_next(txt, pos);`
- [text-motions.c at line 445](https://github.com/martanne/vis/blob/04fdfe6e0720cf815d0d61189fdd36872ad816f7/text-motions.c#L445):

``` c
size_t text_paragraph_next(Text *txt, size_t pos) {
        char c;
        Iterator it = text_iterator_get(txt, pos);

        while (text_iterator_byte_get(&it, &c) && c == '\n')
                text_iterator_char_next(&it, NULL);
        return text_line_empty_next(txt, it.pos);
}

```

It is only checking for the next bytes, and not the current/prev one.  So maybe also check for it?

But maybe not in `text_paragraph_next`, as this could cause `}` to be stuck at the end of a paragraph.  Maybe one step before in text object paragraph ?

``` diff
 Filerange text_object_paragraph(Text *txt, size_t pos) {
 	Filerange r;
 	r.start = text_paragraph_prev(txt, pos);
-	r.end = text_paragraph_next(txt, pos);
+	r.end = end_paragraph(txt, pos) ? pos : text_paragraph_next(txt, pos);
 	return r;
 }
```

One more time, there is no hurry.

**Comment by martanne** [comment]
Not really intended, just never properly implemented. There is currently also no distinction between inner and outer paragraph text objects.

Patches to fix these issues will be gladly accepted. Ideally they would also include tests for the corresponding motions (`{`, `}`) as well as text objects (`ip`, `ap`). In fact it is probably a good idea to start with the tests.

**Comment by josuah** [comment]
I can do this after the exams (1~2 weeks) if you can wait.  :-)

**Comment by martanne** [comment]
I hope your exams went as desired. Do you still plan to fix this? If you have any questions, do not hesitate to ask either here or on IRC.

**Comment by josuah** [comment]
If the cursor is `#`

```
Paragraph 1.
#
Paragraph 2.
```

And I do `dip`/`dap`: What do we want?  I guess we use `dip`/`dap` only while *inside* a paragraph.

- On `dip`, vim delete the blank line.

- On `dap`, vim delete the next paragraph.

The same occurs for words: while in spaces in-between words, `da*` delete the next `*` (whatever) object, and `di*` delete the space before the next object.

The same for vis?

**Comment by martanne** [comment]
That sound reasonable. The word objects should already behave as you described?
