### ISSUE TITLE
First character missing from `!' output

### ISSUE THREAD

**Issue by CasperVector** [martanne/vis#545]
For example, `:!echo 01; sleep 1↵` results in `1` showing up instead of `01`.

**Comment by realwhz** [comment]
I can reproduce the bug.  Actually, it is very weird that only cmd_launch has this bug; cmd_filter/pipeout is fine.

**Comment by realwhz** [comment]
Maybe using `sleep` to hold the output is not a valid use case.  I read issue 416 and I think the current implementation is at least good for interactive cases.
