### ISSUE TITLE
vis-menu: Null pointer passed as an argument to a 'nonnull' parameter

### ISSUE THREAD

**Issue by mikaoP** [martanne/vis#550]
https://github.com/martanne/vis/blob/master/vis-menu.c#L275
https://github.com/martanne/vis/blob/master/vis-menu.c#L441

**Comment by martanne** [comment]
This is now outdated, you should ideally include the commit hash against which you report such issues. Also the full warning / call graph leading to the invocation would have been useful.

I couldn't reproduce your findings and a recent [coverity scan](https://scan.coverity.com/projects/3939) didn't report it either.
