### ISSUE TITLE
"Invisible" (tab, space, newline) symbols are copied with a mouse

### ISSUE THREAD

**Issue by pshevtsov** [martanne/vis#552]
If I `:set show-newlines on`, `:set show-spaces`, `:set how-tabs on`, type some text with tabs, spaces and newlines and then select/copy it with the mouse, the "invisible" symbols are copied as well:
```
›       hello·world↵
```

**Comment by raphael-proust** [comment]
I don't think you can draw characters on a terminal that wouldn't be copied by mouse selection. Vim definitely has the same behaviour:

```
:set listchars=tab:▷\ 
```

will make selections contain ▷ characters.

**Comment by pshevtsov** [comment]
Oh, yes, indeed!
