### ISSUE TITLE
^ and $ have inconsistent meaning in x extracted pattern compared with Sam

### ISSUE THREAD

**Issue by realwhz** [martanne/vis#554]
Support there is a text file containing a single line:
 a aa aaa a 
Note that the line has some white spaces at the beginning and ending around the line.

The following cmd will change the two single 'a' into 'b' [EDIT: fixed a typo in the following cmd]
1x/[a-z]+/g/^a$/c/b/
So the file becomes
 b aa aaa b 
That is, the cmd has the effect to change single 'a' and excludes any other pattern.  It is surprising because it means that after x, the extracted pattern has "unusual" interpretation to meta characters '^' and '$'.  This behavior is inconsistent to Sam; in Sam '^' and '$' always match to line beginning and ending.

**Comment by martanne** [comment]
Yes, in vis `^` and `$` always match the start/end of the range being processed. This seems logical to me. But we should probably document (either in the manual or [wiki page](https://github.com/martanne/vis/wiki/Differences-from-Sam)) that it behaves differently than in sam.

> The following cmd will change the two single 'a' into 'b'
> 1x/[a-z]/g/^a$/c/b/

That is actually not the case. The `x` command extracts every single letter, hence `g/^a$/` matches all of them and the file becomes `b bb bbb b`. What you describe happens for the command `1x/[a-z]+/g/^a$/c/b/`.

**Comment by realwhz** [comment]
Sorry, it's a typo.  The cmd I tried is
1x/[a-z]+/g/^a$/c/b/

This is an example in Rob Pike's Sam paper.  There he mentioned it is a pity that he couldn't use ^ and $ in this way and instead he has to use another v cmd to rule out longer patterns.

Agree.  It is better be documented in manual.  Thanks.
