### ISSUE TITLE
Remove luaL_openlibs() from the configure script

### ISSUE THREAD

**Issue by orang-outan** [martanne/vis#555]
Hello,
It seems the luaL_openlibs symbol is missing with the Lua5.3 library. Better off stripping that off.

**Comment by martanne** [comment]
Why? It [should be there](https://github.com/lua/lua/blob/v5-3-4/lualib.h#L52) (and is used by vis).

**Comment by orang-outan** [comment]
Sorry, it was my lua setup which was wrong. I reinstalled lua. Everything is fine.
