### ISSUE TITLE
Document '%' behavior in Differences-from-Vi(m)

### ISSUE THREAD

**Issue by realwhz** [martanne/vis#557]
Hello.

I noticed the behavior of `%` is different from Vi(m).  In Vi(m), `%` will "Find the next item in this line after or under the cursor and jump to its match".  When the cursor is on one of the special characters, it will jump to its match backward or forward depending on where its match is.  When the cursor is not on any special characters, it will attempt to find one **forward** and then jump.  For example:
```
foo(x, y);
```
When the cursor is before '(', `%` will jump to ')'.  When the cursor is on '(' or ')', `%` will jump to ')' or '('.  When the cursor is after '(' but before ')', `%` will finally jump to '('.  When the cursor is after ')', `%` does nothing as there is no any special character after that in the current line.

Vis's behavior is different, which may need to be documented in the wikipage of "Differences-from-Vi(m)".

Thanks.

**Comment by martanne** [comment]
Hi, it is a wiki so you should be able to edit it yourself? Please keep it concise.

The behavior mentioned in #499 should probably also be documented ...

**Comment by realwhz** [comment]
Thanks.  Updated the Wiki with the difference.
