### ISSUE TITLE
incorrect display when file begins with a multibyte character

### ISSUE THREAD

**Issue by TieDyedDevil** [martanne/vis#56]
When the first character of a file is a multibyte character, vis displays a sequence of Unicode REPLACEMENT CHARACTER.

I believe that the cause is the use of an anonymous (i.e. NULL) mbstate_t* object in the call to mbrtowc() in view_draw(). While this might actually be a bug in the implementation of mbrtowc(), it is avoided by use of an explicitly initialized mbstate_t object.

Here's a short patch:
```diff
diff --git a/view.c b/view.c
index d49c417..80f7038 100644
--- a/view.c
+++ b/view.c
@@ -349,6 +349,8 @@ void view_draw(View *view) {
 	memset(match, 0, sizeof match);
 	/* default and current curses attributes to use */
 	int default_attrs = COLOR_PAIR(0) | A_NORMAL, attrs = default_attrs;
+  /* start from known multibyte state */
+  mbstate_t mbstate = { 0 };
 
 	while (rem > 0) {
 
@@ -403,7 +405,7 @@ void view_draw(View *view) {
 			}
 		}
 
-		size_t len = mbrtowc(&wchar, cur, rem, NULL);
+		size_t len = mbrtowc(&wchar, cur, rem, &mbstate);
 		if (len == (size_t)-1 && errno == EILSEQ) {
 			/* ok, we encountered an invalid multibyte sequence,
 			 * replace it with the Unicode Replacement Character
```

**Comment by martanne** [comment]
Thanks, I didn't notice since it seems to work as is with [musl libc](http://www.musl-libc.org/).
