### ISSUE TITLE
Allow setting mode from Lua

### ISSUE THREAD

**Issue by p-e-w** [martanne/vis#562]
There currently does not seem to be a way to switch editing modes from Lua plugins. Attempting to assign a value to `vis.mode` crashes the editor (#561).

**Comment by martanne** [comment]
What you attempted (assigning to `vis.mode`) should in principle work, but currently not at this early stage.

And yes the documentation should be improved. I recently experimented with [readthedocs.org  for the C parts](vis.readthedocs.io) it would be nice if we could integrate the Lua API documentation somehow.

**Comment by p-e-w** [comment]
Is there currently a way to configure Vis to start in visual rather than normal mode?

**Comment by martanne** [comment]
The following should work:

```Lua
vis.events.subscribe(vis.events.START, function()
        vis.mode = vis.modes.VISUAL
end)
```
