### ISSUE TITLE
Expose bound keys via API

### ISSUE THREAD

**Issue by p-e-w** [martanne/vis#563]
I believe (would love to be corrected) there is currently a shortcoming in the API that makes it challenging to configure custom keybindings from plugins:

Let's say I want `i` to move the cursor up in visual mode. From the API documentation, one might think that

```lua
vis:map(vis.modes.VISUAL, "i", "<vis-motion-line-up>")
```

will do the trick, but unfortunately, it doesn't. The reason is that [there are already multiple keybindings consisting of *two* keys that have `i` as a prefix](https://github.com/martanne/vis/blob/master/config.def.h#L120-L139). Therefore, a single press of `i` does not do anything because the editor is waiting for more input so it can disambiguate.

To fix this problem, we need to unbind all existing key combinations that start with `i`. And here's the shortcoming: There is no way to find those from a plugin. Copying the bindings from `config.def.h` and then calling `unmap` for each of them, besides being ugly and verbose, does not help, because there might be additional bindings set by other plugins or the user might have customized the default bindings before compiling. In summary, there is no 100% reliable way to set keybindings from plugins.

I therefore propose the addition of a new API call

```
Vis:bound_keys(mode)
```

that returns an iterator over all key combinations for which a mapping exists in `mode`. This would allow a plugin to examine whether there are already bindings for the keys it intends to map, and react either by `unmap`ing those bindings or by binding a different key instead.

**Comment by p-e-w** [comment]
That was fast, thank you!

The new API works well, but while trying to use it to remove all visual mode keybindings I noticed another problem:

```lua
local bindings = vis:mappings(vis.modes.VISUAL)
for key, help in pairs(bindings) do
  vis:command("unmap visual " .. key)
end
```

This fails for the keys ` `, `'`, `"` and `\` because concatenating them to `unmap visual ` does not result in a valid command. It would be nice if you could add an `unmap` method to the Lua `Vis` object to match the `unmap` command so this can be accomplished without hacks like special-casing those characters or trying to come up with some "escaping" algorithm.

**Comment by martanne** [comment]
There is already an escaping algorithm in place. Quotes can be used to delimit arguments and a backslash escapes quotes. Due to the Lua escaping rules the backslash has to be doubled. 
```Lua
vis:command("unmap visual ' '")
vis:command("unmap visual \\'")
vis:command('unmap visual \\"')
```
However, I agree that dedicated `unmap` methods are nicer, see e7bfcf4fe6480e217e972889f69e1c44c4057c97.
