### ISSUE TITLE
Cannot use commands involving strings that contain `♪`

### ISSUE THREAD

**Issue by CasperVector** [martanne/vis#566]
As the title, eg. `/a ♪ b↵` and `:x/a ♪ b/↵` do not function.

**Comment by martanne** [comment]
Hi, thanks for the report. Does the referenced commit fix your issue?

I guess so, but you didn't specify whether your build uses libtre or not.

We should probably add a github issue template which asks for the output of `vis -v` and `uname -a` ...

**Comment by CasperVector** [comment]
Yes, it fixes the issue for me, and CJK characters (affected in the same way as `♪`) now become usable in commands.  Many thanks!
I did use TRE; I will post `vis -v` output in later issues (if any)...
