### ISSUE TITLE
Vis doesn't leave multi-cursor mode even when there is only a single cursor left

### ISSUE THREAD

**Issue by p-e-w** [martanne/vis#582]
**Steps to reproduce:**

1. Put
```
abc
def
```
into the buffer and switch to normal mode. Put the cursor on the `a`.
2. Press `<C-j>` to get a second cursor on the `d`, which is drawn in yellow, indicating multi-cursor mode.
3. Press `<Up>` to merge the two cursors.

**Expected behavior:** Vis enters single-cursor mode as there is only one cursor left.

**Actual behavior:** The cursor remains yellow, indicating that Vis is still in multi-cursor mode. You have to press `<Escape>` to leave it.

This is more than a cosmetic problem as the single cursor still behaves like two cursors in insert mode, i.e. typing a character inserts two copies.

**Comment by martanne** [comment]
Yes, the current model doesn't strictly enforce uniqueness of cursors (except at creation time). I agree that this is probably not ideal.

As mentioned in #581 I'm experimenting with a more selection centric approach. In this model overlapping selections would be merged.

**Comment by p-e-w** [comment]
Confirmed fixed. Thank you!
