### ISSUE TITLE
Enable -Werror?

### ISSUE THREAD

**Issue by p-e-w** [martanne/vis#586]
Vis currently builds without any compiler warnings, which is fantastic.

Should `-Werror` be enabled to make sure that remains so?

**Comment by EliteTK** [comment]
You don't need -Werror to ensure there are no warnings, you simply need to look at the compiler output.

**Comment by martanne** [comment]
Enabling `-Werror` for production builds is generally a very bad idea. We don't know what sort of compiler is used and what kind of warning it will emit. In the future compilers might introduce new warnings etc.

We could consider it for `make debug` builds which should be used during development.  These currently also enable stricter compiler flags `-Wall -Wextra -pedantic`. However, the problem there is that the inherited `vis-menu` code has some issues which would break the build.
