### ISSUE TITLE
Behave like :qall on SIGHUP

### ISSUE THREAD

**Issue by ceemos** [martanne/vis#587]
I use this single-line patch to prevent loosing edits when I accidentally close a terminal window:
```
        case SIGHUP:
-               vis->terminate = true;
+               vis_cmd(vis, "qall");
                return true;
```
Together with a cooperating terminal program (st also needs a patch) this can keep the window open when there are unsaved changes.

**Comment by mqudsi** [comment]
It should be possible to distinguish from the calling terminal whether vis exited normally or due to a signal, as such either a different exit code (see #609) should be used or the signal should be rethrown after `qall` is run.

**Comment by martanne** [comment]
What kind of patch did you use for st? I think you should strive for a solution needing only changes to your terminal emulator and not the programs running within it.

In any case, the code you patched is being called from within a signal handler, meaning you can only use [async-signal-safe functions](https://pubs.opengroup.org/onlinepubs/9699919799/functions/V2_chap02.html#tag_15_04_03). However, [`vis_cmd` calls `malloc(3)`](https://github.com/martanne/vis/blob/17b83db3c57682991c188f0338bebe521408917a/vis.c#L1918) which is not.
