### ISSUE TITLE
Is there a way to map to a function?

### ISSUE THREAD

**Issue by ddkn** [martanne/vis#597]
Hello,

I was wondering if there was a way in the visrc.lua script to `map` to a function? For example, I would like to have latex have certain formatting (this is just a simple case)

```
function fmt_latex()
     vis:command('set tw 2')
     vis:command('set cc 80')
end
```
and then either do
`:map normal <F5> fmt_latex()`
or in visrc.lua
`vis:command('map normal <F5> fmt_latex()')`

The current use of this would run commands f, m, t, _ then detect **a**, and append **tex()** as expected. However I am curious as to running a set of commands in succession, is this possible? Or did I miss something?
In vim I would do the following in vimrc
```
function fmt_latex()
  set ts=2
  set sw=2
  set cc=80
endfunction

noremap <F5> :call fmt_latex()<CR>
```

**Comment by erf** [comment]
Did you see the [Lua API doc](http://martanne.github.io/vis/doc/), or more specifically: http://martanne.github.io/vis/doc/#Vis:map ?

**Comment by martanne** [comment]
As pointed out something like the following should work:

```lua
vis:map(vis.modes.NORMAL, "<F5>", function() 
        vis:command('set tw 2') 
        vis:command('set cc 80')
end)
```

**Comment by ddkn** [comment]
@erf I didn't see those documents! I have just been using the man page, thanks!
@martanne Ah I see! This has hit all my needs! Once I finish my project I will try and help out! Thanks!
