### ISSUE TITLE
set tabwidth delay on startup

### ISSUE THREAD

**Issue by erf** [martanne/vis#600]
I `set tabwidth 4` in `visrc.lua` on `WIN_OPEN` ( also tried on `INIT` ) and notice sometimes a delay, when it's first set to 8 and moved back. This is just a minor annoyance, but i wonder if there is a way to fix this? 
I'm on a MacOS, using the default Terminal, vis v0.4-2-g9ab8bcd +curses +lua +tre.

**Comment by martanne** [comment]
Is this still an issue? I can't reproduce it.
