### ISSUE TITLE
filetype plugin: .cls files are mapped to VB, when they should be LaTex

### ISSUE THREAD

**Issue by ltobler** [martanne/vis#604]
Both VB and LaTex use `.cls` ("class") files. `filetype.lua` currently maps `.cls` to Visual Basic. I think it would be more sensible to assume they are LaTex files, because my guess would be that exactly 0 people us Vis to write VB (does Vis even work on Windows at all?).

EDIT: Pull request opened: #606

**Comment by martanne** [comment]
Thanks. Vis can be used with Cygwin on Windows. At some point a few users even did so, which is why I set up an [AppVeyor based CI build](https://ci.appveyor.com/project/martanne/vis/branch/master).
