### ISSUE TITLE
configure script ignores interrupts

### ISSUE THREAD

**Issue by mqudsi** [martanne/vis#607]
The configure script acts weird with interrupts; it ignores them but they then later trigger a failure in some of the tests that configure shells out to.

```
mqudsi@ZBook ~/r/vis> ./configure
checking for C compiler... scc
checking whether C compiler works... yes
checking whether compiler accepts -Werror=unknown-warning-option... ^Cno
checking whether compiler accepts -Werror=unused-command-line-argument... ^Cno
checking whether linker accepts -Werror=unknown-warning-option... ^Cno
checking whether linker accepts -Werror=unused-command-line-argument... ^Cno
checking whether compiler accepts -pipe... ^Cno
checking whether compiler accepts -Os... ^Cno
checking whether compiler accepts -ffunction-sections... ^Cno
checking whether compiler accepts -fdata-sections... ^Cno
checking whether linker accepts -Wl,--gc-sections... ^Cno
checking whether compiler accepts -fPIE... ^Cno
checking whether compiler accepts -fstack-protector-all... ^Cno
checking whether linker accepts -Wl,-z,now... ^Cno
checking whether linker accepts -Wl,-z,relro... ^Cno
checking whether linker accepts -pie... ^Cno
creating config.mk... done
checking for pkg-config... yes
checking for libcurses...
 checking for ncursesw... ^Cno
 checking for ncurses... ^C^Cno
 checking for libcurses... ^Cno
./configure: cannot find libcurses
```

`./configure` without any interrupts would have succeeded:

```
checking for libcurses...
 checking for ncursesw... no
 checking for ncurses... yes
```

**Comment by martanne** [comment]
The configure script [traps interrupts](https://github.com/martanne/vis/blob/1e414d215ebb98e709717cd116ce83acdc863a78/configure#L193) to clean up temporary files, meaning `^C` cancels the current check not the complete script.

Is this really worth bothering about? The original code [stems from the musl configure script](http://git.musl-libc.org/cgit/musl/tree/configure#n218).

**Comment by mqudsi** [comment]
It’s not a big deal at all since unlike some configure scripts, it doesn’t take half an hour to run. But it’s still broken. It doesn’t make sense to abort a single test but not terminate the rest of the script; that handler should set a flag and abort both the current process and the script.

I’m sure musl has a reason for doing it that way, but I can’t see how it makes sense for us with vis. A configure script is much like a makefile in that it’s expected all its commands will ultimately succeed (or fail but still return true). A signal-triggered abort of a configure command should fail the entire script immediately, shouldn’t it?
