### ISSUE TITLE
ctrl-c should exit ex mode

### ISSUE THREAD

**Issue by mqudsi** [martanne/vis#608]
Currently, after typing `:` to enter ex mode, ctrl+c has no effect. There doesn't seem to be a safe way to go back to the editor besides clearing the contents of the prompt and then pressing enter.

ctrl+c should exit the prompt and go back to the editor.

EDIT: just found out that `<ESC>` will exit the prompt. Ctrl+C probably should, too.

**Comment by mqudsi** [comment]
As far as I can tell, in vis `<C-c>` is globally aliased to `<Escape>` - why are they behaving differently at the prompt?

**Comment by anko** [comment]
A `visrc.lua` workaround is to explicitly specify that mapping:

    vis:map(n, '<C-c>', '<Escape>')

Closing the prompt requires 2 presses though: insert mode → normal mode → (close prompt).

**Comment by martanne** [comment]
@anko I agree that this was an inconsistency in the command prompt buffer.

@mqudsi if you want to mimic the vim behaviour you could try something like:

```
:map! insert <C-c> <Escape><Escape>
```
