### ISSUE TITLE
Implement :cq

### ISSUE THREAD

**Issue by mqudsi** [martanne/vis#609]
In vim, `:cq` can be used to force exit with an error code set, handy when attempting to abort a workflow that has spawned an editor in the process. For example, if you call `git commit` from the shell and you have vis set as your git editor, `:cq` would abort the commit.

**Comment by MarSoft** [comment]
+1, would be great. And probably not too hard to implement..

**Comment by martanne** [comment]
The following [patch implements `:cq`](http://sprunge.us/KTPi). As mentioned on IRC, ideally I would like to keep the built in commands to a minimum. Hence another option would be to introduce an optional exit status for `:q` and `:qall`, respectively. It might be a bit inconvenient to type though, `:cq` would become `:qa 1`.

**Comment by MarSoft** [comment]
@martanne Nice idea with custom exit status value, it opens a bunch of usage possibilities. And it is still easy to add an alias `:cq` manually in user's config, right,

**Comment by mqudsi** [comment]
I've been thinking this over in the back of my head for some time now, and I wonder if perhaps there should be some sort of official "vim compatibility pack" that can offer commands (or aliases to commands) but isn't a part of the core, so that vis isn't burdened by the legacy missteps/bloat of vim (see for example neovim, which is still significantly saddled by compatibility concerns).

Obviously this has always been more or less a design goal of vis, but I'm not just suggesting "minimal compatibility, user can fill in the rest" but rather a conscious effort to keep in mind user-mapped commands for vim support, such that even if vim features are not adopted there shouldn't be any vis features that would clash with them (unless absolutely necessary).

What I mean is some sort of "promise" to "reserve" vim motions/commands so that they can be filled in with a vis plugin without conflicting with later-implemented vis features, even as vis doesn't actually implement these vim features (if that makes any sense).

**Comment by martanne** [comment]
I implemented the optional exit code for `:q` and `:qall` in 91d49a0dd0feac1a97b63091ce7f6f32e619fff8, so you should be able to set up an alias.

As for promises regarding vi(m) compatibility, I don't want to add such restrictions. An explicit goal of the project is to try and experiment with different ideas. I recently didn't have much time for that, but in general I expect that the editing experience will likely diverge further from the typical vi(m) workflow.
