### ISSUE TITLE
Strange characters appear when syntax highlighting is turned on

### ISSUE THREAD

**Issue by PaulBatchelor** [martanne/vis#61]
When I turn on syntax highlighting, weird characters for things like tabs and line breaks get displayed like so: ![text](https://cloud.githubusercontent.com/assets/8139389/8766173/3c055446-2dfb-11e5-9a7d-9dbd9f7cb681.png).

I get this problem on st, xterm, and urxvt, and these characters are visible.

I'm currently running vis on a Slackware 14.0.

**Comment by martanne** [comment]
These should be unicode characters [U+23CE](http://www.fileformat.info/info/unicode/char/23ce/index.htm) (return symbol) and [U+25B6](http://www.fileformat.info/info/unicode/char/25b6/index.htm) (black right-pointing triangle). The latest [vis commit](https://github.com/martanne/vis/commit/38f00e3e8a50e1690dcb78cf1eca8b6befb7173b) enables you to enter any unicode character via its code point.

Assuming you are running on a UTF-8 aware system, I'm not sure why they would cause problems. Does your font support them?

You can disable these whitespace replacement symbols with `:set show tabs=0 newlines=0`

**Comment by PaulBatchelor** [comment]
It seems that these characters started appearing after [this commit](https://github.com/martanne/vis/commit/87c7258ccc683965d2b6a5190f1e98d74c8d25d3).

":set show tabs=0 newlines=0" does indeed remove these characters. 

Is there any way to to set these as the default options in the config.h?

**Comment by PaulBatchelor** [comment]
It turns you turned on whitespace replacement symbols by default for C syntax highlighting. I was able to disable this in the config.h file. This solution works for me, so I am closing this ticket.
