### ISSUE TITLE
Manual has unintended formatting in See Also

### ISSUE THREAD

**Issue by parnmatt** [martanne/vis#610]
As can be screenshot below, the See Also section has some strange formatting.
( I'm using man 2.7.6.1, with groff 1.22.3 )

![See Also, man vis](https://user-images.githubusercontent.com/318829/30558997-0c4ffcee-9cab-11e7-966e-151879f6443c.png)

**Comment by martanne** [comment]
Is this still an issue after the recently merged #605?

At least with mandoc it seems to work fine ...

**Comment by parnmatt** [comment]
Indeed that fixes the miss-format my bad.

The date in the manual should reflect when the manual was last updated.
Thus to be consistent `August 13, 2017`; but of course, editing that would make it be whatever the date is when the commit was authored.
