### ISSUE TITLE
Feature request: support for backup files

### ISSUE THREAD

**Issue by hucal** [martanne/vis#620]
**Request:** I'd like Vis to write a copy of the file to a user-defined location. The backup filename and whether this happens at all should be defined in the user's configuration (either `config.h` or `visrc.lua`).

**Analogous VIM feature:** The following lines configure VIM to work as I'd like vis to work `set backup`, `set backupdir`, and `au BufWritePre * let &backupext = ...`.

**Comment by hucal** [comment]
I can work on a pull request. I'd appreciate some guidance on when/where Vis writes to the file.

**Comment by josuah** [comment]
What about a script that makes the backup then starts vis?
This script could be the "$EDITOR", and toggle other goodies.
But that is sure a bit strange to have "$EDITOR" not set to a binary program.

Having temporary files created by default in the current directory is the only thing I wish to avoid.

**Comment by hucal** [comment]
josuah, that makes sense. I also agree that writing to a temp file in the current directory is undesirable. However, the script you suggest only creates one backup per vis session. I'd like it to write a backup **every time I write the file**, aka incremental backups.

I could have a script like this:

1. setup a filewatcher that copies `$FILE` to `get_backup_fname($FILE)` when a program writes to `$FILE`
2. start vis `$FILE`

This would do almost exactly what I want. The only problem is that I want the backup to happen right before vis writes to the file. Basically, I want a vis to run a function right before it writes to my file.

**Comment by hucal** [comment]
Maybe this backup strategy is misguided, but a more general purpose feature that other vis users might need would be making vis call a user-defined function before writing to a file.

Then I'd define my backup function in `config.h`/`visrc.lua`, and vis would call it before any writes.

**Comment by erf** [comment]
You could make a lua [plugin](https://github.com/martanne/vis/wiki/Plugins) which would save to a new file on each [file_save_post](http://martanne.github.io/vis/doc/#Core_Events).

**Comment by josuah** [comment]
Ah, you are right, multiple buffers would not be supported with a script.

**Comment by hucal** [comment]
> You could make a lua plugin which would save to a new file on a specific event, e.g. INPUT or FILE_SAVE_PRE.

That'd be ideal!

Question: is the function `write_all` in `text.c:175` the only place where vis writes to files? If so, this is very easy to implement.

**Comment by erf** [comment]
@hucal i don't think backup will be accepted as part of core, but you can save from a lua plugin file. see [example](https://github.com/erf/vis-cursors/blob/master/cursors.lua)

**Comment by hucal** [comment]
I've read the docs and the source more closely, I now see how I can write a backup function with the existing functionality using vis events. I need only subscribe to the `VIS_EVENT_FILE_SAVE_PRE` event using `vis.events.subscribe`.

Thank you for the help! I'll make use of the example you linked.

**Comment by hucal** [comment]
This issue is completely resolved thanks to vis' plugin API.
I wrote a [backup plugin](https://github.com/hucal/vis-backup) to satisfy my requirement.
