### ISSUE TITLE
Key 'M' is used for restoring mark

### ISSUE THREAD

**Issue by realwhz** [martanne/vis#622]
In vis's man page, 'M' is said to be the key to restore the mark. Later 'M' is also said to be the key to go to the middle of the window (H/M/L). Those two usages are conflict and looks like the second usage is not valid.

**Comment by Shugyousha** [comment]
Hi

On Mon, Oct 23, 2017 at 5:18 AM, Hongzheng Wang
<notifications@github.com> wrote:
> In vis's man page, 'M' is said to be the key to restore the mark. Later 'M'
> is also said to be the key to go to the middle of the window (H/M/L). Those
> two usages are conflict and looks like the second usage is not valid.

Yes, in config.def.h "M" is bound to both of those functions but from
what I can tell, the restore functionality is bound later and thus
prevails. As far as I know this binding is intended but it may indeed
make sense to remove the other one and change the man page
accordingly.
