### ISSUE TITLE
Vim and vis Esc incompatibility (not sure if it's intended)

### ISSUE THREAD

**Issue by aksr** [martanne/vis#629]
If I start to write, for example, a function in vim like this:
`int main()` and if I press `Esc` immediately after entering `)`, 
vim exits input mode, and it *hovers* (now in normal/command mode) above `)`.
`vis` doesn't reproduce this behavior, instead cursor (also in command mode) is after `)`:
`int main()^`

Is this intended?
If not, is there a possibility to change this to be vim-like?

**Comment by martanne** [comment]
For now it is [intended behavior](https://github.com/martanne/vis/wiki/Differences-from-Vi(m)#cursor-positioning-when-leaving-insert-mode) and unlikely to change.
