### ISSUE TITLE
get rid of syntax highlighting

### ISSUE THREAD

**Issue by mehlon** [martanne/vis#63]
Maintaining syntax files and parsing is not worth it for the colorful distraction. Efficiency would be improved, too. 
See also [syntax off](http://www.kyleisom.net/blog/2012/10/17/syntax-off/)

Edit: unless you're doing this to challenge yourself

**Comment by martanne** [comment]
This was discussed before on the suckless developer mailing list. To quote from your link:

> To each their own

`:set syntax off` is your friend.

Regarding the actual implementation I agree it could be improved. At the moment it is [extremely minimal ~100 LOC](https://github.com/martanne/vis/blob/master/view.c#L367) without rules. Hence it does not support stuff like nested rules etc. Personally I think it is a good compromise. However if we decide to improve it, we should try to reuse some existing syntax definitions.
