### ISSUE TITLE
Use output of an interactive command

### ISSUE THREAD

**Issue by guillaumecherel** [martanne/vis#634]
I would like to use [fzf](https://github.com/junegunn/fzf) to open files in vis. I can launch and interact with fzf with the command `! fzf`, but I don't know how to use what fzf writes to stdout. I've seen the lua command `vis:pipe(file, range, command)` but I couldn't make it work. How can I do? 

Here is what I tried with `vis:pipe`:

    vis:command_register("foo", function(argv, force, win, selection, range)
        local status, out, err = vis:pipe(win.file, range, "fzf")
        vis:info(output)
        return true;
    end

fzf seems to be spawned but I can't see it and can't interact with it.

**Comment by NoctuaNivalis** [comment]
I've been using FZF with vis for a while. This works on the latest release (0.4):

```lua
vis:map(vis.modes.NORMAL, ";l", function()
	local out = io.popen("fzf"):read()
	if out then
		vis:command(string.format('open %s', out))
	end
	vis:feedkeys("<vis-redraw>")
end)
```

This will always open a split window with the new file.

Since yesterday, we can [close windows](https://github.com/martanne/vis/commit/c00ef937ac0e6bc6391f973783e900ff5691f4c3) on master, so below command allows replacing the current window instead. Sorry for ugly code, I don't actually know lua.

```lua
vis:command_register("fzf", function(argv, force, cur_win, selection, range)
	local old = cur_win
	local out = io.popen("fzf"):read()
	if out then
		vis:command(string.format('open %s', out))
		if argv[1] then
			old:close(force)
		end
		vis:feedkeys("<vis-redraw>")
	end
end)

vis:map(vis.modes.NORMAL, ";l", function()
	vis:command('fzf')
end)

vis:map(vis.modes.NORMAL, ";o", function()
	vis:command('fzf true')
end)
```

**Comment by guillaumecherel** [comment]
Thanks for the answer! With your help, I was able to write the following:

```lua
vis:command_register("fzf", function(argv, force, win, selection, range)
    local command = "fzf " .. table.concat(argv, " ")

    local file = io.popen(command)
    local output = file:read()
    local success, msg, status = file:close()

    if status == 0 then 
        vis:command(string.format("e '%s'", output))
    elseif status == 1 then
        vis:info(string.format("fzf: No match. Command %s exited with return value %i." , command, status))
    elseif status == 2 then
        vis:info(string.format("fzf: Error. Command %s exited with return value %i." , command, status))
    elseif status == 130 then
        vis:info(string.format("fzf: Interrupted. Command %s exited with return value %i" , command, status))
    else
        vis:info(string.format("fzf: Unknown exit status %i. command %s exited with return value %i" , command, status, status))
    end

    vis:feedkeys("<vis-redraw>")

    return true;
end)
```

It uses vis' `e` command so the file is loaded in the current window explicitly. I did error handling as best as I could: there is apparently no easy way to read stderr in lua.

I could make a pull request with this added as a plugin if it's worth it...

**Comment by guillaumecherel** [comment]
Or rather make a git repo of my own for it.
