### ISSUE TITLE
Unknown option `theme'

### ISSUE THREAD

**Issue by maskedbyte** [martanne/vis#641]
Version: vis v0.4-24-g8e27737 +curses +acl (also tried vis v0.4)
Terminal: urxvt
$TERM: `rxvt-unicode`
I can't set the theme. It says `Unknown option 'theme'`, when I execute for example `:set theme theme`, or `:set theme "theme"`. Executing `:set change-256colors <true or false>` does not affect this problem in any way. Maybe it's related to the fact I'm getting the same "no highlighting for selected text" issue as in https://github.com/martanne/vis/issues/635.

<sup>Also, where should I ask more general questions that I can't find an answer to in docs/issues/wiki, e.g. _Can I have a different cursor style in insert mode?_ or _How do I do X in a Lua plugin?_ Maybe setting up a gitter would be a good idea.</sup>

**Comment by NoctuaNivalis** [comment]
<sup>General questions on [IRC](https://github.com/martanne/vis/wiki/Developer-Overview#irc-channel)</sup>

**Comment by erf** [comment]
Do you have a theme named `theme`? Did you try `:set theme default-16` or `set theme default-256`.

**Comment by martanne** [comment]
The problem is that your vis binary was built without Lua support which is required for theme definitions.

Try to build it with:
```
./configure --enable-lua && make && ./vis -v
```
This will likely fail because configure can't find the Lua development files. Once you have resolved that the version string should include `+lua`.
