### ISSUE TITLE
[PATCH] fix command malfuncton triggered by special cursor position

### ISSUE THREAD

**Issue by CasperVector** [martanne/vis#653]
```diff
--- a/vis-prompt.c
+++ b/vis-prompt.c
@@ -65,11 +65,7 @@ static const char *prompt_enter(Vis *vis, const char *keys, const Arg *arg) {
 			pattern = "^(/|\\?)";
 		if (pattern && regex && text_regex_compile(regex, pattern, REG_EXTENDED|REG_NEWLINE) == 0) {
 			char c;
-			size_t prev;
-			if (text_byte_get(txt, pos, &c) && (c == ':' || c == '/' || c == '?'))
-				prev = pos;
-			else
-				prev = text_search_backward(txt, pos, regex);
+			size_t prev = text_search_backward(txt, pos, regex);
 			if (prev > pos)
 				prev = EPOS;
 			size_t next = text_search_forward(txt, pos, regex);
```
The problem occurs when the user types a command and presses enter after placing the cursor on a `:`, `/` or `?`.  It is oftern encountered by me (and perhaps many others) because eg. when I input `:x/abc/`, I would type `:x//`, move the cursor to the second `/`, and then type `abc`, so the cursor is on the second `/` when I press enter.

**Comment by martanne** [comment]
Thanks, I will commit a slightly modified version which should also work when the cursor is above the initial prompt sign (this was the idea behind the original code).
