### ISSUE TITLE
[PATCH] filetype.lua: reap the zombie after io.popen()

### ISSUE THREAD

**Issue by CasperVector** [martanne/vis#655]
As the title.
```diff
diff --git a/lua/plugins/filetype.lua b/lua/plugins/filetype.lua
index f5c0800..dfbf2b0 100644
--- a/lua/plugins/filetype.lua
+++ b/lua/plugins/filetype.lua
@@ -459,6 +459,7 @@ vis.events.subscribe(vis.events.WIN_OPEN, function(win)
 		local file = io.popen(string.format("file -bL --mime-type -- '%s'", name:gsub("'", "'\\''")))
 		if file then
 			local mime = file:read('*all')
+			file:close()
 			if mime then
 				mime = mime:gsub('%s*$', '')
 			end
```

**Comment by martanne** [comment]
Did you experience any actual resource exhaustion? Once the file handle is garbage collected, [close will be called](https://www.lua.org/manual/5.3/manual.html#pdf-file:close) and the zombie is reaped.

Doing it manually doesn't hurt though.

**Comment by CasperVector** [comment]
No, no such experience; however, on my computer, I found the zombie to be present throughout the lifetime of the vis process.  And considering `io.popen` handles are closed soon in all other places in the vis repository except here, I think it is worthwhile to conform to the same convention here.
