### ISSUE TITLE
Can't search or replace Carriage Returns with vis v0.4

### ISSUE THREAD

**Issue by GregDavidson** [martanne/vis#656]
Running a freshly built vis v0.4-git +curses +acl +selinux
on Linux Mint 18.1 with Lua 5.2.4
I'm editing a file with line endings of CRLF showing as `^M` at ends of lines.
- `/^V^M` does not echo `^M` and takes me to the same place as `$`, i.e. 1 past the newline
- `:x/^V^M/c//` removes all of the newlines, leaving the carriage returns intact on one giant line!

In other words, carriage returns are being turned into newlines when entered,
but other control characters, e.g. `/^V^G` work as expected.

**Comment by martanne** [comment]
Yes, [`^V^M` is currently mapped to `\n` (new line)](https://github.com/martanne/vis/blob/e0b1a90ea831c4ebc184c3636ae9494a7675d82b/vis.c#L1095) not `\r` (carriage return). It could probably be changed. The default was chosen such that it can be used to enter multi-line sam commands (but the UI for it sucks).

In any case `^Vx0d` or using `\r` in the regex search as in: `x/\r\n/ x/\r/ d` should work?

**Comment by martanne** [comment]
We could make `^J` insert a literal new line (curently it is mapped to `<Enter>`), while `^V^M` would insert a carriage return. Does that sound reasonable?

**Comment by GregDavidson** [comment]
Yes, that would behave as expected, it would be good!
