### ISSUE TITLE
More checks for terminal size

### ISSUE THREAD

**Issue by TieDyedDevil** [martanne/vis#66]
The check for terminal size looks only at fd 0.

It's possible that some of the standard fds will be redirected; if fd 0 is not a tty, vis is unable to determine the proper terminal size and falls back to the curses default size.

The following patch checks fds 0, 1 and 2. Only if none of these is attached to a tty will vis fall back to the curses default size.

```
diff --git a/ui-curses.c b/ui-curses.c
index 569b2ca..f224e36 100644
--- a/ui-curses.c
+++ b/ui-curses.c
@@ -296,11 +296,18 @@ static void ui_resize_to(Ui *ui, int width, int height) {
 	draw(ui);
 }
 
+static int ui_get_term_ws(struct winsize *ws) {
+	if (ioctl(0, TIOCGWINSZ, ws) == 0) return 1;
+	if (ioctl(1, TIOCGWINSZ, ws) == 0) return 1;
+	if (ioctl(2, TIOCGWINSZ, ws) == 0) return 1;
+	return 0;
+}
+
 static void ui_resize(Ui *ui) {
 	struct winsize ws;
 	int width, height;
 
-	if (ioctl(0, TIOCGWINSZ, &ws) == -1) {
+	if (!ui_get_term_ws(&ws)) {
 		getmaxyx(stdscr, height, width);
 	} else {
 		width = ws.ws_col;
```

**Comment by martanne** [comment]
Thanks! However since the editor interface is always drawn to `stderr` (see the [newterm](https://github.com/martanne/vis/blob/master/ui-curses.c#L594) call) to support stuff like

> echo Hello | vis - | grep World > out

or dvtm's copy mode.

I think it should suffice to check only file descriptor 2. Does this also fix your issue?

**Comment by TieDyedDevil** [comment]
Yes, checking only fd 2 would suffice for any use case I can envision.
