### ISSUE TITLE
FOSDEM 2018

### ISSUE THREAD

**Issue by martanne** [martanne/vis#662]
I will be in Brussel next weekend and give a [lightning talk about vis](https://fosdem.org/2018/schedule/event/vis_editor/).

The presentation isn't finalized yet. Hence, you can still influence it somewhat e.g. by sharing a particular illustrative structural regular expression example or your favourite use case.

Anyway, I thought I would post it here in case anyone will be there too and would like to chat about text editors, operating systems or anything else really.

**Comment by Shugyousha** [comment]
On Sat, Jan 27, 2018 at 7:48 PM, Marc André Tanner
<notifications@github.com> wrote:
> I will be in Brussel next weekend and give a lightning talk about vis.

Sounds good!


> The presentation isn't finalized yet. Hence, you can still influence it
> somewhat e.g. by sharing a particular illustrative structural regular
> expression example or your favourite use case.

Sadly I am not using structural regular expressions on a daily basis
so I can't give you a good example.


> Anyway, I thought I would post it here in case anyone will be there too and
> would like to chat about text editors, operating systems or anything else
> really.

I will be at FOSDEM and will try to make it to your lightning talk.
Should be fun!


Cheers,

Silvan

**Comment by george-b** [comment]
For anyone following this the slides and video are up on https://fosdem.org/2018/schedule/event/vis_editor/

**Comment by martanne** [comment]
Thanks again for showing up, special mentions to the beer/coffee donors.

Also if someone wants to leave feedback either here or via the [FOSDEM feedback form](https://submission.fosdem.org/feedback/6367.php) that would be appreciated.
