### ISSUE TITLE
Make selection highlited in message and command windows.

### ISSUE THREAD

**Issue by uvelichitel** [martanne/vis#663]
Message and command windows perfectly enters Visual mode. I can yank and past from/to registers, which is quite handy.  But selected text is **not** highlited. What's the reason for this restriction and where in src it's implemented?

**Comment by martanne** [comment]
In theory it should work (more or less) like in any "normal" window. At least here it seems to work as expected. Maybe it is specific to your used color theme? Do others also have this problem?

**Comment by uvelichitel** [comment]
You are right. It's about  themes. Works as expected but not with solarized, not huge deal.

**Comment by martanne** [comment]
Closing, this seems to work as is.
