### ISSUE TITLE
Crash in lexer when handling rst file

### ISSUE THREAD

**Issue by MarSoft** [martanne/vis#665]
## How to reproduce
1. Create a `.rst` file with the following content:
```
title
=====

paragraph
```
2. Put cursor to the line with `=` (the one under title), press `o` to add a new line below
3. Press `<Enter>` and type `-- ` (minus, minus, whitespace)
4. Observe the error. New window will be opened to show that error, and any further keypresses will result in the same error being repeated. The only way to exit this situation is to use `Ctrl+Z` and kill `vis` process thus losing any file changes.

## The error

    /usr/share/vis/lexer.lua:1141: invalid position returned by match-time capture

## Additional observations

* You can use `_` (underscore) instead of `-` (minus). Or `=`, or `~`, or any other valid title-delimiting character. The error is still reproduced.
* When you start typing `paragraph`, it will be highlighted as if it was a title until you type it longer than 5 characters (which matches the number of `=` signs under the actual title).
* At the same time, actual `title` text is not highlighted.
* Looks like the lexer respects only "double-delimited" titles (ones with delimiting line both above and below) but not "underlined" ones.
* But anyway, any crash in the lexer should not result in the editor becoming unrecoverable. In the worst case lexer should be disabled... Is there any way to achieve this with current architecture?

```
$ vis -v
vis v0.4-22-g73ef488 +curses +lua +tre +acl
```

**Comment by MarSoft** [comment]
Re-checked with latest master, the problem persists.

    vis v0.4-40-g5963289 +curses +lua +tre +acl

**Comment by lfdebrux** [comment]
I've just hit the same issue using the Ubuntu vis package

**Comment by lfdebrux** [comment]
Was able to reproduce on master `vis v0.5-56-gf8c9f23 +curses +lua`

**Comment by TmpFinger** [comment]
```diff
diff --git a/lua/lexers/rest.lua b/lua/lexers/rest.lua
index 5a968dc..be5b839 100644
--- a/lua/lexers/rest.lua
+++ b/lua/lexers/rest.lua
@@ -28,7 +28,7 @@ local overline = lpeg.Cmt(starts_line(adornment), function(input, index, adm, c)
   return #input + 1
 end)
 local underline = lpeg.Cmt(starts_line(adornment), function(_, index, adm, c)
-  local pos = adm:match('^%'..c..'+()%s*$')
+  local pos = adm:match('^%'..c..'+%s*()$')
   return pos and index - #adm + pos - 1 or nil
 end)
 -- Token needs to be a predefined one in order for folder to work.
```
