### ISSUE TITLE
Shebang support for filetype detection

### ISSUE THREAD

**Issue by vktec** [martanne/vis#667]
Some kinds of files don't have MIME types and might not have file extensions, so allowing detection based on a shebang would be nice.

**Comment by Two-Finger** [comment]
This already works. You may want to take a look at `lua/plugins/filetype.lua`.

The file extension is checked first, if nothing matches then the file is sent to `file(1)`, and if even this doesn't work it sends some bytes to a custom Lua "file type detector" function, which anyone can write.

**Comment by vktec** [comment]
@Two-Finger Oh, interesting. I missed that; should've read in more detail :)
