### ISSUE TITLE
creating a visrc.lua stomps default configuration

### ISSUE THREAD

**Issue by xificurC** [martanne/vis#669]
After a build from source I have solarized theme and syntax highlighting on by default. After creating `~/.config/vis/visrc.lua` I don't have either. Is this expected behavior? I couldn't find what the defaults are and how to set them again if that's what one should do after creating the local configuration file.

**Comment by lanodan** [comment]
I don’t seen to have this issue here (with vis 0.4). What did you put in ``~/.config/vis/visrc.lua``?
An example/template configuration is present in ``/usr/local/share/vis/visrc.lua``.
What you can do is to (re)set the theme in your config, like that:
```lua
require("vis")

vis.events.subscribe(vis.events.WIN_OPEN, function(win)
        vis:command('set theme solarized-16')
end)
```

**Comment by xificurC** [comment]
Thanks, it wasn't clear to me that I need to copy the structure of `/usr/local/share/vis/visrc.lua`. I just created a new file containing `vis:command(...)`. Putting it into the global or WIN_OPEN section solves it.
