### ISSUE TITLE
% does not move to matching ' (quote) or  " (double quotes) 

### ISSUE THREAD

**Issue by slim** [martanne/vis#670]
1. put a " (double quote) under the cursor
2. see matching " (double quote) highlighted
3. press %
4. see cursor does not move to highlighted matching " (double quote)

**Comment by PuercoPop** [comment]
That is the intended behaviour as docuumented in the [man page](http://martanne.github.io/vis/man/vis.1.html) (`% match bracket`). Making `%` match {single,double} quotes is easy, just modify the function bracket_match in vis-motions.c. For example if you want to single quoutes:


```patch
--- a/vis-motions.c
+++ b/vis-motions.c
@@ -176,7 +176,7 @@ static size_t window_nop(Vis *vis, Win *win, size_t pos) {
 }

 static size_t bracket_match(Text *txt, size_t pos) {
-       size_t hit = text_bracket_match_symbol(txt, pos, "(){}[]<>");
+       size_t hit = text_bracket_match_symbol(txt, pos, "(){}[]<>'");
        if (hit != pos)
                return hit;
        char current;
@@ -191,6 +191,7 @@ static size_t bracket_match(Text *txt, size_t pos) {
                case ']':
                case '<':
                case '>':
+               case '\'':
                        return it.pos;
                }
                text_iterator_byte_next(&it, NULL);
```

**Comment by mqudsi** [comment]
Shouldn't this be a configurable option, a la `set matchpairs`?

**Comment by PuercoPop** [comment]
I would favor extending the concept to include pairs as well
