### ISSUE TITLE
Structural Regular Expressions Cheatsheet

### ISSUE THREAD

**Issue by vvug** [martanne/vis#682]
Hello,

I really like `vis`, but I'm very used to vim's regular expressions, and it's difficult to change habits. Having a structural regular expressions cheatsheet, for example in the form of a nice and printer friendly PDF, would really help.

**Comment by erf** [comment]
The [sam tutorial](http://doc.cat-v.org/bell_labs/sam_lang_tutorial/sam_tut.pdf) linked from the [README](https://github.com/martanne/vis/blob/master/README.md) is a good introduction ( there are also other documents linked there). The regular expressions are the same i believe, just use `:x/someregex` to find something and create a selection. vis does not support the substitute command, but use the change command instead, like `:x/findme/c/changetothis`, or `x/deleteme/d` to delete something. Also see the [this](https://github.com/martanne/vis/wiki/Differences-from-Vi(m)) Wiki page explaining differences from vim.

**Comment by vvug** [comment]
The sam tutorial will do. Thanks.

**Comment by erf** [comment]
You could also see the documentation by typing `man vis` - there is a section there on sam commands.
