### ISSUE TITLE
Control-J is identical to Enter

### ISSUE THREAD

**Issue by TieDyedDevil** [martanne/vis#69]
Control-J is the same character as Enter. This affects the binding of MOVE_LINE_DOWN in vis_movements[], which (with the introduction of multiple cursors) is now shadowed by the binding to cursors_new in vis_mode_normal[].

**Comment by martanne** [comment]
Yes this is a [known problem](https://github.com/martanne/vis/issues/42#issuecomment-127013258). Suggestions for better key bindings regarding the multiple cursor functionality are welcome...

**Comment by mrak** [comment]
can you use ncurses' `nonl()` to make `^J` and `^M` differentiable? `dvtm` had the same problem before.

**Comment by martanne** [comment]
Yes, thanks for the hint, this should be fixed now!
