### ISSUE TITLE
zb on last line in a file does nothing

### ISSUE THREAD

**Issue by joshaw** [martanne/vis#697]
`zb` should move the line the cursor is on to the bottom of the screen. When the cursor is on the last line in a file, `zb` does nothing. Move up a line, and it works fine. It doesn't seem to matter whether the last line has a newline terminating it or not.

```
$ for i in {1..100}; do echo line $i; done | vis -
G
zt -> works
zz -> cool
zb -> nothing
k
zb -> now it works
```

**Comment by Two-Finger** [comment]
The change below seems to fix this.

`view.c`:
```diff
@@ -626,7 +626,7 @@ void view_redraw_center(View *view) {

 void view_redraw_bottom(View *view) {
        Line *line = view->selection->line;
-       if (line == view->lastline)
+       if (line == view->height)
                return;
        size_t pos = view->selection->pos;
        view_viewport_up(view, view->height);
```

**Comment by joshaw** [comment]
Thanks. Hadn't got round to testing your solution Two-finger. Thanks martanne.
