### ISSUE TITLE
Substitute command (s/.../.../)

### ISSUE THREAD

**Issue by aksr** [martanne/vis#705]
*(*I apologise if I'm missing something and/or if there's an alternative way to achieve the following.*)*

While (classical) `ed`'s `s` command is not needed in `sam`, `sam`'s variant of `s` command is useful.
Suppose we have a line like this:
```
...a b c 3 3 3 3 3 3 d e f...
```
and if we want to change, for example, the second (or the third or ...) occurrence of 3, 
in `sam` it would be like this:
```
,x s2/3/4/
,x s3/3/4/
...
```
I guess we could find a way (depending on data) to produce this effect with `x`,
but it's much easier (and perhaps more logical) to use `s` command.
The `x`'s way here seems like a kludge.
*Again, If I'm not missing something...*

Also, a following kind of substitution (*addition*) is fairly useful (and familiar):
```
,x... s/smthng/&&&/
```
(But this can be achieved since you implemented `&` for `x` in `vis`.)
(BTW, it seems to me it's not a bad idea.)

I'm not *`s` in sam* apologist, but it has (its niche) use.
Please consider implementing (*restoring*) `s`.

**Comment by martanne** [comment]
Hi, what you want can be achieved by specifying a count for `g` as in:

```
x/3/ g2 c/4/
```
which would replace the second occurrence of 3 with 4.

You might also want to check out the wiki page [listing some differences compared to sam](https://github.com/martanne/vis/wiki/Differences-from-Sam#count-specifier-for-g-and-v-commands) and the relevant [man page section](http://martanne.github.io/vis/man/vis.1.html#Loops_and_conditionals).
