### ISSUE TITLE
Configuring Vis. "Need active window for `:set number`"

### ISSUE THREAD

**Issue by timfayz** [martanne/vis#707]
Hi all.

I'm trying to make the most simple configuration file. I'm not familiar with Lua. So I might mess something around. Here is my config:

```
/home/timur/.config/vis/visrc.lua

require('vis')

vis:command("set number")
vis:command("set autoindent on")
vis:command("set theme base16-grayscale-dark")
```

After running just `vis` from CLI I found two problems: (1) I see `Need active window for :set number` and no line line numbers at left; (2) default theme doesn't change. If I do the same **after** vis is run - everything works perfectly. Can anybody explain what do I wrong?

**Comment by erf** [comment]
You need to set it inside the `WIN_OPEN` event. See included config file.
```
vis.events.subscribe(vis.events.WIN_OPEN, function(win)
	-- Your per window configuration options e.g.
	vis:command('set number')
end)
```

**Comment by timfayz** [comment]
Works perfectly! Thank you a lot :)

I see suckless comunity takes a little Sparta-like approach but it's normal to give a little example how to configure program without just refering using `Lua API` (awesomewm is a good [example](https://awesomewm.org/doc/api/documentation/07-my-first-awesome.md.html)). Only now I've found that there is a little file `lua/visrc.lua` and `/usr/share/vis/visrc.lua` in the binary package which looks similar to "template". At lease, it would be good to mention that file in the man page under `FILES` section with exact path `/usr/share/vis/visrc.lua`.
