### ISSUE TITLE
How to list last :-commands and navigate within?

### ISSUE THREAD

**Issue by timfayz** [martanne/vis#709]
Hello everybody. I'm still in stage of migrating my habits from vim to vis. 
Now I'm trying to find an easy way to list most recently used commands. I expect `^n`/`^p` to loop/cycle as usual way but instead they're literally printed. I also tried to use keyboard arrows which gave me separate window of list. It's better than nothing but I'm still in sense of "incompleteness". Also it's difficult to navigate being at `:` line since most of useful shortcuts are also printed (like ordinary bash `Alt+B`, `Alt+F`, `Ctrl-A`/`Ctrl-E` or `^`/`$` in vis' normal mode). Maybe I missed something?

**Comment by NoctuaNivalis** [comment]
The command window is just an ordinary window, with the exception that hitting enter will not insert a newline but run the current line. This mean you can indeed navigate with the arrow keys, or just hit esc once and navigate with `jk`, or even search with `/`. Hitting esc in normal command mode will leave command mode.

Someone will correct me if I'm wrong.

**Comment by timfayz** [comment]
Hm, that's perfect! :+1:  Indeed if I press `Esc` I can easily navigate if I were in `normal` mode. Why it's not mentioned in vis man page? :( It reminds me finding "easter eggs".. :)
Can I expand recently used commands using something different from arrow keys?
