### ISSUE TITLE
How to change a window size? 

### ISSUE THREAD

**Issue by timfayz** [martanne/vis#710]
Dears,
I didn't find any information about changing the size of opened windows within Vis. I expected something like `Ctrl-w +`/`Ctrl-w -` for height and `Ctrl-w >`/`Ctrl-w <` for width. Is there any? If there is no such thing, it would be great if someone explain that feature or design decision.

**Comment by martanne** [comment]
This is currently not possible, window management is intentionally kept very simplistic because ideally it would be entirely delegated to your regular window manager. #130 is used to track this long term goal.

**Comment by mralusw** [comment]
This would be a little less annoying if these unresizable splits didn't pop up at all (like when requesting help, or when for some reason `vis` decides to expand the command line to an entire window)
