### ISSUE TITLE
lexers: Over-simplified token set

### ISSUE THREAD

**Issue by Javyre** [martanne/vis#714]
I love `vis` and want to make it my new main editor. I started porting my favorite theme over from vim (molokai) manually and realized it would be impossible to have some of the same distinctions in token types as I had in vim.

For example, `.` is considered an operator by scintilla's norm. This would make it impossible to highlight `=` without highlighting `.` all over the place.
There are many other places where I believe finer-grain token types would not hurt to have.

I would be ready to port some of the lexers to more fine-grained token sets if this turns out to be the solution to this issue.

I'd like to know what others think about this as well. Does this only seem weird to me?

**Comment by mcepl** [comment]
@ninewise, this should probably be sent upstream to https://github.com/orbitalquark/scintillua/issues, right?
