### ISSUE TITLE
ruler and line numbers

### ISSUE THREAD

**Issue by wthurein** [martanne/vis#72]
With current head on OS X 10.10:
1. the ruler (row, col) doesn't get updated until ':' is pressed;
2. are line numbers window-local?
(They disappear from top/left when window is split, except for C/C++ files.)

**Comment by greduan** [comment]
Oh can you provide steps to compile on OS X? I know how to on BSD and Linux but haven't tried on OS X.

**Comment by wthurein** [comment]
I just had to 'make'. That's all.

**Comment by greduan** [comment]
Oh. I thought there'd be stuff to install or something. Cool. Thanks. :) :P

**Comment by martanne** [comment]
Thanks for the report! I plan to overhaul parts of the editor display code and will try to fix these issues while doing so.

As for the options, yes the line numbers are currently window local. At some point all existing options need to be reviewed whether they should apply to all windows or just the currently active one.
