### ISSUE TITLE
Support Semantic Highlighting

### ISSUE THREAD

**Issue by HalosGhost** [martanne/vis#721]
[Semantic Highlighting](https://medium.com/@evnbr/coding-in-color-3a6db2743a1e) is the concept that syntax highlighting groups of keywords actually does not necessarily provide a significant amount of information; or, at the very least, that there is more helpful information that could be provided by color-coding.

In particular, giving each identifier its own color (perhaps scope-limited) lets you identify, at a glance, where a particular variable is being used, which (at least in the opinion of some) can be more useful.

There is an implementation available for [vim](https://github.com/jaxbot/semantic-highlight.vim) that might offer a good starting point.

**Comment by mcepl** [comment]
@ninewise, this is probably irrelevant now when we switched to the Scintillua lexers, right?

**Comment by ninewise** [comment]
Scintillua lexers still use syntactical highlighting, not semantic highlighting. That said, semantic highlighting is something vis probably won't do, since we'd need to interpret languages. This could perhaps be part of the LSP-plugin.

**Comment by mcepl** [comment]
@rnpnr Isn’t this something for a plugin or outside of the scope of the project right now?

**Comment by rnpnr** [comment]
Yep I think this is best kept as a separate plugin.
