### ISSUE TITLE
Performance issues in YAML highlighting

### ISSUE THREAD

**Issue by peaceant** [martanne/vis#726]
Hello.

I'm editing .yml file (link below) in vis editor and the performance is really terrible. Scrolling and editing text is really laggy. Why is that? It's only 286 lines of yaml code. I'm editing in vis editor 500000 lines of xml code with better peformance.

[custom-theme.yml](https://github.com/peaceant/perf-vis/blob/master/custom-theme.yml)

**Comment by Shugyousha** [comment]
Hi

On Wed, Aug 08, 2018 at 12:26:26AM -0700, Martin Radimec wrote:
> I'm editing .yml file (link below) in vis editor and the performance
> is really terrible. Scrolling and editing text is really laggy. Why
> is that? It's only 286 lines of yaml code. I'm editing in vis editor
> 500000 lines of xml code with better peformance.

Yes, there seem to be some issues with the syntax highlighting in some
cases. Big XML files show similar symptoms.

> [custom-theme.yml](https://github.com/peaceant/perf-vis/blob/master/custom-theme.yml)

I have recorded some perf sample data showing where the time is spent
when scrolling around in the file in vis. Interestingly enough, the
farther down you scroll, the slower everything gets.

The perf data indicates that most of the time is spent in the lua string
matching functions. The recorded perf data can be downloaded from
[here](https://sillymon.ch/data/perf-data-for-custom-theme-yml.data.gz).

I wanted to create a flame graph from the perf data but the flamegraph
scripts didn't work. I wonder if there is another way to get an easier
interpretable view of the data.

**Comment by lanodan** [comment]
Maybe one way would be to have a configurable limit to syntax highlighting depending on something like the file size.

**Comment by erf** [comment]
I also noticed it now when scrolling down to the end of [this file](https://github.com/tmcdonell/config-alacritty/blob/master/alacritty.yml)

**Comment by TmpFinger1** [comment]
For YAML, you can try [this patch](https://repo.or.cz/vis/gkirilov.git/blobdiff/9eff1bc595a465572f79bfcb5c9e1ccf1f4a65b7..0cc2a5be96ebffe262842ca5751df8ee816fb430:/lua/lexers/yaml.lua).

It is only some of the lexers that have terrible performance. It's the way they are written - they ignore the "horizon" and re-read the whole file from the very beginning, multiple times.

**Comment by erf** [comment]
@peaceant i believe 79859b57fc3556c2ed74950a5a5668c64face4e3 solved this issue

**Comment by rokf** [comment]
Can confirm that it seems to be fixed with the commit @erf mentioned. I've tested it with the `custom-theme.yml` file linked above.

Have to test this with various OpenAPI and k8s specifications :+1:

**Comment by martanne** [comment]
I'm closing this for now as the imminent issue making the editor unusable seems fixed. Highlighting improvements can be contributed separately.

@TmpFinger1 do you have any further changes? Do you also want to look into the XML issue #603?

**Comment by wesleyae** [comment]
This is still a problem with yaml. Interestingly, I noticed it's only slow if I have a visrc.lua file set up. When I commented everything in my ~/.config/vis/visrc.lua, the performance of vis was better.
