### ISSUE TITLE
Explicitly loading a configuration file

### ISSUE THREAD

**Issue by Vintodrimmer** [martanne/vis#729]
Good day, is there a way to "force feed" Vis a configuration file?

I've made a fresh Gentoo installation and Vis seems to ignore the `visrc.lua` and show no syntax highlighting. I tried setting `VIS_PATH` to the `~/.config/vis/` but that didn't help.

**Comment by sham1** [comment]
The Gentoo version of vis is compiled without Lua support, because I don't think they can update their Lua version to be high enough to support vis. Something about other packages breaking and such.

**Comment by Vintodrimmer** [comment]
That's unfortunate, perhaps Gentoo is in a sadder state than I thought.

Thank you for clarification!
