### ISSUE TITLE
How to colorize every second row?

### ISSUE THREAD

**Issue by octos** [martanne/vis#73]
Would it be possible to write a rule that would highlight every second row?

**Comment by martanne** [comment]
No this is currently not possible without directly modifying the display code. I'm thinking about redesigning the way syntax highlighting is implemented. With the new scheme it might be possible to do such things without having to change the C code ...

**Comment by martanne** [comment]
If you want to give the lua branch a try, it supports the `:set cursorline` command/setting which might be of interest to you. The [corresponding commit](https://github.com/martanne/vis/commit/57c1eedad877646c63147ab437a1acc56b159c46) should give you an idea how your desired functionality could be implemented...
