### ISSUE TITLE
Usage information for command

### ISSUE THREAD

**Issue by notramo** [martanne/vis#731]
When a command is typed, but not accepted yet, `vis` should automatically display  usage information for the command in a help box. See how the [Kakoune](http://kakoune.org/) editor does it.

**Comment by martanne** [comment]
I don't particularly like these kind of interactive distractions, therefore it is unlikely that this functionality will be included in the core anytime soon. For now we should probably focus on improving the existing documentation e.g. the man page. I agree though that we should provide the necessary Lua APIs to enable such a feature as an extension.
