### ISSUE TITLE
set terminal title to current file

### ISSUE THREAD

**Issue by erf** [martanne/vis#732]
Is there a way to set terminal title to the current open file in vis?

I know you can set a title like this in bash: 
`PROMPT_COMMAND='echo -ne "\033]0;YOUR TITLE GOES HERE\007"'`

**Comment by lanodan** [comment]
I’m pretty sure this can be done by a vis plugin.

**Comment by erf** [comment]
I got it working using the following in `visrc.lua`:
```
vis.events.subscribe(vis.events.WIN_OPEN, function(win)
  vis:command(string.format(":!echo -ne '\\033]0;%s\\007'", win.file.name))
end)
```

**Comment by erf** [comment]
I made a simple [plugin](https://github.com/erf/vis-title) for this
