### ISSUE TITLE
Add Lua event for switching active window

### ISSUE THREAD

**Issue by erf** [martanne/vis#733]
Add event for switching active window.
```
vis somefile.txt
ctrl+w v ( split screen )
ctrl+w ctrl+w ( go to other screen should output event with current active window )
```

**Comment by erf** [comment]
i can't remember my use case for this now, but perhaps someone would find it useful, but feel free to close this

**Comment by TmpFinger1** [comment]
You can use the WIN_STATUS event instead:

```lua
local last_win
vis.events.subscribe(vis.events.WIN_STATUS, function(win)
	if win == vis.win and last_win ~= win then
		vis:info"window changed"
		last_win = win
	end
end)
```

A similar approach can be used for mode-change, syntax-change and other things.

**Comment by erf** [comment]
thanks, good tip. will close this for now
