### ISSUE TITLE
Some tabs collapse when the line is selected

### ISSUE THREAD

**Issue by mqudsi** [martanne/vis#734]
Sorry for the awkward issue title, but I'm not sure how else to describe the problem I'm facing.

Here's an asciinema of the bug:
https://asciinema.org/a/20wjrcSX4fpeueSiSpLkkn8UF

Basically some lines with a leading tab have the tab collapsed when the cursor (in normal mode) is placed on that tab.

**Comment by rnpnr** [comment]
Closing since we have no way to reproduce and no way of even seeing what the problem is. Feel free to reopen with more info.
