### ISSUE TITLE
multiline f/t

### ISSUE THREAD

**Issue by aeosynth** [martanne/vis#735]
https://github.com/martanne/vis/wiki/FAQ#what-are-structural-regular-expressions

> The main insight [of sam] is that text editing should not be artificially limited by the concept of a line.

the `f` and `t` motions only search for characters on the current line; instead, it should work across lines. Multiple vim plugins exist to add this behavior, and kakoune supports it by default.

**Comment by martanne** [comment]
As mentioned in #915, with adf65e1dca8d3c0381133be8446eebddf412d772 it should be possible to add mappings which provide the multi line functionality.
