### ISSUE TITLE
Why VIS_PATH and not VISPATH?

### ISSUE THREAD

**Issue by adriangrigore** [martanne/vis#736]
Why is the environment variable named `VIS_PATH` and not `VISPATH` to be closer to the other path variables in [POSIX](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html) like `CDPATH`, `MAILPATH`, `MANPATH`, `NLSPATH`?

**Comment by martanne** [comment]
I used `VIS_` as a prefix in anticipation that there might be more environment variables needed in the future. An example from POSIX would be `LC_` for the locale related stuff.

Even if `VISPATH` is preferable, changing it at this point and possibly breaking existing installation is not worth the trouble.
