### ISSUE TITLE
set softtabstop

### ISSUE THREAD

**Issue by pjfichet** [martanne/vis#738]
Hello,

When using `set expandtab 4`, it is handy to may delete all four spaces with a single backspace. Vim has
an option for this:  `set softtabstop 4`.

Could this be implemented in vis?
Or is there a trick to achieve the same effect?

Thank you!

**Comment by NoctuaNivalis** [comment]
Well, `<<` already removes multiple spaces when `expandtab on` is set, but I agree removing spaces until the previous tabstop with backspace would be a handy option, too.

**Comment by ydschneider** [comment]
I had the same issue and worked around it with this in my visrc.lua:
```lua
vis.events.subscribe(vis.events.INIT, function()
    local tabwidth = 4
    vis:command('set tabwidth ' .. tabwidth)
    vis:command('set expandtab')
    vis:map(vis.modes.INSERT, '<Backspace>', function()
       local found_tab = true
       for selection in vis.win:selections_iterator() do
           local pos = selection.pos
           if not pos or pos < tabwidth or vis.win.file:content(pos - tabwidth, tabwidth) ~= string.rep(' ', tabwidth) then
               found_tab = false
               break
           end
       end
       vis:feedkeys(string.rep('<vis-delete-char-prev>', found_tab and tabwidth or 1))
    end)
...
```

**Comment by pjfichet** [comment]
Thanks ydschneider, that's what I was looking for.

**Comment by theamazingwaffle** [comment]
since the issue isn't closed, I would like to share my opinion on softtabstop  
when i was a vim scrub i just copied and pasted some "standard" settings for vim  
there was softtabstop in there as well. When i just wanted to delete one space i always deleted 4 instead and i burned in hell, filled with agony, thinking that it was a vim quirck and that i have to deal with it.  
Thanks random stranger for helping me understand what i did to myself back then.

**Comment by ninewise** [comment]
Since this issue I've modified the snippet above slightly, so it remove tabs up to a multiple of tabwidth spaces:

```lua
vis:map(vis.modes.INSERT, '<Backspace>', function()
	local tabwidth = 4
	local single_selection = false
	for selection in vis.win:selections_iterator() do
		if single_selection then
			single_selection = false
			break
		end
		single_selection = true
	end

	local to_stop = (vis.win.selection.col - 1) % tabwidth
	if to_stop == 0 then
		to_stop = tabwidth
	end

	if single_selection and to_stop > 1 and vis.win.file:content(vis.win.selection.pos - to_stop, to_stop) == string.rep(' ', to_stop) then
		vis:feedkeys(string.rep('<vis-delete-char-prev>', to_stop))
	else
		vis:feedkeys('<vis-delete-char-prev>')
	end
end)
```

The closing of this issue is up to @pjfichet.

**Comment by pjfichet** [comment]
Oups, sorry, I did not know it was me who had to close this. It's solved, indeed.

Thank you all!
