### ISSUE TITLE
Support/Expose xf86 keysyms

### ISSUE THREAD

**Issue by HalosGhost** [martanne/vis#742]
I can happily map functions to various keys, including function keys, but I cannot, at the moment map keys to xf86 keysyms (e.g., ``XF86AudioPlay``, the one I was trying to bind when I ran into this issue). My laptop at ``$DAYJOB`` has its function key row mapped to various xf86 actions (with a function key allowing for a fallback to the standard F keys). It would be lovely if I could bind my unused xf86 keys to functions in `vis` so that I can call them without needing to hold another key.

The full list of xf86 keysyms can often be found in [``/usr/include/X11/XF86keysym.h``](https://cgit.freedesktop.org/xorg/proto/x11proto/tree/XF86keysym.h).

**Comment by martanne** [comment]
Hi, vis is currently a console application and adding a X11 dependency is undesirable. You should probably configure your terminal emulator to map the special keys to ones understood by libtermkey. See the "Symbolic keys"  section in the `:help` output for a list of keys you could use.

**Comment by HalosGhost** [comment]
I fully understand not wanting to add a hard X11 dependency; would an optional dependency / compile-time option be unreasonable as a solution?

**Comment by HackedPixels** [comment]
Yes.  Generally Compile time features tend to complicate the code unnecessarily. 
Also vis would have to handle two input methods; libtermkey and X.

**Comment by HalosGhost** [comment]
Fair enough. Just wanted to see if that was a reasonable option. I will look into mapping my xf86 keys with libtermkey. Thank you both!
