### ISSUE TITLE
Vi parity feature: cursor placement on end of line

### ISSUE THREAD

**Issue by hholst80** [martanne/vis#747]
Suppose you have a file with the contents `foo` (with or without EOL it is no importance).
When you open up the file you can place the cursor (in normal mode) AFTER the second `o` as illustrated below (`#` = cursor).

```
foo#
```

The correct way imho would be to limit the cursor to standing on top of the last `o` and if I want to add text AFTER I press `a` as we all have been thought in Vi-school.

**Comment by miles-canfield** [comment]
This is actually the desired behavior. Newline characters are directly addressable in vis. Pressing `x` while the cursor is in that position will delete the newline character. See: https://github.com/martanne/vis/wiki/Differences-from-Vi(m)

**Comment by hholst80** [comment]
Fair enough. You seem to have thought about this so I will sharpen my arguments or adapt to the new way of thinking. I will close this bug report.

**Comment by TmpFinger** [comment]
@hholst80 here's what I use to make it work like in vi(m):
```lua
vis.events.subscribe(vis.events.INIT, function()
	-- Your global configuration options
	vis:map(vis.modes.NORMAL, '$', '<vis-motion-line-end><vis-motion-char-prev>')
	vis:map(vis.modes.VISUAL, '$', '<vis-motion-line-end><vis-motion-char-prev>')
end)
```

**Comment by benhormann** [comment]
Use line-char to handle blank lines:
```lua
vis:map(vis.modes.NORMAL, '$', '<vis-motion-line-end><vis-motion-line-char-prev>')
vis:map(vis.modes.VISUAL, '$', '<vis-motion-line-end><vis-motion-line-char-prev>')
```
