### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by vvug** [martanne/vis#748]
No commits since May 2018... How is the status of this project?

**Comment by erf** [comment]
@martanne please let us know you are ok, we miss you

**Comment by hholst80** [comment]
![image](https://user-images.githubusercontent.com/6200749/51365932-1b558a80-1ae3-11e9-8f5c-25f99ac3b46c.png)

Anyone asked on IRC?

**Comment by ninewise** [comment]
@hholst80 he hasn't been there for some time (absent since 2018-12-03 according to my logs, last activity 2018-10-28).

@vvug so the status is the same as in May 2018. While I do worry about martanne (as a person) I don't worry about the project. The code is rather stable imho. I know software is never finished, but current vis works for me.

**Comment by vvug** [comment]
@ninewise I didn't realize @martanne was missing in general. Then yes, I hope we will ping us soon, regardless of the project

Vis works fine for me too, but as you say software is never finished. Look at the number of issues/PRs.

**Comment by erf** [comment]
I like how the author of [Kitty](https://github.com/kovidgoyal/kitty) handles issues. Usually most issue are non-issues and can be closed.

**Comment by Shugyousha** [comment]
I also hope @martanne is okay! After being so productive I can understand
if he wants to take a break though...

[2019-01-17 14:12] erf <notifications@github.com>
>
> @martanne [https://github.com/martanne] please let us know you are ok,
> we miss you

**Comment by tonchis** [comment]
I sincerely hope @martanne is doing ok, and that we get to hear from him soon. We miss you!

I still use `vis` as my daily text editor and I agree it's pretty stable.

**Comment by martanne** [comment]
Hi, sorry for the radio silence. I'm fine, for some definition of fine. I was just really busy and then decided to take off some time and limit computer presence to a minimum.

As for the state of vis, it is in a kind of strange place. It mostly works, but I would eventually like to rethink a few things. However, I feel that invasive changes are best done in a contiguous block of time. In practice that means things get delayed indefinitely.

Unfortunately the next 6 months will most likely again be rather hectic, but I will try to fit in at least basic maintenance tasks.

**Comment by Shugyousha** [comment]
[2019-02-20 03:51] Marc André Tanner <notifications@github.com>
> Hi, sorry for the radio silence. I'm fine, for some definition of
> fine. I was just really busy and then decided to take off some time
> and limit computer presence to a minimum.

No problem! Glad to hear that you are doing okay!


Cheers,

Silvan

**Comment by erf** [comment]
@martanne Happy Xmas and best wishes for 2020
