### ISSUE TITLE
multi-cursor tutorial/introduction

### ISSUE THREAD

**Issue by ghost** [martanne/vis#751]
Is there some tutorial/explanation/something on the multi-cursor functionality?   It doesn't have to be much, but I am completely failing to wrap my head around it and I don't even know where to begin.  Which is frustrating the hell out of me since I love the idea of this editor and desperately want to use it, but at my current ability it's less capable than vim. :/

**Comment by PuercoPop** [comment]
It's explain in the manual and on the :help. The easiest way to get multiple cursors is to use the x command to place a cursors on each match. Ej. `x/const` will select all const keywords in the file. Another way is to use C-n to select the next match of the word currently at point. The multiple selection section of the manual has more shortcuts. Martens also gave a short demo of the editor at the past FOSDEM https://m.youtube.com/watch?v=y41MyOrPt8Q

Hope that helps

**Comment by egency** [comment]
I have read the manual, hence me being here.  I mostly understand the use of `x/const` and some of the funky manipulations one can do with that.  All of that is cute and all, I however would like to do something simple, as an example, block select in vim.  I'm not having a failure of reading, and I'm very well acquainted with the flashy examples shown at FOSDEM (and elsewhere).  I'm having a failure of understanding the basics, in particular since I do the basics more frequently and I usually notice the patterns better.

**Comment by ninewise** [comment]
Block select I mostly replaced with <ctrl-j>'ing down some lines and editing them at the same time. And that's probably my most common use of multiple cursors.

**Comment by qstrejo** [comment]
You can block select using V.

**Comment by erf** [comment]
You can also select some lines in visual mode and press `I` to add a cursor to each line.

**Comment by egency** [comment]
V is line select.

I guess the part that I can't seem to wrap my head around is using/manipulating the cursors themselves.  With something like block select you don't really have much flexibility at all, but the limitations, uses, and how to manipulate all of this is fairly obvious.

With multiple cursors I don't know.  As a stupid example, can one take something like this:
|a| |b| |c|
|a| |b| |c|

(note that each spans multiple lines) and turn it into this:
|a|
|a|
|b|
|b|
|c|
|c|

I know that with block select it's a long and laborious process where one takes each individual block, make a space for it, past it, etc, etc.  But how would one do it using multiple cursors?

I don't know whether this explains what I'm after any better at all, but I guess, what are the mechanics of multiple cursors?  Using it as a fancy block select is fine and all, but how does it work?  If I made a mistake placing one cursor can I move just that one?  Can it solve the above copy paste job elegantly?

Does this make more sense?

I'm sorry for taking up so much of everybody's time and the answers here have been very helpful so far, so thank you all. :) This community is great!

**Comment by erf** [comment]
@egency you could press `C-j` to create two cursor at the start of the two lines. Then press `W` go go to start of `|b|`, then press `dW`, to delete the two `|b| `s. Then press `jjp`, to go down two lines and paste  ( as long as you have new lines at bottom ). Then press `kklD`, to go up, right and delete the `|c|`s, then down again and paste them. This is a simple and visual way of working with the multiple cursors. Just as you would do in vim, only with two cursors. I'm sure there is a more clever way to do this.

**Comment by egency** [comment]
Okay, that makes sense, thank you! :)  Another question if I may, I noticed that if one modifies the example slightly to:
|a| |b| |c|
|a| |b| |c|

-------------

Instead and one goes `C-j C-j dWjj` the bottom cursor will be at column 5 instead of column 1 as I sort of expected.  There also seems to be a sort of "privileged" (for lack of better term) cursor from which the column number gets determined and which is highlighted.  What are the significance/implications of these observations?

**Comment by ninewise** [comment]
I can't follow your example, could you put it in a code block (with "```") so I can get the exact file?

There is indeed a "primary selection". This is the one that will remain when you escape from multiple cursors to a single cursor, and will control movement. When you e.g. `C-j`, it will create a new selection on the line below the primary selection. (Try it out with a file with 5 empty lines, start on line 3 and press `C-j`, `C-j`, `C-k`, `C-k`, `C-k`.)

**Comment by egency** [comment]
Pardon I don't know markdown very well and failed to properly check the result:
```
|a| |b| |c|
|a| |b| |c|

-----------
```

**Comment by qstrejo** [comment]
Use V to select both lines, then x/ /c/\n/

**Comment by erf** [comment]
@qstrejo i also thought of that first but that would result in:
```
|a|
|b|
|c|
|a|
|b|
|c|
```
not
```
|a|
|a|
|b|
|b|
|c|
|c|
```

**Comment by qstrejo** [comment]
Ahh, in that case use x/ /c/\n/, then use V to select all those lines and then | sort, to call the sort command on the selection.

**Comment by erf** [comment]
@qstrejo that's a cool trick :)

**Comment by slve** [comment]
My solution is to zip the second line, then repeat this zip method on the subsequent lines, at the end wrap the line that's been built up.
![out](https://user-images.githubusercontent.com/20797303/53049343-c369c500-348e-11e9-92d7-a62d224436c0.gif)

Prepare
`:x/^/ c/ /↵` insert space before the first column
`:1x/\>↵` select the word endings in the first line
`m` save the cursors

Zip
`qq` record macro to register "q"
`:2x/ /↵` select spaces in the second line
`ex` extend selections to the word endings and cut them to the clipboard
`MP` restore the previously saved cursors and paste the clipboard before them
`lm` move cursors right and save the cursors
`<Esc>:2d↵`  back to normal mode and delete the second line
`kq` go back to first line and stop recording

Repeat
`3@q` repeat macro "q" 3 times

Finish
`Mi↵` restore the latest cursors and break lines

Tear down
`<Esc><C-k>x<Esc>` back to normal mode, extend selection upwards, cut spaces

**Comment by ninewise** [comment]
Smart use of saving the cursors, right there. That's probably the best way to do it.

**Comment by martanne** [comment]
I agree that the documentation should eventually be improved, but you at least got some pointers and usage examples. I am closing this for now.
