### ISSUE TITLE
Failed attempt to reimplement vim syntax highlighting

### ISSUE THREAD

**Issue by KAction** [martanne/vis#754]
I just tried to evaluate, whether vis could replace vim for my needs. I
tried to write syntax highlighting for debian changelog. Here is one
entry of typical changelog:

	dvtm (0.15-4) unstable; urgency=medium

	  * Fix typo in package description (s/it's/its)
	  * Build-depend on `debhelper-compat' (obsoletes `debian/compat')
	  * Bump standards version to 4.2.1 (no changes needed)
	  * Update Vcs-* fields in debian/control.

	 -- Dmitry Bogatov <KAction@debian.org>  Sat, 24 Nov 2018 21:34:36 +0000

I tab-indented example, all spacing (two spaces before stars, no spaces
before 'dvtm', single space before --) are all of essence.

I wanted version \([0-9.+-a-z]+\) to be highlighted in version line, but
not in other lines. Version line is well-distinguished by non-space
symbol in zero column. But seems that equivalent of Vim's region
start/stop in lpeg not only much more verbose, but also strictly less
powerful. Here is my attempt:

	local l = require('lexer')
	local token, word_match = l.token, l.word_match
	local P, R, S, B = lpeg.P, lpeg.R, lpeg.S, lpeg.B

	local M = { _NAME = 'debchangelog' }

	function mk_vline ()
	  local L = { _NAME = 'version-line' }
	  local pkgname = l.starts_line(R("az")) * (R("az") + S("+-"))^1 * l.space
	  local version = B(l.space) * "(" * (R("09", "az") + S("+-."))^1 * ")"
	  local known_dists = B(l.space) * word_match { "experimental", "unstable" }
	  local known_urgencies = B('urgency=') * word_match { "low", "medium", "high" }
	  local sc = #P(';')
	  
	  L._rules = {
	    {'pkgname',       token(l.VARIABLE, pkgname)          },
	    {'version',       token(l.CLASS, version)             },
	    {'known-dist',    token(l.CONSTANT, known_dists * sc) },
	    {'unknown-dist',  token(l.ERROR, l.word * sc)         },
	    {'urgency',       token(l.KEYWORD, P('urgency='))     },
	    {'urgency-value', token(l.TYPE, known_urgencies)      },
	  }
	  return L
	end
	vline = mk_vline()
	l.embed_lexer(M, vline, #P('dvtm'), P(';'))
	M._rules = {
	  {'closes', token(l.KEYWORD, 'Closes')},
	}
	return M

As you can see, I created seperate lexer for version line (equivalent of
`contained') and used `embed_lexer'. Here I even hardcoded name of
package, but it is not the point. Lpeg insist, that start_tag pattern
has non-empty width. Code showed results in error:

	..../share/vis/lexer.lua:989: empty loop in rule 'debchangelog'

As related note, it is possible for rules to overlap in Vim, but not in
lpeg. The fact, that upstream lexers for perl does not hightlight
variables in strings:

	print "Hello $world"

suggests that lpeg expressions are actually not powerful enough.

**Comment by martanne** [comment]
Hi, I think your approach is a bit over-engineered. Are you aware that one rule can contain multiple tokens?

Something like the following should highlight the individual components. Although, if the version line is malformed (i.e. not matched) then nothing on the line will be colored.
 
```lua
local l = require('lexer')
local token, word_match = l.token, l.word_match
local P, R, S = lpeg.P, lpeg.R, lpeg.S

local M = { _NAME = 'debchangelog' }

local separator = l.space^1
local pkgname = token(l.VARIABLE, l.starts_line(R("az")) * (R("az") + S("+-"))^1)
local version = token(l.CLASS, "(" * (R("09", "az") + S("+-."))^1 * ")")
local dists = token(l.CONSTANT, word_match { "experimental", "unstable" } * ";")
local urgencies = token(l.TYPE, P('urgency=') * word_match { "low", "medium", "high" })

local version_line = pkgname * separator * version * separator * dists * separator * urgencies
local author = token(l.COMMENT, l.starts_line(P(" --")) * l.nonnewline^0)

M._rules = {
  {'version_line', version_line },
  {'author', author },
}

return M
```

In any case, we are currently in the process of upstreaming our lexer changes to the [Scintillua project](https://github.com/orbitalquark/scintillua), see also #916 and #908. Please contribute it there, maybe @orbitalquark also has a suggestion on how to best handle it.

The string interpolation issue you mentioned has already an individual issue: #862. Maybe upstream also has an opinion on that topic?
