### ISSUE TITLE
rc lexer fails to identify $$* as a variable

### ISSUE THREAD

**Issue by Nomarian** [martanne/vis#757]
Fix

`
-- Variables.
local variable = token(l.VARIABLE,
 P('$')^1 * S('"#^')^-1 * ('*' + l.digit^1 + l.word)
)
`

**Comment by theamazingwaffle** [comment]
if you fixed it then maybe close the issue?

**Comment by Nomarian** [comment]
There's the patch but its not merged... and apparently it never will be, so closed anyway.
