### ISSUE TITLE
error

### ISSUE THREAD

**Issue by letarg0** [martanne/vis#760]
armbian

$make
cp config.def.h config.h
cc          -std=c99 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -DNDEBUG -DVERSION=\"v0.5-56-gf8c9f23\" -DHAVE_MEMRCHR=0 -DVIS_PATH=\"/vis\" -DCONFIG_HELP=1 -DCONFIG_CURSES=1 -DCONFIG_LUA=1 -DCONFIG_LPEG=0 -DCONFIG_TRE=0 -DCONFIG_SELINUX=0 -DCONFIG_ACL=0  array.c buffer.c libutf.c main.c map.c sam.c text.c text-motions.c text-objects.c text-util.c ui-terminal.c view.c vis.c vis-lua.c vis-modes.c vis-motions.c vis-operators.c vis-registers.c vis-marks.c vis-prompt.c vis-text-objects.c text-regex.c          -lc -o vis
In file included from ui-terminal.h:4:0,
                 from main.c:13:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
In file included from vis.h:12:0,
                 from sam.h:4,
                 from sam.c:26:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
In file included from text.c:28:0:
util.h:28:14: error: static declaration of ‘memrchr’ follows non-static declaration
 static void *memrchr(const void *m, int c, size_t n)
              ^~~~~~~
In file included from text.c:7:0:
/usr/include/string.h:117:14: note: previous declaration of ‘memrchr’ was here
 extern void *memrchr (const void *__s, int __c, size_t __n)
              ^~~~~~~
In file included from ui-terminal.h:4:0,
                 from ui-terminal.c:16:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
In file included from view.h:11:0,
                 from view.c:7:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
vis.c:21:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
In file included from vis-lua.c:24:0:
vis-lua.h:5:17: fatal error: lua.h: Nie ma takiego pliku ani katalogu
 #include <lua.h>
                 ^
compilation terminated.
In file included from vis.h:12:0,
                 from vis-core.h:5,
                 from vis-modes.c:3:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
In file included from vis.h:12:0,
                 from vis-core.h:5,
                 from vis-motions.c:4:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
In file included from vis.h:12:0,
                 from vis-core.h:5,
                 from vis-operators.c:3:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
In file included from vis.h:12:0,
                 from vis-core.h:5,
                 from vis-registers.c:4:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
In file included from vis.h:12:0,
                 from vis-core.h:5,
                 from vis-marks.c:1:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
In file included from vis.h:12:0,
                 from vis-core.h:5,
                 from vis-prompt.c:2:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
In file included from vis.h:12:0,
                 from vis-core.h:5,
                 from vis-text-objects.c:1:
ui.h:6:21: fatal error: termkey.h: Nie ma takiego pliku ani katalogu
 #include <termkey.h>
                     ^
compilation terminated.
Makefile:61: polecenia dla obiektu 'vis' nie powiodły się
make: *** [vis] Błąd 1

**Comment by ninewise** [comment]
Looks like you're missing some header files. Either fixing your paths or installing `libtermkey-dev` and some lua `-dev` package should help.

If it doesn't, could you format and translate the output, so I can read it?

**Comment by martanne** [comment]
You should make sure `configure` runs without errors to check that all mandatory dependencies are met.

Closing this as user error.
