### ISSUE TITLE
Every time you update the "network" shape always changes, how can you make the shape unchanged?

### ISSUE THREAD

**Issue by itpwuwei** [martanne/vis#762]

**Comment by itpwuwei** [comment]
Every time you update the "network" shape always changes, how can you make the shape unchanged?

**Comment by theamazingwaffle** [comment]
i will not help, but for others you need to provide a more detailed description of your issue, in as few words as possible.

**Comment by martanne** [comment]
I'm not sure what you mean by "network shape", closing due to missing information.
