### ISSUE TITLE
Is the vis editor still being developed?

### ISSUE THREAD

**Issue by nostdm** [martanne/vis#768]
Looking at the sparse commit history and quite a few outstanding issues still open I would assume that the author is no longer actively working on this project. Are there any future development plans for the vis editor? I couldn't find any information here regarding future goals.

**Comment by ninewise** [comment]
See #748.

**Comment by nostdm** [comment]
@ninewise Great, thanks that answers the question. Do any other developers have merge rights / review PRs or only @martanne? 

Closing the issue.

**Comment by ninewise** [comment]
AFAIK only martanne has write access on this repository. Everyone can review PR's though, to make it easier for martanne when he takes a look.
