### ISSUE TITLE
Override redraw-center at file bottom

### ISSUE THREAD

**Issue by 3dc1d3** [martanne/vis#772]
Currently doing `vis +$` to hit end of file results in last line being centered in the terminal window - how can I override this and draw the bottom line at the bottom of the screen?

Neither `vis +zb` nor `vis +vis-window-redraw-bottom` worked.  Ideally I'd like to avoid having to add a custom command in either `config.h` or `visrc.lua`.

Is there a `vis +action:vis-window-redraw-bottom` or similar?

**Comment by martanne** [comment]
No, you will have to modify `visrc.lua`

```lua
vis.events.subscribe(vis.events.START, function()
    vis:feedkeys('<vis-motion-line-last>')
    vis:feedkeys('<vis-window-redraw-bottom>')
    -- or if you don't mind depending on the currently used default bindings
    vis:feedkeys('Gzb')
end)
```

Is this not good enough?

**Comment by 3dc1d3** [comment]
It's not good enough because I don't always want that behaviour, only when invoked by `dvtm-editor`.

I added `{ "dvtm-editor", "+zb" }` to my `config.h` which didn't work, hence my question.

Eventually after some digging I found that `dvtm` sends key events, not arguments, to `dvtm-editor` so I just had to remove the '+'.

**Comment by martanne** [comment]
Ok, but I think you should already be able to hack something together using the existing Lua functionality. This is also a duplicate of #612.

**Comment by 3dc1d3** [comment]
Thanks for the link, will be handy for the future.
