### ISSUE TITLE
[Lua-API] Bug in file_save_post(file, path): file.path != path

### ISSUE THREAD

**Issue by seifferth** [martanne/vis#773]
The [lua docs](http://martanne.github.io/vis/doc/#Core_Events) state that both `file_save_post` and `file_save_pre` expose `file` and `path` where `path` is the full path to the file being written. If I open vis without specifying a filename, however, and then run `:w filename`, the respective variables don't seem to be set to the correct values.

Here's a small `visrc.lua` you can use to confirm this behaviour:

```lua
require "vis"

vis.events.subscribe(vis.events.FILE_SAVE_PRE, function (file, path)
  print()
  print("FILE_SAVE_PRE file.path is:") print(file.path)
  print("FILE_SAVE_PRE path is:") print(path)
end)

vis.events.subscribe(vis.events.FILE_SAVE_POST, function (file, path)
  print()
  print("FILE_SAVE_POST file.path is:") print(file.path)
  print("FILE_SAVE_POST path is:") print(path)
end)
```

I get the following output when running `:w filename` (indentation cleaned up):

```
FILE_SAVE_PRE file.path is:  nil
FILE_SAVE_PRE path is:       filename
FILE_SAVE_POST file.path is: /tmp/filename
FILE_SAVE_POST path is:
```

If I run `:w` again afterwards, the output is as expected:

```
FILE_SAVE_PRE file.path is:  /tmp/filename
FILE_SAVE_PRE path is:       /tmp/filename
FILE_SAVE_POST file.path is: /tmp/filename
FILE_SAVE_POST path is:      /tmp/filename
```

---

```
$ vis -v
vis v0.5-62-ge136e34 +curses +lua +tre +acl
```

**Comment by martanne** [comment]
Hi, these are not supposed to be the same thing. `file.path` is the full path of the file being saved. In particular, if it is yet to be named, it will be `nil`. Also if you open a file named foo, but then do `:w bar` the `file.path` should point to foo while `path` is referring to bar. As of 978f3d70b9047608789e40a0b67e91d4fd19e60a the latter should now also always be absolute and non-empty (the bug demonstrated by your snippet).
