### ISSUE TITLE
motion not working when changing case using gu

### ISSUE THREAD

**Issue by erf** [martanne/vis#776]
motion not working when changing case using gu

for example: `guu` does not change line to lowercase

see more examples here:
https://stackoverflow.com/questions/2946051/changing-case-in-vim

**Comment by ninewise** [comment]
As seen in `:help`, `gu` in vis is just an alias to `:|tr '[:upper:]' '[:lower:]'<Enter>`. It's not an operator, so it makes sense it does not wait to listen for a motion. It seems the manpage does list it amongst the operators, so either it should be removed there or it could be made an operator.

**Comment by erf** [comment]
@TmpFinger1 thanks! your plugin seem to work fine :)

**Comment by lobre** [comment]
Does anyone have context on why it was changed from operators to `tr` aliases? Seeing the previous implementation (that was removed), it seemed clean and not that verbose. So I am wondering why it was switched to something that feels inferior now (at least from my point of view). It makes vis get away from vim for no apparent reason.

**Comment by rnpnr** [comment]
> Does anyone have context on why it was changed from operators to `tr` aliases?

Huh, this is the first time I've seen the commits linked above. The only reason I can see for doing that was in hopes of supporting unicode (which is still broken and we keep adding workarounds to). I agree that current solution is worse and would prefer a builtin native version.

Currently vis has a number of other issues with unicode as well. It might be worth considering vendoring in something like [libgrapheme](https://libs.suckless.org/libgrapheme/) to help with this. I'll bring it up on the mailing list later when I have time.

**Comment by lobre** [comment]
Effectively, unicode could be the reason. Good catch. I am wondering how vim/neovim projects deal with unicode, and if they use external dependencies for this.
