### ISSUE TITLE
Mapping multiple actions in visrc.lua

### ISSUE THREAD

**Issue by csmcrvrs** [martanne/vis#777]
I am attempting to develop custom key mappings for the vis editor.

I have reviewed issue #597 which was closed.  I have written a snippet that illustrates my issue.

I have reviewed:  https://martanne.github.io/vis/doc/#Vis:map

In the sample code below, the firstAction is mapped to the m1 key combination.  It works as expected.   The secondAction is mapped to the m2 key combination and does not work.  The only difference I can see is that the first one works and the second one doesn't even though they are semantically equivalent.

What needs to change for the second one to work the way the first one does?
*********************************************************************
#!/usr/bin/lua                                                                  
                                                                                
-- load standard vis module, providing parts of the Lua API                     
require('vis')                                                              
                                   
local firstAction = vis:action_register("info", function()                      
  vis:info("Mapping works here")                                                
end, "Info message help text")                                                  
                                                                                
local secondAction = vis:action_register("info", function()                     
  vis:info("Mapping not working here.")                                         
end, "Info message help text")                                                  
                                                                                
vis.events.subscribe(vis.events.INIT, function()                                
                                                                                
   -- Your global configuration options                                         
   vis:command('set theme base16-ir-black')                                     
                                                                                
end)                                                                            
                                                                                
vis.events.subscribe(vis.events.WIN_OPEN, function(win)                         
   -- Your per window configuration options e.g.                                
   vis:command('set number')                                                    
   vis:command('set tab 3')                                                     
   vis:command('set expandtab')                                                 
   vis:command('set cursorline')                                                
   vis:command('set colorcolumn 80')                                            
   vis:map(vis.modes.NORMAL, "m1", firstAction )                                
   vis:map(vis.modes.NORMAL, "m2", secondAction )                               
end)

**Comment by ninewise** [comment]
You're registering 2 actions with the same name, "info". These names should be unique, so secondAction is `nil`.

If you just want to bind these functions to a key, I'd advise using:

```lua
vis:map(vis.modes.NORMAL, "m1", function()
    ...
end)
```

**Comment by csmcrvrs** [comment]
Thank-you some much ninewise.  I was afraid I might be doing some silly little thing.
