### ISSUE TITLE
Soft tab indentation replacement symbol

### ISSUE THREAD

**Issue by theamazingwaffle** [martanne/vis#779]
For me tabwidth = 4, so 
Every 4th space draw the tab replacement symbol.

Make it depend on tabwidth too if possible, if no maybe make a separate option?

**Comment by ninewise** [comment]
Could you post a screenshot of the desired result (a picture with the setting and a picture without the setting)? I'm not sure what you want.

**Comment by theamazingwaffle** [comment]
![I'm sorry, i'm bad at explaining things](https://user-images.githubusercontent.com/54444526/70560776-dec6cd80-1b91-11ea-8a8a-155fb1ad5a3c.png)

For real though, i'm very sorry for my bad explanations \>_\<

**Comment by ninewise** [comment]
No problem, it's clear what you're talking about now. I'm afraid this isn't (afaik) supported by vis, yet. I'm not familiar with the vis source code, so I can't help you there.

One horrible workaround would be to use `:set show-spaces on` and use a font ligature to merge four `·` into a single symbol. But it's probably better not to do this.

Alternatively, why not just use tabs? ;-) If you prefer to keep the content as spaces when on disk, you could replace all (indenting) spaces with tabs when opening a file, and replace them with spaces again when closing/saving a file.

**Comment by theamazingwaffle** [comment]
Thanks for the reply. I don't need to store them as  spaces so i'll just use tabs then.
