### ISSUE TITLE
'Invalid argument' when saving file in a VirtualBox shared folder

### ISSUE THREAD

**Issue by 3dc1d3** [martanne/vis#792]
Within a VirtualBox guest running Linux on a Windows host, if I try to save changes to a file in a shared folder I get `Can't write /mnt/host/moo.csv: Invalid argument` - but the file **does** get saved to disk, yet the buffer remains in a 'dirty' state (as though it hasn't been saved).

Attempting to save again results in `WARNING: file has been changed since reading it`.

My permissions are fine and I can pipe data into files in the shared folder, and also save changes using `vim` so it is specific to the way `vis` does the write - or more accurately the way it verifies the write? (since the data does get written...)

Suggesting an alternate filename with `:w tmp.csv` gives the same error.

If I find time I'll try to debug this but if anyone has any immediately clues or potential fixes I'd be grateful.

**Comment by martanne** [comment]
You can try whether it behaves differently with `:set savemethod inplace`, but a strace output would probably be useful ...

**Comment by 3dc1d3** [comment]
great that worked, cheers.

I attached the strace just before `:w` and then a gap before the second attempt.

[vis.vbox.trace.log](https://github.com/martanne/vis/files/4106106/vis.vbox.trace.log)
