### ISSUE TITLE
g[uU~] with movement no longer works

### ISSUE THREAD

**Issue by michaelforney** [martanne/vis#793]
I noticed that in the latest git version of vis, `gUe` no longer works to capitalize to the end of the word. I believe this is due to the change to implement these commands with `:|tr ...`.

Is there any way to preserve the previous behavior with the new implementation? If not, I suppose I can retrain my muscle memory to use `v<movement>g[uU~]`, but just wanted to check that it's not an unexpected regression.

**Comment by ninewise** [comment]
Duplicate of #776; there's a plugin linked there to restore previous behaviour.

**Comment by michaelforney** [comment]
Thanks for the link.
