### ISSUE TITLE
vis crashes with too many windows

### ISSUE THREAD

**Issue by TieDyedDevil** [martanne/vis#80]
Attempting to create more windows than will fit on the screen causes vis to segfault. This can be trigged either via repeated application of :new or by attempting to open many files from the command line.

This really isn't that serious since there's no good way to use vis with a lot of windows: vis lacks commands to manipulate window size and visibility. One quickly learns to only open as many files as the screen size will comfortably accommodate.

**Comment by martanne** [comment]
The editor is still essentially unusable, but does no longer crash. Also the editor command line works, hence one can save + close all windows.
