### ISSUE TITLE
show vis:info before shell command

### ISSUE THREAD

**Issue by erf** [martanne/vis#805]
I'd like to display some info to the user before running a shell command, but when i call `vis:info` or `vis:message`, it does not show up until after the command finishes. Is there a way to fix this?

Example:
```
vis:info('updating..') -- show info before git call
os.execute("git ..")
```

**Comment by martanne** [comment]
As of 30c6ceb2447be5b8b73958271972ba98457dc0b7 you might be able to use `vis:redraw()`. However, make sure to avoid infinite recursion.

**Comment by erf** [comment]
Works great - thanks!
