### ISSUE TITLE
Do not strip binaries! Avoid public nudity!

### ISSUE THREAD

**Issue by mcepl** [martanne/vis#811]
Most Linux distributions I know about (Debian, Fedora, openSUSE) prefer that the upstream build system DOES NOT strip binaries, because their packaging scripts do it themselves and preserve debugging symbols in separate packages.

There doesn't seem to be a good way how persuade the vis build system not to strip binaries aside from [this rather crude patch](https://github.com/martanne/vis/files/4245202/puritanism.patch.txt). Couldn't we get something better?

**Comment by TmpFinger2** [comment]
A separate `install-strip` target is pretty standard: https://www.gnu.org/software/automake/manual/html_node/Standard-Targets.html

**Comment by mcepl** [comment]
Thank you.
