### ISSUE TITLE
Questions and request regarding lua runtime files / paths

### ISSUE THREAD

**Issue by erf** [martanne/vis#813]
Typing `vis man` i find the following:
```
FILES
     Upon startup vis will source the first visrc.lua configuration file found from these
     locations.  All actively used paths can be listed at runtime using the :help command.

     o   $VIS_PATH

     o   The location of the vis binary (on systems where /proc/self/exe is available).

     o   $XDG_CONFIG_HOME/vis where XDG_CONFIG_HOME refers to $HOME/.config if unset.

     o   /etc/vis for a system-wide configuration provided by administrator.

     o   /usr/local/share/vis or /usr/share/vis depending on the build configuration.

         When creating a new visrc.lua be sure to copy the structure from here.
```

If i type `:help` as suggested i get listed a set of paths like this:
```
 Lua paths used to load runtime files (? will be replaced by filename):

  /Users/myname/.config/vis/?.lua
  /Users/myname/.config/vis/?/init.lua
  /etc/vis/?.lua
  /etc/vis/?/init.lua
  /usr/local/share/vis/?.lua
  /usr/local/share/vis/?/init.lua
  /usr/local/share/lua/5.3/?.lua
  /usr/local/share/lua/5.3/?/init.lua
  /usr/local/lib/lua/5.3/?.lua
  /usr/local/lib/lua/5.3/?/init.lua
```

Are all `visrc.lua` files found in these paths loaded? 

For example i have the following folder from install:
`/usr/local/share/vis/visrc.lua`

but i also add:
`.config/vis/visrc.lua`

So are both these config files loaded, and if so is that not unnecessary and perhaps a performance hit?

Also is `visrc.lua` the only `.lua` file loaded from these paths ( except other lua files included via `require('vis')` in `visrc.lua` ) ?

I does not seem that custom "plugin" `.lua` files are included if inside these folders, and must be included explicitly via `visrc.lua`.

Would it make sense to make the "working" lua runtime path available inside `visrc.lua` so other lua plugins could access it ( for writing to disk etc. )?

**Comment by erf** [comment]
I could call the following "pipe pwd" to get the current directory, but the file is only available in `WIN_OPEN` event, and i'd like to call require on other plugins before that, so i'd like to allready have that path available before any events, if possible.
```
vis.events.subscribe(vis.events.WIN_OPEN, function(win) 
	local status, out, err = vis:pipe(win.file, { start = 0, finish = 0 }, "pwd")
```

**Comment by ninewise** [comment]
> Are all `visrc.lua` files found in these paths loaded?

According to the part of the man page you quoted, "vis will source the first visrc.lua configuration file found from these location".

> So are both these config files loaded, and if so is that not unnecessary and perhaps a performance hit?

So that's a no. Only the `.config/vis/visrc.lua` will be loaded.

> Also is `visrc.lua` the only `.lua` file loaded from these paths ( except other lua files included via `require('vis')` in `visrc.lua` ) ?

Yes. Only the files required by the sourced visrc will be loaded.

> Would it make sense to make the "working" lua runtime path available inside visrc.lua so other lua plugins could access it ( for writing to disk etc. )?

I don't think so. Plugins should be agnostic to which visrc was used. If you want to store configuration/data/cache, plugins should probably adhere to the XDG standard. They probably don't have rights to write to most of the path, anyway.

**Comment by erf** [comment]
@ninewise thanks for your answer. Regarding the Lua runtime path, the reason i would like the same path as where the sourced

**Comment by erf** [comment]
@ninewise thanks for your answer. the reason i'd like to get the path to the sourced `visrc.lua` is because, i require a "plugin manager" as a "plugin" there, and i would like to have it download and update other plugins to the same folder.
