### ISSUE TITLE
Feature request: Make the current Lua runtime path available in Lua API

### ISSUE THREAD

**Issue by erf** [martanne/vis#815]
I'd like to have the current Lua runtime path, used to source the visrc.lua, available via the Lua API.

I require a Lua plugin, which would like to do some disk operations on the current path.

**Comment by martanne** [comment]
You can use the standard [Lua `package.path`](https://www.lua.org/manual/5.3/manual.html#pdf-package.path), it is also used to produce the `:help Lua` listing.

As was explained in #813, the *first* path which contains the requested file is used.

**Comment by erf** [comment]
Thanks!

Ok, this might be weird, but would it be possible to make a bash or lua script, which would somehow get the default `visrc.lua` path; perhaps by running a command / pipe via vis ?
