### ISSUE TITLE
syntax highlighting of changes broken

### ISSUE THREAD

**Issue by mcepl** [martanne/vis#816]
It looks like an apostrof (chr(39), nothing about UTF-8) throws off syntax highlighting:

![Snímek z 2020-03-03 13-53-39](https://user-images.githubusercontent.com/198999/75777554-77ff1d80-5d56-11ea-9ae9-28eda42463fe.png)

**Comment by martanne** [comment]
As was already pointed out on IRC, the used lexer is intended for [Squeak, a Smalltalk dialect](http://wiki.squeak.org/squeak/1105). You would have to write your own highlighting rules for these changelog entries.
