### ISSUE TITLE
How to auto insert spaces instead tabs.

### ISSUE THREAD

**Issue by wachd** [martanne/vis#821]
I don't know where to ask, Is there any forum, subreddit or TG or other places that I can easily ask something?

**Comment by RibalGZ** [comment]
You can expand to spaces with `:set expandtab on`.
Check the `:help` page to see the available commands.

**Comment by wachd** [comment]
and how to get command history in lua API?

**Comment by ninewise** [comment]
You cannot, AFAIK. The API docs are [here](https://martanne.github.io/vis/doc/index.html). For easily asking something, there's the IRC channel #vis-editor on the freenode servers.

**Comment by wachd** [comment]
thank you!

**Comment by erf** [comment]
https://github.com/martanne/vis/issues/538
