### ISSUE TITLE
Can't cancel a motion immediately after count sequence in normal mode

### ISSUE THREAD

**Issue by budbin** [martanne/vis#825]
After making some accidental key presses on the number row, I found that it's not possible to cancel a motion at the point when vis expects an operator to follow. The only way out at this point is to follow through with any operator, then undo it. This can be quite cumbersome when working fast.

To replicate:

1. Type any number sequence in normal mode.
2. Try to cancel the motion using Esc or Ctrl+].

Expected behavior: the motion is cancelled.

What happens instead: vis keeps expecting an operator (the count is still visible in the status line).

**Comment by ninewise** [comment]
You can create the requested behaviour by adding the following to your visrc:

```lua
vis:map(vis.modes.NORMAL, "<Escape>", function()
	if vis.count then
		vis.count = nil
	else
		vis:feedkeys"<vis-selections-remove-all>"
	end
end)
```

I think there's already an issue about this somewhere.
