### ISSUE TITLE
complete-filename backtrace

### ISSUE THREAD

**Issue by mcepl** [martanne/vis#827]
When running ``<Ctrl-x><Ctrl-f>`` I get this backtrace:
```
/usr/share/vis/plugins/complete-filename.lua:9: attempt to call a nil value (method 'text_object_longword')
```

**Comment by martanne** [comment]
Do you have any additional information? How did you create the window from which you are trying to run the completion? I can't reproduce it.

Also the mentioned function is currently provided by the [vis core Lua bindings](https://github.com/martanne/vis/blob/08a550deac6f55f32f131f66992994b3944011ce/vis-lua.c#L2738). It seems like you are dealing with a strange [`file` object](https://github.com/martanne/vis/blob/08a550deac6f55f32f131f66992994b3944011ce/lua/plugins/complete-filename.lua#L5). I would try to add some debug statements to see what is going on ...

**Comment by mcepl** [comment]
That’s the weird thing. When I add this to ``/usr/share/vis/plugin/complete-filename.lua``:
```diff
--- complete-filename.lua.orig	2020-04-27 15:47:13.004212805 +0200
+++ complete-filename.lua	2020-04-27 15:48:52.413564058 +0200
@@ -6,6 +6,7 @@
 	local pos = win.selection.pos
 	if not pos then return end
 	-- TODO do something clever here
+        vis:info('pos = ' .. pos .. ', condition = ' .. (pos > 0 and pos-1 or pos))
 	local range = file:text_object_longword(pos > 0 and pos-1 or pos);
 	if not range then return end
 	if range.finish > pos then range.finish = pos end
```
I get this echo:
```
pos = 3539, condition = 3538
```
so it looks like everything is working just fine.

**Comment by martanne** [comment]
The problem is unrelated to the actual position being used. The error tells you that `text_object_longword` field of the `file` object is `nil` (and can thus not be called).

Therefore I suggested to investigate the `file` object. The following might be a starting point:

```
type(file)
```
should be: userdata
```
getmetatable(file).__name
```
should be: file
```
type(getmetatable(file).text_object_longword)
```
should be: function

Are you sure you are not running some other plugin/code which messes with the file object?

I would check the lifetime of the file object, e.g. check the above values in a `FILE_OPEN` event etc.

**Comment by mcepl** [comment]
OK, the first two are correct: ``type(file)`` is ``userdata`` and ``getmetatable(file).__name`` is ``file``.

The last one when adding
```lua
vis:info('type = ' .. type(getmetatable(file).text_object_longword))
```
gives me ``nil``.

**Comment by mcepl** [comment]
I get the same error when I move ``~/.config/vis`` elsewhere, so I don’t think it can be caused by any third-party plugins. The only patches I have on the top of the regular git checkout are the ones from #558 and #822.

**Comment by mcepl** [comment]
OK, after upgrade to 7648280, the problem seems to go away. You can ignore this.

**Comment by mcepl** [comment]
Unfortunately, the problem reappeared again, when I added patch from #558.
