### ISSUE TITLE
Build fails with tcc

### ISSUE THREAD

**Issue by theamazingwaffle** [martanne/vis#828]
```bash
make
```
```
In file included from array.c:1:
In file included from /usr/include/stdlib.h:25:
In file included from /usr/include/bits/libc-header-start.h:33:
/usr/include/features.h:397: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O)
In file included from buffer.c:1:
In file included from /usr/include/stdlib.h:25:
In file included from /usr/include/bits/libc-header-start.h:33:
/usr/include/features.h:397: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O)
In file included from libutf.c:2:
In file included from libutf.h:6:
In file included from /usr/include/stdint.h:26:
In file included from /usr/include/bits/libc-header-start.h:33:
/usr/include/features.h:397: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O)
In file included from main.c:1:
In file included from /usr/include/signal.h:25:
/usr/include/features.h:397: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O)
In file included from main.c:13:
In file included from ui-terminal.h:4:
In file included from ui.h:81:
vis.h:944: error: identifier expected
make: *** [Makefile:62: vis] Error 1
```

**Comment by martanne** [comment]
TCC doesn't seem to support the [`static` keyword for arrays within function parameter declarations](https://port70.net/~nsz/c/c11/n1570.html#6.7.6.3p7).

However, the feature merely provides additional information ([here is an informal description](https://hamberg.no/erlend/posts/2013-02-18-static-array-indices.html)) and isn't strictly needed. Simply removing the `static` keyword from the offending lines should make it compile.

If you are interested in lightweight compilers, you might also want to try [cproc](https://git.sr.ht/~mcf/cproc)+[qbe](https://c9x.me/compile/) or [cparser](https://github.com/libfirm/cparser)+[libfirm](https://pp.ipd.kit.edu/firm/). You might need to patch vis in a few places, but it should be manageable.

**Comment by michaelforney** [comment]
Since you mentioned cproc, I just wanted to add that there are some vis patches that can be used to get it to build:
https://github.com/oasislinux/oasis/tree/master/pkg/vis/patch

These are necessary until I implement VLAs and wide string literals in cproc.

**Comment by martanne** [comment]
Do you intend to eventually implement VLAs? Since they are optional in C11, maybe I should just merge your patch ...

**Comment by michaelforney** [comment]
I do, but doing it properly requires some support in QBE (see https://todo.sr.ht/~mcf/cproc/1). I could implement basic support for VLAs that don't appear in loops or after labels, but have not gotten around to it yet.

That said, I think VLAs should be avoided in most cases, and if my patch looks unobtrusive enough to you, I'd support merging it.

(of course, not the wide string literal one, that's just a hack)
