### ISSUE TITLE
line numbers are broken on latest master

### ISSUE THREAD

**Issue by lanodan** [martanne/vis#830]
- OS: Gentoo Linux
- [build.log](https://github.com/martanne/vis/files/4549245/build.log)
- [vissrc.lua](https://github.com/martanne/vis/files/4549253/vissrc.lua.txt)
- Terminal: tmux into st

Screenshot (a106a42bf1ddf2d88ccf4e470bb134e6a9fa8334 vs. version 0.5)

![screen](https://user-images.githubusercontent.com/3816428/80551190-ee20a900-89c2-11ea-8e84-fcbe04313b4a.png)

**Comment by 0x5EA8E1B7** [comment]
I backtracked the commit that broke everything to df147e9

**Comment by michaelforney** [comment]
Sorry about that. Thanks for fixing my bug.
