### ISSUE TITLE
Which device file does the auto-completion write into? 

### ISSUE THREAD

**Issue by varmanishant** [martanne/vis#832]
I just connected `hterm` (hterm.org) by creating a `pty` pair and sending data to the master `pty` via websocket. Slave is connected to my shell.

`vis` works fine, but the only problem is that the auto-completion <kbd>:Tab</kbd> writes into the terminal which started the websocket and not to the master pty as I would expect! Is there any reason for this? `xterm.js` in Visual Studio Code works fine though.

Here is how I create the `pty` pair in Python (websocket connection writes into the master):

```python
SH = ["rc"]                                                                         
OPTS = ["-l"]                                                                          

# Generating a master, slave pair.                                                                                        

M, S = openpty()                                                                                

MRD = open(M, "rb", buffering=0)                                          
MWR = open(M, "wb", buffering=0)                                                                                            

SRD = open(S, "rb", buffering=0)                               
SWR = open(S, "wb", buffering=0)

def fork():
    proc = run(SH + OPTS, stdin=SRD, stdout=SWR, stderr=SWR)

t = Thread(target=fork)
t.daemon=True
t.start()
```

**Comment by martanne** [comment]
Hi, the completion currently uses the `vis-menu(1)` utility which [re-opens `/dev/tty`](https://github.com/martanne/vis/blob/1ad19aeb7ee6b6b8446d6262543cd31d9215df4f/vis-menu.c#L323) and uses it to receive interactive input and draw its user interface.
