### ISSUE TITLE
Textmate Grammar support? 

### ISSUE THREAD

**Issue by tmccombs** [martanne/vis#835]
While quite a few languages have syntax highlighting support in vis, the set of available syntax highlighting plugins is much smaller than more popular editors, and some of the provided syntax files are out of date (for example rust). It would be nice if vis could take advantage of syntax files created for other (currently) more prevalent editors. Textmate grammars are used not only by TextMate, but also VSCode, Atom, and Sublime Text. If vis supported Textmate grammars, it would get syntax highlighting for languages used by these editors for free. 

It might be possible to implement this as a lua plugin on top of the existing syntax highlighting system, and I might take a stab at doing that. From a quick look, my biggest question is how to map textmate hierarchal style names to the flat style names in vis. It would also need a json, and possibly an xml parser available in lua, and probably won't perform as well as a native c implementation.

p.s. It looks like vis's syntax system is based on scintillua, which is deprecated (https://foicica.com/scintillua/)

**Comment by mcepl** [comment]
The same argument can go vim syntax files (or the Emacs ones).

**Comment by yory8** [comment]
Neovim is switching to tree-sitter, which provides high-quality high-performance highlighting.

**Comment by mcepl** [comment]
> Neovim is switching to tree-sitter, which provides high-quality high-performance highlighting.

Is tree-siter bound to some particular syntax of syntax files? Neovim doesn’t seem to be switching anything there.

**Comment by yory8** [comment]
It uses its own syntax. The main downside of tree-sitter seems to be that the compiled grammars are quite big, see this thread of the wip implementation for [micro](https://github.com/zyedidia/micro/pull/1466). 
I agree that the current way is already satisfactory.

**Comment by mcepl** [comment]
> It uses its own syntax. The main downside of tree-sitter seems to be that the compiled grammars are quite big, see this thread of the wip implementation for [micro](https://github.com/zyedidia/micro/pull/1466).
> I agree that the current way is already satisfactory. Just wanted to say that textmate is a mess, so if a switch were done tree-sitter would be a much better idea.

Agree, tree-sitter or something vim-like (emacs-like probably will be too heavily linked to Lisp).

**Comment by tmccombs** [comment]
> I agree that the current way is already satisfactory

I agree that the way vis handles syntax highlighting is good. My request is more that it would be nice to take advantage of existing syntax files from another project instead of having to re-implement them. Even a tool that could automatically generate lua syntax files for vis from textmate/vim/emacs/tree-sitter would work.

**Comment by mcepl** [comment]
> My request is more that it would be nice to take advantage of existing syntax files from another project instead of having to re-implement them.

Which is exactly what we are doing. Since https://github.com/martanne/vis/pull/1018 we are using fully https://github.com/orbitalquark/scintillua syntax files.

IMHO, this ticket could be closed.

**Comment by rnpnr** [comment]
Yep [orbitalquark/scintillua](https://github.com/orbitalquark/scintillua) is definitely not "deprecated" and I think
its much preferred to needing a json or xml parser. And I agree and
also prefer that vis isn't made dependent on some other library.
