### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by erf** [martanne/vis#836]
Congrats on the 0.6 release!

Not sure if you have considered adding a [CHANGELOG.md](https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md) file to show major changes per release as a text file in the repo?

**Comment by mcepl** [comment]
@ninewise, this should probably be closed, we don’t maintain a ChangeLog, do we?

**Comment by ninewise** [comment]
It would be a good thing to do, though

**Comment by mcepl** [comment]
Fortunately, it is stored platform independently in git tags https://git.sr.ht/~mcepl/vis/refs .

**Comment by ninewise** [comment]
Applied on sourcehut.
