### ISSUE TITLE
Build error on OSX

### ISSUE THREAD

**Issue by erf** [martanne/vis#84]
I get the following error when i run <b>make</b> on OSX:
<pre>
cc -D_DARWIN_C_SOURCE -std=c99 -Os -I. -DVERSION="0.r580.geb906b3" -DNDEBUG -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 buffer.c editor.c libutf.c map.c register.c ring-buffer.c text-motions.c text-objects.c text-regex.c text-util.c text.c ui-curses.c view.c vis.c -lc -lncurses -o vis
Undefined symbols for architecture x86_64:
  "_termkey_advisereadable", referenced from:
      _mainloop in vis-c91dcd.o
  "_termkey_destroy", referenced from:
      _ui_curses_free in ui-curses-7b3498.o
  "_termkey_get_waittime", referenced from:
      _ui_getkey in ui-curses-7b3498.o
  "_termkey_getkey", referenced from:
      _ui_getkey in ui-curses-7b3498.o
  "_termkey_getkey_force", referenced from:
      _ui_getkey in ui-curses-7b3498.o
  "_termkey_new", referenced from:
      _ui_curses_new in ui-curses-7b3498.o
  "_termkey_start", referenced from:
      _ui_terminal_restore in ui-curses-7b3498.o
  "_termkey_stop", referenced from:
      _ui_terminal_save in ui-curses-7b3498.o
  "_termkey_strfkey", referenced from:
      _ui_getkey in ui-curses-7b3498.o
  "_termkey_strpkey", referenced from:
      _keynext in vis-c91dcd.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [vis] Error 1

</pre>

**Comment by twe4ked** [comment]
Same errors here using `libtermkey` version `0.17` (homebrew).

**Comment by martanne** [comment]
Could you try whether it works now with: `rm config.h && make`?

If not you will have to come up with a proper fix. I have no clue how Mac OS X / homebrew operate. Is `pkg-config` available? The problem is obviously that your missing the `-ltermkey` linker directive, which was due to the wrong `LIBS` assignment in the if `ifeq (${OS},Darwin)` section.

**Comment by erf** [comment]
Got it working.
I built ncurses from source using : ./configure --enable-widec
Then i had to change the config.mk with the correct folder, from '/usr/include/ncursesw' to '/usr/include/ncurses'.

**Comment by twe4ked** [comment]
I tried `rm config.h && make` and got:

```
cp config.def.h config.h
cc -I/usr/local/include -D_DARWIN_C_SOURCE -I/usr/local/Cellar/libtermkey/0.17/include -I/usr/include/ncursesw -std=c99 -Os -DVERSION="0.r624.g1190302" -DNDEBUG -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 buffer.c libutf.c main.c map.c register.c ring-buffer.c text-motions.c text-objects.c text-regex.c text-util.c text.c ui-curses.c view.c vis.c -L/usr/local/lib -L/usr/local/Cellar/libtermkey/0.17/lib -ltermkey -lncursesw -lc -o vis
ld: library not found for -lncursesw
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [vis] Error 1
```

We do have `pkg-config`, `pkg-config --cflags ncursesw` returns “No package 'ncursesw' found”.

II could build ncurses from source but an older version of vis worked with the system package.

Not sure if this helps:

```
$ grep VERSION /usr/include/curses.h
#define NCURSES_VERSION_MAJOR 5
#define NCURSES_VERSION_MINOR 7
#define NCURSES_VERSION_PATCH 20081102
#undef  NCURSES_VERSION
#define NCURSES_VERSION "5.7"
#define NCURSES_MOUSE_VERSION 1
#  define NCURSES_EVENT_VERSION 1
#define curses_version() NCURSES_VERSION
#if NCURSES_MOUSE_VERSION > 1
#if NCURSES_MOUSE_VERSION > 1
```

**Comment by martanne** [comment]
> pkg-config --cflags ncursesw returns “No package 'ncursesw' found”

What does `pkg-config --cflags --libs ncurses` print?

**Comment by erf** [comment]
@twe4ked did you try change the folder 'ncursesw' to 'ncurses' in the config.mk ?

**Comment by twe4ked** [comment]
@martanne It returns the same thing.

@erf I tried changing that now and it works, thanks.

``` diff
diff --git a/config.mk b/config.mk
index 73027bf..b0cc92f 100644
--- a/config.mk
+++ b/config.mk
@@ -26,10 +26,10 @@ PREFIX ?= /usr/local
 MANPREFIX = ${PREFIX}/share/man
 
 CFLAGS_TERMKEY = $(shell pkg-config --cflags termkey 2> /dev/null || echo "")
-CFLAGS_CURSES = $(shell pkg-config --cflags ncursesw 2> /dev/null || echo "-I/usr/include/ncursesw")
+CFLAGS_CURSES = $(shell pkg-config --cflags ncurse 2> /dev/null || echo "-I/usr/include/ncurses")
 
 LDFLAGS_TERMKEY = $(shell pkg-config --libs termkey 2> /dev/null || echo "-ltermkey")
-LDFLAGS_CURSES = $(shell pkg-config --libs ncursesw 2> /dev/null || echo "-lncursesw")
+LDFLAGS_CURSES = $(shell pkg-config --libs ncurses 2> /dev/null || echo "-lncurses")
 
 LIBS = -lc
 OS = $(shell uname)
```

It looks like it's falling over the the `|| echo "-lncurses` (as I guess you guys already know). I haven't built a version of `ncurses` with `--enable-widec` (just worked out that's what `ncursesw` is…). I guess the fix would be to build `ncurses` with `--enable-widec` to `/usr/include/ncursesw`.

**Comment by martanne** [comment]
I asked about the pkg-config output for `ncurses` (without the trailing w) because it might make sense to fall back to it if pkg-config fails for `ncursesw` as in:

``` diff
diff --git a/config.mk b/config.mk
index 73027bf..77385f9 100644
--- a/config.mk
+++ b/config.mk
@@ -26,10 +26,10 @@ PREFIX ?= /usr/local
 MANPREFIX = ${PREFIX}/share/man
 
 CFLAGS_TERMKEY = $(shell pkg-config --cflags termkey 2> /dev/null || echo "")
-CFLAGS_CURSES = $(shell pkg-config --cflags ncursesw 2> /dev/null || echo "-I/usr/include/ncursesw")
+CFLAGS_CURSES = $(shell pkg-config --cflags ncursesw 2> /dev/null || shell pkg-config --cflags ncurses 2> /dev/null || echo "-I/usr/include/ncursesw")
 
 LDFLAGS_TERMKEY = $(shell pkg-config --libs termkey 2> /dev/null || echo "-ltermkey")
-LDFLAGS_CURSES = $(shell pkg-config --libs ncursesw 2> /dev/null || echo "-lncursesw")
+LDFLAGS_CURSES = $(shell pkg-config --libs ncursesw 2> /dev/null || shell pkg-config --libs ncurses 2> /dev/null || echo "-lncursesw")
 
 LIBS = -lc
 OS = $(shell uname)
```

 However Mac OS X (or at least your system) seems to have these libraries installed, but without the corresponding `*.pc` pkg-config configuration files. Therefore it won't help you.

The simple solution is to specify the correct flags directly on the command line when building:
`make CFLAGS_CURSES="-I/usr/include/ncurses" LDFLAGS_CURSES="-lncurses"`

**Comment by twe4ked** [comment]
Thanks for the explanation. :)
