### ISSUE TITLE
How to get values from registers when registering new operator?

### ISSUE THREAD

**Issue by Yodzorah** [martanne/vis#859]
I want to be able to:

- `"aR` - for replacing selected text in VISUAL mode with whetever there is in `a` register
- `R2w"a` - for replacing 2 words in NORMAL mode with whatever there is in the `a` register

```lua
vis:operator_new("R", function(file, range, pos)
	vis:delete(range)
	vis:insert(range.start, ???) # how to get the register which is being addressed?

	return range.start -- new cursor location
end, "Replace operator, deletes something into `_` register, pastes something in return")
```

**Comment by martanne** [comment]
With the introduction of `vis.register` in c02ff996418dd8e5c4115333c5a442e14e9add61 it should be possible now.
