### ISSUE TITLE
Lexer: String Interpolation

### ISSUE THREAD

**Issue by jeremybobbin** [martanne/vis#862]
Is there any way to syntax highlight inner expressions like `${0##*/}` & `$opt` in this string?
```bash
echo "${0##*/}: invalid option '$opt'"
```

Or maybe the `%s`'s in:
```c
printf("%s: invalid option '%s'", argv[0], opt);
```

What would be the best way to do this sort of thing?

**Comment by martanne** [comment]
There are two possible approaches to this:

1. Define a "sub" lexer for strings and try to integrate it using `embed_lexer`. I'm not sure whether that will actually work when the start and end rule are the same, though.

2. Introduce some concept of "stacked lexing" where the initial (existing) lexer produces a token stream `(type, range)` which could be further tweaked in subsequent passes. In your case you could filter out all tokens of type string and analyze them further. It might also be useful for language independent things like highlighting trailing white spaces etc.

However, if you are looking for advanced/correct syntax highlighting it might make more sense to investigate integration with existing language aware solutions.

**Comment by ninewise** [comment]
Yes, closing this here. Please open a ticket at scintillua if this is still relevant.
