### ISSUE TITLE
How do I get vis to recognize racket files?

### ISSUE THREAD

**Issue by ccao001** [martanne/vis#868]
How can I get vis to recognize [racket](https://docs.racket-lang.org/) files (i.e. .rkt files) and turn on scheme syntax?

Any help is greatly appreciated.

\- Carla

**Comment by ninewise** [comment]
Did you find the [README about lexers](https://github.com/martanne/vis/tree/master/lua/lexers)? It is slightly hidden.

**Comment by TmpFinger3** [comment]
In `lua/plugins/filetype.lua`, there is this section:

```lua
	scheme = {
		ext = { "%.sch$", "%.scm$", "%.sld$", "%.sls$", "%.ss$" },
	},
```

If you add `"%.rkt$"`, the existing `scheme` lexer will be used for highlighting.

You might find the [vis-parkour plugin](https://lisp-parkour.neocities.org) useful, too.
There are Racket-specific rules for automatic square bracket rewriting, among other things.
