### ISSUE TITLE
Request: Agda Lexer (agda.lua)

### ISSUE THREAD

**Issue by ccao001** [martanne/vis#869]
# [Agda](https://wiki.portal.chalmers.se/agda/pmwiki.php)

Agda has similar syntax to Haskell but with some slight differences.

See [this video](https://www.youtube.com/watch?v=shXKb2MTkUc&list=PLB7F836675DCE009C&index=2&t=0s) comparison between haskell and agda syntax at the beginning.

I'm not sure if I can work on it at the moment fully but would like to mention in it in case anybody would like to start.

**Comment by martanne** [comment]
We are currently using [Scintillua](https://github.com/orbitalquark/scintillua) for syntax highlighting. Please direct your feature request at upstream. Thanks.
