### ISSUE TITLE
Backspace inserts `<DEL>`

### ISSUE THREAD

**Issue by erf** [martanne/vis#87]
Backspace inserts `<DEL>`, and does not delete characters.

**Comment by erf** [comment]
This problem seems to persist after fa41d89

**Comment by martanne** [comment]
Did you remove your local `config.h`?

**Comment by erf** [comment]
no =) it works!

**Comment by erf** [comment]
Same things happen for delete if i press fn+backspace

**Comment by martanne** [comment]
Is everything fixed now?

**Comment by erf** [comment]
Yes! Thank you
