### ISSUE TITLE
Request: ABC Music Lexer (abc.lua)

### ISSUE THREAD

**Issue by ccao001** [martanne/vis#871]
[Abc notation](https://abcnotation.com/) is a markup language for music. In this sense it is similar to lilypond but it's syntax is different.

Here is an example:

```
X:1
T:Speed the Plough
M:4/4
C:Trad.
K:G
|:GABc dedB|dedB dedB|c2ec B2dB|c2A2 A2BA|
  GABc dedB|dedB dedB|c2ec B2dB|A2F2 G4:|
|:g2gf gdBd|g2f2 e2d2|c2ec B2dB|c2A2 A2df|
  g2gf g2Bd|g2f2 e2d2|c2ec B2dB|A2F2 G4:|
```

# Editors That Have Code Highlighting for ABC Music

[emacs-abc-mode](https://github.com/mkjunker/abc-mode)
[abc-vim](https://github.com/leesavide/abc-vim)
[SublimeABC](https://github.com/jimhawkridge/SublimeABC)

The most popular abc music program called `abcm2ps` in the [gentoo repositories](https://packages.gentoo.org/packages/media-sound/abcm2ps). It is written in the C programming language.

An article about abc music in [Fedora Magazine](https://fedoramagazine.org/rendering-music-notation-with-abc/).

**Comment by martanne** [comment]
We are currently using [Scintillua](https://github.com/orbitalquark/scintillua) for syntax highlighting. Please direct your feature request at upstream. Thanks.
