### ISSUE TITLE
Folds

### ISSUE THREAD

**Issue by machinedgod** [martanne/vis#887]
Hi,
I'd love to have folds functionality, similar to how vim has it (auto-folds on tag pairs, or manual fold creation).
I offer to help with few hours during weekends, but unfortunately don't have enough free time in this period to do it myself.

Example of custom autofolds, set on `{{{` and `}}}` pair:
![2020-11-02-104957_637x695_scrot](https://user-images.githubusercontent.com/5933618/97888579-4a111500-1cf9-11eb-9350-e7ee10b0617a.png)

**Comment by moesasji** [comment]
The lua lexers used by vis do have bits used to do folding by the upstream editors. As a result implementing this might be figuring out how to use that capability of the lexers within vis. See: [scintillua manual](https://orbitalquark.github.io/scintillua/manual.html) and search for folding. My guess would be that this is far from trivial....

**Comment by moesasji** [comment]
On a closer look this actually looks like a duplicate of #342

**Comment by machinedgod** [comment]
It is, sorry, I _did_ the search for similar issues but for one reason or another - I missed it. My apologies.
I will close this one.
