### ISSUE TITLE
Memory limit for large file

### ISSUE THREAD

**Issue by rickywu** [martanne/vis#897]
Can I limit memory usage when open large file?
Vis is very fast so I want to use it in prod env for open large log file but with limited memory, such as docker container.

**Comment by martanne** [comment]
You did not mention your OS, but in general these kind of issues are best dealt with on the operating system level, not by modifying individual applications. We also use external tools (e.g. `fmt(1)`, `tr(1)`) for certain functionality, meaning the restrictions should probably also apply to them.

In general vis may use lots of virtual memory, but large files are memory mapped read-only, enabling the OS to page out unused data. That is your limitation should ideally be based on physical not virtual memory. On Linux this can be [configured using cgroups](https://stackoverflow.com/questions/6882661/limit-physical-memory-per-process).
