### ISSUE TITLE
Makefile broken for parallel execution

### ISSUE THREAD

**Issue by MatzeB** [martanne/vis#9]
The "all" rule has "clean" and "options" as dependencies because those are not dependent on each other make can execute them in any order which leads to sometimes clean being executed after building vis when you use "make -j".

**Comment by martanne** [comment]
I guess "all" doesn't need to depend on "clean", this should fix it?

However if build time ever becomes a real issue, the project has gone terribly wrong.

**Comment by MatzeB** [comment]
yes removing "all" is the fix I am currently using. Although to work properly in all cases the Makefile would need some header dependency rules or at least all source files should depend on all header files...

However for a low overall buildtime like here the easiest solution may be just a single (phony) "$(CC) *.c -o vis" which has no dependency problems as it rebuilds each time, no .o file clutter in the directory and you get some link time opts for free. (And then one might wonder if this shouldn't rather be a shell script if there are no real dependencies left in the Makefile).

**Comment by jvoisin** [comment]
Removing `clean` from `all` since to be the way to go, even if the time gain is minimal.

**Comment by martanne** [comment]
I went the `$CC *.c -o vis` route, hope it works as expected.
