### ISSUE TITLE
edit . does not give me a file explorer

### ISSUE THREAD

**Issue by erf** [martanne/vis#90]
<code>edit .</code> does not give me a file explorer. it says <code>command failed</code>.

i'm on OSX (10.11.1)

**Comment by george-b** [comment]
I don't believe this is going t0 be implemented, from the [non-goals](https://github.com/martanne/vis#non-goals) section.

> file and directory browser

**Comment by erf** [comment]
Im just talking about simple file selection like he does In the animated gif demonstration

**Comment by martanne** [comment]
You need to get [vis-open](https://github.com/martanne/vis/blob/master/vis-open) working, i.e. `ls -1 | vis-open` should do something useful.

For that you will need either [dmenu](http://tools.suckless.org/dmenu/) or [slmenu](https://bitbucket.org/rafaelgg/slmenu), the latter is probably easier to get running on Mac OS X (no need for a X server).

**Comment by erf** [comment]
Great! Got it working with slmenu.
