### ISSUE TITLE
Some VIS_ACTION_* may not depend on other keybindings

### ISSUE THREAD

**Issue by andreafeletto** [martanne/vis#906]
When I disabled the arrow keys in NORMAL and INSERT mode (for self training purposes) I found out that in NORMAL mode `<O>` stopped working correctly.
Looking at the code I saw that the function `openline` (to which `<O>` is bounded by default) relies on `<Up>` actually moving the cursor to the line above.
Shouldn't basic commands like this be independent of keybindings, or is it intentional?

For reference, to disable the arrow keys I added the following to the INIT event in visrc.lua:
```lua
keys = {'<Left>', '<Right>', '<Up>', '<Down>'}
for _, key in ipairs(keys) do
    vis:map(vis.modes.NORMAL, key, '')
    vis:map(vis.modes.INSERT, key, '')
end
```

**Comment by martanne** [comment]
Hi, thanks for the report. This particular case should be fixed in 8c5205ad56f0bd76d3f9cd4a85eba9e01d071228. For now we still depend on `<Escape>` and `<Enter>`.
