### ISSUE TITLE
Add support for themeable colors in (default) theme(s)

### ISSUE THREAD

**Issue by moesasji** [martanne/vis#917]
The use of themeable colors can give surprising behavior as some themes have a `colors` table defined and exported - [solarized.lua:23](https://github.com/martanne/vis/blob/40c387aca214f701cd316c63b290ba7f35abbe3a/lua/themes/solarized.lua#L23), but the default one doesn't. (And even solarized.lua doesn't currently have the `black` color for the `hr` rule used in the markdown lexer.)

Suggested fix in the pull-request that triggered this issue: add a `colors` table to all the themes, so vis could use unmodified lexers from Scintillua.

_Originally posted by @lepotic in https://github.com/martanne/vis/issues/916#issuecomment-749124065_

**Comment by martanne** [comment]
I think this is already fixed by a commit included in the scintillua branch? If not then feel free to re-open the issue with a more specific description of the problem.
