### ISSUE TITLE
dw should not delete the new line

### ISSUE THREAD

**Issue by FoundOne** [martanne/vis#923]
How to reproduce:
1. Open a text file.
2. Go to on the last word of a line.
3. Press dw.

What happens:
It deletes the word and the next new line.

What should happen:
It should just delete the word.

Edit: I noticed that it happens with any whitespace.

**Comment by erf** [comment]
I believe `vis` differ from `vim` regarding this as described [here](https://github.com/martanne/vis/wiki/Differences-from-Vi(m)#newline-addressability)

**Comment by FoundOne** [comment]
Oh, so it's supposed to do that. Ok. I'm sorry.

**Comment by ninewise** [comment]
Yes, this can be a bit confusing at first. To just delete the word, use `de`.

(could you close the issue if this seems reasonable?)

**Comment by FoundOne** [comment]
Yes. Thanks for the advice.

**Comment by martanne** [comment]
This is not so much about newline address ability, but the fact that `w` and `dw` i.e. when used with an operator does not cover the same range.
