### ISSUE TITLE
:set backupcopy=yes in vis equivalent

### ISSUE THREAD

**Issue by jgarte** [martanne/vis#938]
What is the equivalent of vim's `:set backupcopy=yes`?

I ask because hot-module reloading is not working in vis with the default settings but it does work in vim with `:set backupcopy=yes`

https://parceljs.org/hmr.html#safe-write

Any help is greatly appreciated.

**Comment by jgarte** [comment]
I think I was able to figure it out by setting the following:

`:set savemethod inplace`

Would you say that this is equivalent to `:set backupcopy=yes`?

Hot-reloading seems to be working now with vis after setting `:set savemethod inplace`

Let me know if I should close this issue.

**Comment by TwoFinger** [comment]
> Would you say that this is equivalent to :set backupcopy=yes?

I believe it is, see [text-io.c:386](https://github.com/martanne/vis/blob/40c387aca214f701cd316c63b290ba7f35abbe3a/text-io.c#L386)

Also related - #758

**Comment by jgarte** [comment]
@TwoFinger Thanks for pointing that out! It is much appreciated

I'll close this now. If anyone has any other comments regarding this feel free to comment further in the closed issue.
