### ISSUE TITLE
Wrong links in some parts of the documentation (ex. FAQ)

### ISSUE THREAD

**Issue by luishgh** [martanne/vis#943]
![image](https://user-images.githubusercontent.com/51053603/114951004-96c15600-9e2a-11eb-976d-914e9c0998d4.png)
So, starting today, github.com links of github pages websites won't redirect to github.io, so all of the links to https://martanne.github.io/vis/ that haven't been changed to this domain stopped working, this one in the key bindings section of the FAQ is an example: 
![image](https://user-images.githubusercontent.com/51053603/114951376-fb7cb080-9e2a-11eb-8308-559ba28b8aa4.png)

**Comment by rnpnr** [comment]
I'm closing this since they should all be fixed at this point.
