### ISSUE TITLE
Type capital U to return the line to it's original state

### ISSUE THREAD

**Issue by erf** [martanne/vis#95]
Type capital U to return the line to it's original state. #vimtutor

**Comment by jrdccx** [comment]
Please and thank you to capital U redo.

**Comment by martanne** [comment]
This is not possible because vis has no real concept of a line, instead it operates on a byte stream (this is the reason why it is more performant for large files) which can be snapshotted at arbitrary times.

**Comment by erf** [comment]
Ok. Thanks.
