### ISSUE TITLE
Freenode move?

### ISSUE THREAD

**Issue by lanodan** [martanne/vis#951]
With freenode having been took over (<https://en.wikipedia.org/wiki/Freenode#Ownership_change_and_conflict>) many channels moved with former freenode staff to [libera.chat](https://libera.chat) or other networks like OFTC.

I ended up leaving Freenode ~definitely some days ago and now idle in `#vis` and `#vis-editor` on Libera.Chat.

**Comment by crabbedhaloablution** [comment]
Helpful link: [How to register an organization with Libera](https://libera.chat/chanreg)

**Comment by mcepl** [comment]
Already happened (#vis-editor IRC channel on libera). This ticket can be closed.
