### ISSUE TITLE
theme: acme

### ISSUE THREAD

**Issue by ghost** [martanne/vis#955]
consider adding the acme theme to themes provided as part of vis.

**Comment by TomHarned** [comment]
I've made an acme theme I use regularly. It's still a work in progress, but's definitely usable: https://github.com/TomHarned/acme-ish. I based it off of this one, which is linked right on the vis github page:

https://raw.githubusercontent.com/timoha/vis-acme/master/acme.lua

The same person has a number of other themes too.

**Comment by mcepl** [comment]
@ninewise, this probably should be closed, because the plugins exists.
