### ISSUE TITLE
syntax highlight for conky, remind and groff

### ISSUE THREAD

**Issue by Docbroke** [martanne/vis#961]
Hi,
I have recently moved from vim to vis and I am missing syntax highlighting for conky, remind and groff (mom macros) files. I tried to find out lexer files for them but couldn't get any. Any  pointers would be great.
thanks

**Comment by ninewise** [comment]
Easiest method is to find a similar language among [the list](https://github.com/orbitalquark/scintillua/tree/default/lexers) and add it to scintillua (and your local lexers).

**Comment by chilledfrogs** [comment]
I'm currently working on a Roff highlighter actually

**Comment by chilledfrogs** [comment]
Question @Docbroke: I am currently trying to make generic Roff highlighting rules for any macro set (or a lack thereof), but do you think it would be really useful to have specific highlighting for standard macros for instance and maybe therefore separate highlighting rules per macro set (and 1 for generic/none)?

**Comment by Docbroke** [comment]
I don't have any experience  regarding how syntax highlight works. 
Any file written using some macro can have generic groff requests as well, so you can use .bp to break page even when you are using .mom or .ms macros. Therefore generic rules will be needed, and specific rules for macro can be added to that.

**Comment by mcepl** [comment]
@ninewise, this should be probably closed, or if still applicable, this should be moved to the https://github.com/orbitalquark/scintillua/issues.

**Comment by mcepl** [comment]
@rnpnr ??? What about this one?

**Comment by rnpnr** [comment]
I think groff is supported upstream since orbitalquark/scintillua@369ee2b.
I'll add an item to the release plans to resync the lexers.

The others can be requested upstream. From my perspective it is better
if we don't implement our own lexers unless there is a very compelling
reason to do so.
