### ISSUE TITLE
Does this work on plan9?

### ISSUE THREAD

**Issue by tucnak** [martanne/vis#962]
The nine is not POSIX-complaint, afaik. Can I use this as a drop–in for sam, in any reasonable capacity that is?

**Comment by mcepl** [comment]
See the requirements in README.md. First of them is “In order to build vis you will need a C99 compiler, a POSIX.1-2008 compatible environment as well as: …”.

**Comment by mcepl** [comment]
Actually, it may be possible somebody tried to port it to plan9 using https://plan9.io/sys/doc/ape.pdf but I have never heard about it.

**Comment by mcepl** [comment]
@ninewise Shouldn't this be closed? It is now just empty chat, I am afraid.

**Comment by mcepl** [comment]
Actually, there is https://github.com/okvik/lu9, build with APE, so perhaps it is not completely silly idea.
