### ISSUE TITLE
rst lexer does not lex urls properly 

### ISSUE THREAD

**Issue by jgarte** [martanne/vis#967]
![rst_link_not_lexed](https://user-images.githubusercontent.com/47760695/126719588-5db875d4-af86-4cef-a31d-09d69eded324.png)

wdyt?

**Comment by jgarte** [comment]
At line 13 column 61

**Comment by mcepl** [comment]
Because we all hope https://github.com/martanne/vis/pull/1018 is merged soon, this will be then non-issue for vis, and it should be filed upstream at https://github.com/orbitalquark/scintillua/issues.
