### ISSUE TITLE
'Matching parantheses search' ( Lesson 4.3 ) fails on vimtutor

### ISSUE THREAD

**Issue by erf** [martanne/vis#97]
'Matching parantheses search' ( Lesson 4.3 ) fails. 
% does not match parantheses on test line. #vimtutor

**Comment by martanne** [comment]
This particular test case should now work. If there are strings delimited by `"` involved, then the vis behavior will likely be different.

Also if somebody could explain me what vim does when performing a `%` motion while the cursor is not on a special symbol, that would be appreciated. In my quick tests it seemed like it sometimes moves to the previous opening symbol and sometimes to the next closing one. I couldn't really make sense of it ...

**Comment by erf** [comment]
Great work.

It seems to me if the cursor is after the opening bracket, and before an inner bracket, it goes to the closing bracket of the inner bracket, but if it is no inner bracket next, it goes to the opening parent bracket.
