### ISSUE TITLE
Bug: lexing ruby backticks

### ISSUE THREAD

**Issue by jgarte** [martanne/vis#978]
If you do something like the following it breaks the syntax highlighting in ruby files and thinks the rest of the buffer is a backtick command string waiting to be closed:

```ruby
when /^```/
  :verbatim
```

or this

```ruby
when /^`/
  :verbatim
``` 

The above is taken from this gemtext parser code:

https://github.com/genenetwork/gemini-rb/blob/main/lib/gemini-rb/parser.rb#L64

relevant place in vis lua code:

https://github.com/martanne/vis/blob/master/lua/lexers/ruby.lua#L37

**Comment by mcepl** [comment]
@ninewise, this should probably be sent upstream to https://github.com/orbitalquark/scintillua/issues, right?

**Comment by ninewise** [comment]
Yes. I'll be closing this here.
