### ISSUE TITLE
Lesson 4.4: The subsitute command in vimtutor fails.

### ISSUE THREAD

**Issue by erf** [martanne/vis#98]
<code>:s/thee/the</code> fails with:
<pre>Command failed: sed: 1: "s/thee/the": unterminated substitute in regular expression</pre>
#vimtutor

**Comment by martanne** [comment]
This is expected since we use `sed(1)` for now, hence you must use the correct [POSIX syntax](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/sed.html).

**Comment by erf** [comment]
Ok. Thanks.
