### ISSUE TITLE
Cannot execute external command inside {} grouping

### ISSUE THREAD

**Issue by honestSalami** [martanne/vis#980]
I'm trying to insert selection from clipboard and inserting a newline after in a single grouped command, however, ```:{< xsel -ob a/\n/}``` returns 'unknown command'

Does anyone know how to accomplish this?

**Comment by jpaulogg** [comment]
I think that's not possible. But you can group shell commands like this:

`: < { xsel -ob; echo; }`

**Comment by honestSalami** [comment]
Thanks for the tip! I got a working version of my idea by:
```qa^M:< xsel -ob^Mq``` and running the defined macro with ```@a```.
