### ISSUE TITLE
Don't store duplicates in command history

### ISSUE THREAD

**Issue by adigitoleo** [martanne/vis#993]
I didn't seen this explicitly mentioned (could have missed it), but it would be nice if the command buffer didn't store duplicates. Some commands are used fairly frequently, e.g. `:w`, and it tends to clutter the command buffer after some time.

**Comment by adigitoleo** [comment]
Right, that's nice. However, I think this could be preserved while also avoiding duplicates. The check would need to be performed before the line is added.

**Comment by jpaulogg** [comment]
> If I get time to look into vis-menu, I guess I could set up some custom keybindings to cycle through previous "commands" (i.e. lines of the command buffer) while skipping duplicates or something like that. Sorry for the noise.

You could use a plugin for line completion. I wrote [one](https://github.com/jpaulogg/vis-ins-completion/) myself.

**Comment by ninewise** [comment]
It might also be possible to have a WIN_OPEN event on the command window which removes duplicates.

**Comment by adigitoleo** [comment]
> It might also be possible to have a WIN_OPEN event on the command window which removes duplicates.

True, I'd just need some way to detect the command window. That doesn't seem to be exposed to the API yet, so this would have to be done internally.
